{
  "hash": "62837f123fa9793920189eea1a3e69dc",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Classification and Decision Trees\"\nauthor: \"Diego Villalba\"\ndate: today\nlang: en\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    toc-title: \"Contents\"\n    number-sections: true\n    code-fold: true\n    code-tools: true\n    code-summary: \"Show code\"\n    fig-align: center\n    theme: cosmo\n    highlight-style: github\n    smooth-scroll: true\n  pdf:\n    toc: true\n    toc-depth: 3\n    number-sections: true\n    documentclass: scrbook\n    papersize: letter\n    fontsize: 11pt\n    geometry: margin=2.5cm\n    keep-tex: false\nexecute:\n  echo: true\n  warning: false\n  message: false\n  cache: false\nbibliography: [referencias_clasificacion_arboles.bib, ../../../references.bib]\ncrossref:\n  fig-title: \"Figure\"\n  tbl-title: \"Table\"\n  eq-prefix: \"Eq.\"\njupyter: python3\n---\n\n## Introduction\n\nClassification is one of the fundamental tasks in supervised learning. Its goal is to learn a decision rule from previously observed examples capable of assigning a categorical label to new observations. Unlike numerical prediction (regression), where the output belongs to a continuous or ordered discrete space, in classification the output belongs to a finite set of discrete classes: for example, `spam` or `non-spam`, `approve` or `reject`, `positive`, `negative`, or `neutral` [@hastie2009; @james2021].\n\nIn general terms, a classification problem starts with a training dataset composed of pairs\n\n$$\n\\mathcal{D} = \\{(\\mathbf{x}_i, y_i)\\}_{i=1}^{n},\n$$\n\nwhere $\\mathbf{x}_i \\in \\mathcal{X}$ represents the predictor variables or available observations, while $y_i \\in \\mathcal{Y}$ represents the target class. The objective is to construct a function\n\n$$\n\\hat{f}: \\mathcal{X} \\to \\mathcal{Y}\n$$\n\nthat generalizes well to unseen data.\n\nThis chapter explores decision trees as interpretable classification models. The exposition focuses on the general logic of tree induction, Hunt's algorithm, the ID3 algorithm, entropy, information gain, and the extraction of classification rules.\n\n## Classification as a Supervised Problem\n\nIn a classification problem, historical examples are available where the true class is known. The model leverages these examples to learn patterns connecting explanatory variables to target labels.\n\nTypical examples include:\n\n- Classifying an email as `spam` or `non-spam`;\n- Deciding whether a credit application should be `approved` or `rejected`;\n- Identifying whether a patient presents hypertension;\n- Categorizing a review as `positive`, `negative`, or `neutral`;\n- Predicting whether a customer will purchase a laptop.\n\nThe distinction between classification and regression depends on the type of target variable. If the output is categorical, it is a classification problem. If the output is numerical, it is a regression problem.\n\n| Task | Output Type | Example |\n|---|---:|---|\n| Classification | Categorical | Pass / Fail |\n| Regression | Numerical | Tomorrow's Temperature |\n\n::: {.callout-note appearance=\"minimal\"}\nDefinition. A supervised classification problem consists of estimating a function $\\hat{f}$ that maps each observation $\\mathbf{x}$ to a class $y$ within a finite set of labels $\\mathcal{Y}$:\n$$\n\\hat{f}: \\mathcal{X} \\to \\mathcal{Y}, \\qquad |\\mathcal{Y}| < \\infty.\n$$ {#eq-classification-function}\n:::\n\n## Training, Testing, and Generalization\n\nClassification workflows are typically divided into two main phases: training and testing. During training, the algorithm adjusts its internal rules using labeled data. During testing, the model is evaluated on unseen data to estimate its generalization capability.\n\nThis separation is essential because a model can memorize training data without learning useful underlying patterns. This phenomenon is known as overfitting. In decision trees, overfitting occurs when a tree grows too deep, creating highly specific partitions for individual training cases [@breiman1984; @quinlan1986induction].\n\n::: {.callout-note appearance=\"minimal\"}\nDefinition. Given a training set $\\mathcal{D}_{\\text{train}}$ and a test set $\\mathcal{D}_{\\text{test}}$, the generalization capability of a classifier is evaluated by estimating its performance on examples not used during model fitting:\n$$\n\\mathcal{D} = \\mathcal{D}_{\\text{train}} \\cup \\mathcal{D}_{\\text{test}}, \\qquad\n\\mathcal{D}_{\\text{train}} \\cap \\mathcal{D}_{\\text{test}} = \\varnothing.\n$$ {#eq-train-test-split}\n:::\n\n## Data Preparation Before Classifier Building\n\nBefore training a classifier, data preparation is required. Model quality depends directly on feature quality. Three common tasks are data cleaning, transformation, and dimensionality reduction.\n\nData cleaning involves correcting invalid or inconsistent entries (such as negative ages or misspelled categories) and deciding how to handle missing values. Data transformation includes encoding categorical variables, scaling numerical features, and parsing dates into usable features. Dimensionality reduction removes redundant, irrelevant, or noisy features.\n\nFor decision trees, feature scaling is less critical than in linear models or neural networks, as trees are invariant to monotonic feature transformations. However, category quality, missing value strategies, and handling of continuous features remain important considerations [@james2021; @geron2022hands].\n\n::: {#edca599a .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\n\nclientes = pd.DataFrame({\n    \"income\": [\"high\", \"low\", \"medium\", \"low\", \"medium\"],\n    \"credit_history\": [\"good\", \"bad\", \"good\", \"fair\", \"bad\"],\n    \"debt\": [\"low\", \"high\", \"low\", \"high\", \"medium\"],\n    \"stable_employment\": [\"yes\", \"no\", \"yes\", \"no\", \"yes\"],\n    \"decision\": [\"approve\", \"reject\", \"approve\", \"reject\", \"reject\"]\n})\n\nclientes\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>income</th>\n      <th>credit_history</th>\n      <th>debt</th>\n      <th>stable_employment</th>\n      <th>decision</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>high</td>\n      <td>good</td>\n      <td>low</td>\n      <td>yes</td>\n      <td>approve</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>low</td>\n      <td>bad</td>\n      <td>high</td>\n      <td>no</td>\n      <td>reject</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>medium</td>\n      <td>good</td>\n      <td>low</td>\n      <td>yes</td>\n      <td>approve</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>low</td>\n      <td>fair</td>\n      <td>high</td>\n      <td>no</td>\n      <td>reject</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>medium</td>\n      <td>bad</td>\n      <td>medium</td>\n      <td>yes</td>\n      <td>reject</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThe example above represents a binary classification task: deciding whether to approve or reject a credit application. Predictor variables are categorical, and the target label is `decision`.\n\n## Decision Trees\n\nA decision tree is a predictive model that organizes sequential decisions in a hierarchical structure. Each internal node represents a test on an attribute, each branch represents a test outcome, and each leaf node assigns a class. Predicting a new observation involves traversing the tree from the root to a leaf.\n\nDecision trees are particularly valued for their interpretability. Unlike opaque models, a tree can be translated directly into human-readable IF-THEN rules [@breiman1984; @quinlan1993c45].\n\n::: {.callout-note appearance=\"minimal\"}\nDefinition. A classification decision tree is a hierarchical structure composed of internal nodes, branches, and leaves. Each internal node applies a test $h_j(\\mathbf{x})$, each branch corresponds to a test outcome, and each leaf assigns a class $c \\in \\mathcal{Y}$:\n$$\nT(\\mathbf{x}) = c, \\qquad c \\in \\mathcal{Y}.\n$$ {#eq-decision-tree}\n:::\n\nCore elements of a tree include:\n\n| Element | Description |\n|---|---|\n| Root Node | The topmost node containing all training examples before splitting. |\n| Internal Node | A node where an attribute test is evaluated to split the dataset. |\n| Branch | A outcome path originating from a node test. |\n| Leaf Node | A terminal node assigning a final class label. |\n\n## Data Partitioning in Decision Trees\n\nTree induction relies on recursively partitioning data. At each node, an attribute is chosen to split the dataset into subsets.\n\nFor categorical attributes, the tree may create one branch per category. For instance, if `Outlook` takes values `Sunny`, `Overcast`, and `Rain`, three branches are formed. In binary trees, categories are evaluated via boolean tests like \"Is color red?\".\n\nFor continuous attributes, a split threshold must be selected. For example, `Income` might be split into `Income <= 25000` and `Income > 25000`. Although ID3 was designed primarily for categorical features, extensions such as C4.5 handle continuous variables smoothly [@quinlan1986induction; @quinlan1993c45].\n\n## Hunt's Algorithm\n\nHunt's algorithm outlines a general recursive framework for building decision trees. The core logic is simple: if all examples reaching a node belong to the same class, the node becomes a leaf. Otherwise, an attribute test is chosen to partition the data, and the procedure recurses on each subset.\n\nLet $D_t$ be the set of training records reaching node $t$. The algorithm proceeds as follows:\n\n1. If all records in $D_t$ belong to class $y$, create a leaf node with label $y$.\n2. If $D_t$ is empty, create a leaf node labeled with a default class (typically the majority class of the parent node).\n3. If records belong to multiple classes, select an attribute test to split $D_t$.\n4. Partition $D_t$ into subsets based on test outcomes.\n5. Recursively apply the algorithm to each subset.\n\nThis approach is top-down (moving from root to leaves) and follows a divide-and-conquer strategy.\n\n::: {.callout-note appearance=\"minimal\"}\nDefinition. Let $D_t$ be the set of examples reaching node $t$. A node is pure if all examples in $D_t$ belong to the exact same class:\n$$\n\\exists c \\in \\mathcal{Y} \\; \\text{such that} \\; y_i = c \\quad \\forall (\\mathbf{x}_i,y_i) \\in D_t.\n$$ {#eq-pure-node}\n:::\n\n## Stopping Criteria\n\nTree partitioning cannot continue indefinitely. Common stopping criteria include:\n\n- All examples at the node belong to a single class;\n- No remaining attributes are available for splitting;\n- The number of examples at the node falls below a minimum threshold;\n- Maximum tree depth has been reached;\n- Information gain from further splitting falls below a minimum threshold.\n\nIn classic ID3, if no attributes remain and examples belong to multiple classes, the node is assigned the majority class label.\n\n## ID3: Feature Selection via Information Gain\n\nID3 (*Iterative Dichotomiser 3*) is a classic decision tree algorithm proposed by Quinlan. It uses information gain at each node to select the attribute that best separates the target classes [@quinlan1986induction].\n\nThe intuition is that a good splitting attribute produces subsets that are purer (more homogeneous) than the original set. To quantify impurity, ID3 uses entropy from information theory [@shannon1948mathematical].\n\nThe workflow is:\n\n1. Start with all training records at the root node.\n2. Calculate current dataset entropy.\n3. Evaluate all available candidate attributes.\n4. Compute weighted average entropy after splitting for each attribute.\n5. Select the attribute yielding highest Information Gain.\n6. Recurse on child branches.\n\n## Entropy as an Impurity Measure\n\nEntropy measures the degree of randomness or impurity in a dataset. If all examples belong to a single class, entropy is 0. If classes are evenly split, entropy reaches its maximum value.\n\n::: {.callout-note appearance=\"minimal\"}\nDefinition. Let $S$ be a dataset with $c$ target classes, and let $p_i$ be the proportion of examples belonging to class $i$. The entropy of $S$ is defined as:\n$$\nH(S) = -\\sum_{i=1}^{c} p_i \\log_2(p_i).\n$$ {#eq-entropy}\n:::\n\nBy convention, $0\\log_2(0)=0$, since $\\lim_{p \\to 0^+} p\\log_2(p) = 0$.\n\nFor example, if $S$ contains 15 records with 9 `Yes` and 6 `No` labels:\n\n$$\np(\\text{Yes}) = \\frac{9}{15}, \\qquad p(\\text{No}) = \\frac{6}{15}.\n$$\n\nThus,\n\n$$\nH(S) = -\\frac{9}{15}\\log_2\\left(\\frac{9}{15}\\right)\n       -\\frac{6}{15}\\log_2\\left(\\frac{6}{15}\\right)\n       \\approx 0.971.\n$$\n\n::: {#6a17abc2 .cell execution_count=2}\n``` {.python .cell-code}\nimport numpy as np\n\ndef entropy(labels):\n    values, counts = np.unique(labels, return_counts=True)\n    probs = counts / counts.sum()\n    return -np.sum(probs * np.log2(probs))\n\nlabels = [\"Yes\"] * 9 + [\"No\"] * 6\nentropy(labels)\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```\nnp.float64(0.9709505944546686)\n```\n:::\n:::\n\n\n## Information Gain\n\nInformation Gain measures the reduction in entropy achieved by partitioning a dataset on a given attribute. A split producing pure child nodes yields high information gain.\n\n::: {.callout-note appearance=\"minimal\"}\nDefinition. Let $S$ be a dataset and $A$ an attribute taking values $v \\in \\operatorname{Values}(A)$. If $S_v$ denotes the subset of examples where attribute $A$ takes value $v$, Information Gain is defined as:\n$$\n\\operatorname{Gain}(S,A) = H(S) - \\sum_{v\\in \\operatorname{Values}(A)} \\frac{|S_v|}{|S|} H(S_v).\n$$ {#eq-information-gain}\n:::\n\nThe first term, $H(S)$, represents initial dataset impurity. The second term represents expected entropy after splitting, weighted by subset sizes. Information Gain reflects the impurity reduction obtained by splitting on $A$.\n\n## Example: Building a Tree for Baseball Game Prediction\n\nConsider a dataset predicting whether a baseball game will be played (`Play`). Predictor features are `Outlook`, `Temperature`, `Humidity`, and `Wind`.\n\n::: {#3e3faf5f .cell execution_count=3}\n``` {.python .cell-code}\nimport pandas as pd\n\ndf = pd.DataFrame({\n    \"Outlook\": [\n        \"Sunny\", \"Sunny\", \"Overcast\", \"Rain\", \"Rain\",\n        \"Rain\", \"Overcast\", \"Sunny\", \"Sunny\", \"Rain\",\n        \"Sunny\", \"Overcast\", \"Overcast\", \"Rain\", \"Sunny\"\n    ],\n    \"Temperature\": [\n        \"Hot\", \"Hot\", \"Hot\", \"Mild\", \"Cool\",\n        \"Cool\", \"Cool\", \"Mild\", \"Cool\", \"Mild\",\n        \"Mild\", \"Mild\", \"Hot\", \"Mild\", \"Cool\"\n    ],\n    \"Humidity\": [\n        \"High\", \"High\", \"High\", \"High\", \"Normal\",\n        \"Normal\", \"Normal\", \"High\", \"Normal\", \"Normal\",\n        \"Normal\", \"High\", \"Normal\", \"High\", \"High\"\n    ],\n    \"Wind\": [\n        \"Weak\", \"Strong\", \"Weak\", \"Weak\", \"Weak\",\n        \"Strong\", \"Strong\", \"Weak\", \"Weak\", \"Weak\",\n        \"Weak\", \"Strong\", \"Weak\", \"Strong\", \"Weak\"\n    ],\n    \"Play\": [\n        \"No\", \"No\", \"Yes\", \"Yes\", \"Yes\",\n        \"No\", \"Yes\", \"No\", \"Yes\", \"Yes\",\n        \"Yes\", \"Yes\", \"Yes\", \"No\", \"No\"\n    ]\n})\n\ndf\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Outlook</th>\n      <th>Temperature</th>\n      <th>Humidity</th>\n      <th>Wind</th>\n      <th>Play</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Sunny</td>\n      <td>Hot</td>\n      <td>High</td>\n      <td>Weak</td>\n      <td>No</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Sunny</td>\n      <td>Hot</td>\n      <td>High</td>\n      <td>Strong</td>\n      <td>No</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Overcast</td>\n      <td>Hot</td>\n      <td>High</td>\n      <td>Weak</td>\n      <td>Yes</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Rain</td>\n      <td>Mild</td>\n      <td>High</td>\n      <td>Weak</td>\n      <td>Yes</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Rain</td>\n      <td>Cool</td>\n      <td>Normal</td>\n      <td>Weak</td>\n      <td>Yes</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>Rain</td>\n      <td>Cool</td>\n      <td>Normal</td>\n      <td>Strong</td>\n      <td>No</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>Overcast</td>\n      <td>Cool</td>\n      <td>Normal</td>\n      <td>Strong</td>\n      <td>Yes</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>Sunny</td>\n      <td>Mild</td>\n      <td>High</td>\n      <td>Weak</td>\n      <td>No</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>Sunny</td>\n      <td>Cool</td>\n      <td>Normal</td>\n      <td>Weak</td>\n      <td>Yes</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>Rain</td>\n      <td>Mild</td>\n      <td>Normal</td>\n      <td>Weak</td>\n      <td>Yes</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>Sunny</td>\n      <td>Mild</td>\n      <td>Normal</td>\n      <td>Weak</td>\n      <td>Yes</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>Overcast</td>\n      <td>Mild</td>\n      <td>High</td>\n      <td>Strong</td>\n      <td>Yes</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>Overcast</td>\n      <td>Hot</td>\n      <td>Normal</td>\n      <td>Weak</td>\n      <td>Yes</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>Rain</td>\n      <td>Mild</td>\n      <td>High</td>\n      <td>Strong</td>\n      <td>No</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>Sunny</td>\n      <td>Cool</td>\n      <td>High</td>\n      <td>Weak</td>\n      <td>No</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nFirst, compute initial dataset entropy:\n\n::: {#ef7c2ccb .cell execution_count=4}\n``` {.python .cell-code}\nH_total = entropy(df[\"Play\"])\nH_total\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```\nnp.float64(0.9709505944546686)\n```\n:::\n:::\n\n\nWith 9 `Yes` and 6 `No` instances, initial entropy is approximately $0.971$.\n\nNext, evaluate Information Gain for each attribute:\n\n::: {#11d12902 .cell execution_count=5}\n``` {.python .cell-code}\ndef information_gain(data, attribute, target):\n    total_entropy = entropy(data[target])\n    weighted_entropy = 0.0\n    for value, subset in data.groupby(attribute):\n        weight = len(subset) / len(data)\n        weighted_entropy += weight * entropy(subset[target])\n    return total_entropy - weighted_entropy\n\nattributes = [\"Outlook\", \"Temperature\", \"Humidity\", \"Wind\"]\n\ngains = {\n    attr: information_gain(df, attr, \"Play\")\n    for attr in attributes\n}\n\npd.Series(gains).sort_values(ascending=False)\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```\nOutlook        0.279982\nHumidity       0.185805\nWind           0.059773\nTemperature    0.013315\ndtype: float64\n```\n:::\n:::\n\n\nGain values are approximately:\n\n| Attribute | Information Gain |\n|---|---:|\n| Outlook | 0.280 |\n| Humidity | 0.186 |\n| Wind | 0.145 |\n| Temperature | 0.013 |\n\n`Outlook` yields the highest gain and is selected as the root node.\n\n## Branch Construction Following Root Selection\n\nSplitting on `Outlook` creates three child branches:\n\n- `Outlook = Overcast`;\n- `Outlook = Sunny`;\n- `Outlook = Rain`.\n\nFor `Outlook = Overcast`, all 4 examples belong to class `Yes` ($H = 0$), forming a pure leaf node.\n\n::: {#06c3f9c8 .cell execution_count=6}\n``` {.python .cell-code}\ndf[df[\"Outlook\"] == \"Overcast\"]\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Outlook</th>\n      <th>Temperature</th>\n      <th>Humidity</th>\n      <th>Wind</th>\n      <th>Play</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>2</th>\n      <td>Overcast</td>\n      <td>Hot</td>\n      <td>High</td>\n      <td>Weak</td>\n      <td>Yes</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>Overcast</td>\n      <td>Cool</td>\n      <td>Normal</td>\n      <td>Strong</td>\n      <td>Yes</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>Overcast</td>\n      <td>Mild</td>\n      <td>High</td>\n      <td>Strong</td>\n      <td>Yes</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>Overcast</td>\n      <td>Hot</td>\n      <td>Normal</td>\n      <td>Weak</td>\n      <td>Yes</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nFor `Outlook = Sunny`, class mixture remains (2 `Yes`, 4 `No`), requiring further evaluation on remaining features: `Temperature`, `Humidity`, `Wind`.\n\n::: {#1e645027 .cell execution_count=7}\n``` {.python .cell-code}\nsunny = df[df[\"Outlook\"] == \"Sunny\"]\nremaining = [\"Temperature\", \"Humidity\", \"Wind\"]\n\npd.Series({\n    attr: information_gain(sunny, attr, \"Play\")\n    for attr in remaining\n}).sort_values(ascending=False)\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```\nHumidity       0.918296\nTemperature    0.251629\nWind           0.109170\ndtype: float64\n```\n:::\n:::\n\n\n`Humidity` yields the highest gain (0.918). Splitting on `Humidity`:\n\n- `Outlook = Sunny` and `Humidity = High` $\\implies$ `Play = No`;\n- `Outlook = Sunny` and `Humidity = Normal` $\\implies$ `Play = Yes`.\n\nFor `Outlook = Rain`, evaluating remaining features identifies `Wind` as the top splitter (gain = 0.971).\n\n::: {#2751def6 .cell execution_count=8}\n``` {.python .cell-code}\nrain = df[df[\"Outlook\"] == \"Rain\"]\n\npd.Series({\n    attr: information_gain(rain, attr, \"Play\")\n    for attr in remaining\n}).sort_values(ascending=False)\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```\nWind           0.970951\nTemperature    0.019973\nHumidity       0.019973\ndtype: float64\n```\n:::\n:::\n\n\nSplitting on `Wind`:\n\n- `Outlook = Rain` and `Wind = Weak` $\\implies$ `Play = Yes`;\n- `Outlook = Rain` and `Wind = Strong` $\\implies$ `Play = No`.\n\n## Final Tree Structure\n\nThe final decision tree is summarized as:\n\n```{mermaid}\nflowchart TD\n    A[Outlook]\n    A -->|Overcast| B[Yes]\n    A -->|Sunny| C[Humidity]\n    A -->|Rain| D[Wind]\n    C -->|High| E[No]\n    C -->|Normal| F[Yes]\n    D -->|Weak| G[Yes]\n    D -->|Strong| H[No]\n```\n\nNotice that not all features are required across all branches. In the `Overcast` branch, `Temperature`, `Humidity`, and `Wind` are unused because class determination is complete.\n\n```{=html}\n<div id=\"id3-root\" style=\"font-family:Georgia,serif;background:#f8f9fb;border:1px solid #d8dee6;border-radius:8px;padding:20px 24px;margin:2em 0;\">\n\n  <div style=\"text-align:center;margin-bottom:10px;\">\n    <span style=\"font-size:1.05em;font-weight:bold;color:#1a2e45;\">ID3 Algorithm — Step-by-Step Construction</span><br>\n    <span style=\"font-size:0.82em;color:#666;\">Dataset: Play Baseball? &nbsp;·&nbsp; n = 15 examples &nbsp;·&nbsp; 4 attributes</span>\n  </div>\n\n  <div style=\"text-align:center;margin-bottom:8px;\">\n    <span id=\"id3-badge\" style=\"background:#1a3a5c;color:#fff;padding:3px 16px;border-radius:12px;font-size:0.8e;\"></span>\n  </div>\n\n  <svg id=\"id3-svg\" width=\"680\" height=\"368\" style=\"display:block;margin:0 auto;overflow:visible;\"></svg>\n\n  <div id=\"id3-panel\" style=\"margin:8px 0 6px;padding:10px 14px;background:#fff;border:1px solid #e0e5ed;border-radius:6px;font-size:0.82em;min-height:76px;\"></div>\n\n  <div id=\"id3-desc\" style=\"font-size:0.84em;color:#3a3a3a;line-height:1.6;min-height:52px;margin:6px 4px 12px;\"></div>\n\n  <div style=\"display:flex;align-items:center;justify-content:center;gap:14px;\">\n    <button id=\"id3-prev\" class=\"id3btn\" onclick=\"id3Nav(-1)\">← Previous</button>\n    <span id=\"id3-ctr\" style=\"font-size:0.82em;color:#666;min-width:80px;text-align:center;\"></span>\n    <button id=\"id3-next\" class=\"id3btn\" onclick=\"id3Nav(+1)\">Next →</button>\n  </div>\n</div>\n\n<style>\n.id3btn{padding:5px 16px;border:1px solid #aab;background:#fff;border-radius:4px;cursor:pointer;\n        font-family:Georgia,serif;font-size:0.82em;transition:background .12s;}\n.id3btn:hover{background:#eef2f7;}.id3btn:disabled{opacity:0.38;cursor:default;}\n</style>\n\n<script>\n(function(){\n\n/* ── nodes & edges ─────────────────────────────────────── */\nconst N = {\n  root:    {x:340, y:52,  lbl:\"Outlook\",     t:\"int\"},\n  nub_lf:  {x:90,  y:200, lbl:\"Yes\",         t:\"leaf\", cls:\"si\"},\n  humedad: {x:285, y:200, lbl:\"Humidity\",    t:\"int\"},\n  viento:  {x:548, y:200, lbl:\"Wind\",        t:\"int\"},\n  alta_lf: {x:185, y:335, lbl:\"No\",          t:\"leaf\", cls:\"no\"},\n  norm_lf: {x:385, y:335, lbl:\"Yes\",         t:\"leaf\", cls:\"si\"},\n  deb_lf:  {x:462, y:335, lbl:\"Yes\",         t:\"leaf\", cls:\"si\"},\n  fue_lf:  {x:635, y:335, lbl:\"No\",          t:\"leaf\", cls:\"no\"},\n};\n\nconst E = [\n  [\"root\",   \"nub_lf\",  \"Overcast\",186, 112],\n  [\"root\",   \"humedad\", \"Sunny\",   307, 108],\n  [\"root\",   \"viento\",  \"Rain\",    459, 108],\n  [\"humedad\",\"alta_lf\", \"High\",    221, 260],\n  [\"humedad\",\"norm_lf\", \"Normal\",  342, 260],\n  [\"viento\", \"deb_lf\",  \"Weak\",    497, 260],\n  [\"viento\", \"fue_lf\",  \"Strong\",  600, 260],\n];\n\n/* ── steps ─────────────────────────────────────────────── */\nconst STEPS = [\n  { badge:\"Step 1 of 9\", title:\"Initial Entropy — Root Node\",\n    desc:\"ID3 begins with all 15 examples at the root node. Initial entropy H(S) = 0.971 indicates impurity (9 'Yes', 6 'No'). In binary classification, H = 1 is maximum uncertainty and H = 0 represents a pure node.\",\n    vN:[\"root\"], vE:[], hl:\"root\",\n    panel:{t:\"ent\", lbl:\"Root Node (n = 15)\", si:9, no:6, H:0.971}},\n\n  { badge:\"Step 2 of 9\", title:\"Root Attribute Selection\",\n    desc:\"Gain(S, A) is computed across all 4 attributes. Outlook achieves the highest gain (0.280) because the Overcast subset is completely pure. Outlook is selected as the root node.\",\n    vN:[\"root\"], vE:[], hl:\"root\",\n    panel:{t:\"gains\", gains:[\n      {a:\"Outlook\",     g:0.280, best:true},\n      {a:\"Humidity\",    g:0.186},\n      {a:\"Wind\",        g:0.145},\n      {a:\"Temperature\", g:0.013}]}},\n\n  { badge:\"Step 3 of 9\", title:\"Splitting on Outlook — Three Branches\",\n    desc:\"The root splits into 3 subsets. Overcast (n = 4) has H = 0 (all 'Yes'), forming a pure leaf node. Sunny and Rain subsets remain impure and require further splitting.\",\n    vN:[\"root\",\"nub_lf\",\"humedad\",\"viento\"], vE:[0,1,2], hl:null,\n    panel:{t:\"sub\", subs:[\n      {lbl:\"Overcast (n = 4)\", si:4, no:0, H:0.000, pure:true},\n      {lbl:\"Sunny (n = 6)\",    si:2, no:4, H:0.918, pure:false},\n      {lbl:\"Rain (n = 5)\",     si:3, no:2, H:0.971, pure:false}]}},\n\n  { badge:\"Step 4 of 9\", title:\"Overcast Branch → Pure 'Yes' Leaf\",\n    desc:\"All 4 Overcast examples belong to class 'Yes'. H = 0 → pure node. Leaf created. Extracted rule: IF Outlook = Overcast → Play = Yes.\",\n    vN:[\"root\",\"nub_lf\",\"humedad\",\"viento\"], vE:[0,1,2], hl:\"nub_lf\",\n    panel:{t:\"ent\", lbl:\"Outlook = Overcast (n = 4)\", si:4, no:0, H:0.000}},\n\n  { badge:\"Step 5 of 9\", title:\"Sunny Branch → Selecting Next Attribute\",\n    desc:\"The 6 Sunny examples (2 Yes, 4 No) are impure (H = 0.918). Remaining features are evaluated. Humidity eliminates all impurity with gain 0.918 (the maximum possible). Humidity is selected.\",\n    vN:[\"root\",\"nub_lf\",\"humedad\",\"viento\"], vE:[0,1,2], hl:\"humedad\",\n    panel:{t:\"gains\", gains:[\n      {a:\"Humidity\",    g:0.918, best:true},\n      {a:\"Wind\",        g:0.294},\n      {a:\"Temperature\", g:0.170}]}},\n\n  { badge:\"Step 6 of 9\", title:\"Splitting Humidity on Sunny Branch\",\n    desc:\"Sunny + High → 4 examples, all 'No' (H = 0). Sunny + Normal → 2 examples, all 'Yes' (H = 0). Both subsets are pure leaf nodes. Rules: IF Sunny ∧ High → No; IF Sunny ∧ Normal → Yes.\",\n    vN:[\"root\",\"nub_lf\",\"humedad\",\"viento\",\"alta_lf\",\"norm_lf\"], vE:[0,1,2,3,4], hl:null,\n    panel:{t:\"sub\", subs:[\n      {lbl:\"Sunny + High (n = 4)\",   si:0, no:4, H:0.000, pure:true},\n      {lbl:\"Sunny + Normal (n = 2)\", si:2, no:0, H:0.000, pure:true}]}},\n\n  { badge:\"Step 7 of 9\", title:\"Rain Branch → Selecting Next Attribute\",\n    desc:\"The 5 Rain examples (3 Yes, 2 No) are impure (H = 0.971). Wind produces two pure subsets (gain = 0.971, maximum possible). Wind is selected.\",\n    vN:[\"root\",\"nub_lf\",\"humedad\",\"viento\",\"alta_lf\",\"norm_lf\"], vE:[0,1,2,3,4], hl:\"viento\",\n    panel:{t:\"gains\", gains:[\n      {a:\"Wind\",        g:0.971, best:true},\n      {a:\"Humidity\",    g:0.020},\n      {a:\"Temperature\", g:0.020}]}},\n\n  { badge:\"Step 8 of 9\", title:\"Splitting Wind on Rain Branch\",\n    desc:\"Rain + Weak → 3 examples, all 'Yes' (H = 0). Rain + Strong → 2 examples, all 'No' (H = 0). Both subsets pure: final leaf nodes created. Rules: IF Rain ∧ Weak → Yes; IF Rain ∧ Strong → No.\",\n    vN:[\"root\",\"nub_lf\",\"humedad\",\"viento\",\"alta_lf\",\"norm_lf\",\"deb_lf\",\"fue_lf\"],\n    vE:[0,1,2,3,4,5,6], hl:null,\n    panel:{t:\"sub\", subs:[\n      {lbl:\"Rain + Weak (n = 3)\",   si:3, no:0, H:0.000, pure:true},\n      {lbl:\"Rain + Strong (n = 2)\", si:0, no:2, H:0.000, pure:true}]}},\n\n  { badge:\"Step 9 of 9\", title:\"Complete Tree — 5 Classification Rules\",\n    desc:\"The ID3 tree is fully constructed. Depth 2, 5 leaves, 3 of 4 attributes used (Temperature was not selected). All leaf nodes are pure, achieving 100% training accuracy.\",\n    vN:[\"root\",\"nub_lf\",\"humedad\",\"viento\",\"alta_lf\",\"norm_lf\",\"deb_lf\",\"fue_lf\"],\n    vE:[0,1,2,3,4,5,6], hl:null,\n    panel:{t:\"rules\"}},\n];\n\n/* ── SVG helpers ────────────────────────────────────────── */\nconst svg = document.getElementById('id3-svg');\nconst NS  = \"http://www.w3.org/2000/svg\";\n\nfunction mk(tag, attrs, txt) {\n  const e = document.createElementNS(NS, tag);\n  for (const [k,v] of Object.entries(attrs)) e.setAttribute(k, v);\n  if (txt != null) e.textContent = txt;\n  return e;\n}\n\nfunction drawTree(step) {\n  svg.innerHTML = '';\n  const {vN, vE, hl} = step;\n\n  const defs = mk('defs', {});\n  const marker = mk('marker', {id:'arr', markerWidth:6, markerHeight:6,\n    refX:5, refY:3, orient:'auto'});\n  marker.appendChild(mk('path', {d:'M0,0 L0,6 L6,3 z', fill:'#99aabb'}));\n  defs.appendChild(marker);\n  svg.appendChild(defs);\n\n  E.forEach(([fid, tid, lbl, lx, ly], i) => {\n    if (!vE.includes(i)) return;\n    const f = N[fid], t = N[tid];\n\n    const dx = t.x - f.x, dy = t.y - f.y;\n    const len = Math.hypot(dx, dy);\n    const rf = (f.t === 'int') ? (fid === 'root' ? 33 : 28) : 0;\n    const rt = (t.t === 'int') ? 28 : 16;\n    const sx = f.x + dx/len*rf,  sy = f.y + dy/len*rf;\n    const ex = t.x - dx/len*rt,  ey = t.y - dy/len*rt;\n\n    svg.appendChild(mk('line', {\n      x1:sx, y1:sy, x2:ex, y2:ey,\n      stroke:'#8899bb', 'stroke-width':1.6,\n      'marker-end':'url(#arr)'\n    }));\n\n    svg.appendChild(mk('rect', {\n      x:lx-22, y:ly-9, width:44, height:16, rx:4,\n      fill:'white', stroke:'#ccd', 'stroke-width':0.8\n    }));\n    svg.appendChild(mk('text', {\n      x:lx, y:ly+4, 'text-anchor':'middle',\n      'font-size':'10', 'font-family':'Georgia,serif', fill:'#445'\n    }, lbl));\n  });\n\n  for (const [nid, node] of Object.entries(N)) {\n    if (!vN.includes(nid)) continue;\n    const isHL = (nid === hl);\n\n    if (node.t === 'int') {\n      const r = nid === 'root' ? 33 : 28;\n      svg.appendChild(mk('circle', {\n        cx:node.x, cy:node.y, r:r,\n        fill: isHL ? '#2a5285' : '#1a3a5c',\n        stroke: isHL ? '#f4a03a' : '#0c2040',\n        'stroke-width': isHL ? 3 : 1.5\n      }));\n      svg.appendChild(mk('text', {\n        x:node.x, y:node.y+5, 'text-anchor':'middle',\n        'font-size': nid==='root'?'12.5':'11.5',\n        'font-family':'Georgia,serif', 'font-weight':'bold', fill:'white'\n      }, node.lbl));\n\n    } else {\n      const w=52, h=30;\n      const fill = isHL\n        ? (node.cls==='si' ? '#1b5e20' : '#7f0000')\n        : (node.cls==='si' ? '#2d6a4f' : '#9d0208');\n      svg.appendChild(mk('rect', {\n        x:node.x-w/2, y:node.y-h/2, width:w, height:h, rx:7,\n        fill:fill, stroke: isHL?'#f4a03a':'rgba(0,0,0,0.18)',\n        'stroke-width': isHL?3:1\n      }));\n      svg.appendChild(mk('text', {\n        x:node.x, y:node.y+5, 'text-anchor':'middle',\n        'font-size':'14', 'font-family':'Georgia,serif',\n        'font-weight':'bold', fill:'white'\n      }, node.lbl));\n    }\n\n    if (isHL) {\n      const r2 = (node.t==='int') ? (nid==='root'?33:28) : 20;\n      const ring = mk('circle', {\n        cx:node.x, cy:node.y, r:r2+7,\n        fill:'none', stroke:'#f4a03a', 'stroke-width':1.5,\n        opacity:0.55\n      });\n      svg.appendChild(ring);\n    }\n  }\n}\n\n/* ── info panel ─────────────────────────────────────────── */\nfunction renderPanel(p) {\n  const div = document.getElementById('id3-panel');\n  if (p.t === 'ent') {\n    const tot = p.si + p.no;\n    div.innerHTML =\n      `<strong style=\"color:#1a3a5c;\">${p.lbl}</strong>\n       <div style=\"display:flex;gap:20px;margin-top:6px;align-items:center;flex-wrap:wrap;\">\n         <div>\n           <span style=\"background:#2d6a4f;color:#fff;padding:1px 9px;border-radius:3px;\">Yes: ${p.si}</span>\n           &nbsp;\n           <span style=\"background:#9d0208;color:#fff;padding:1px 9px;border-radius:3px;\">No: ${p.no}</span>\n           &nbsp; n = ${tot}\n         </div>\n         <div style=\"color:#333;\">\n           H = −<sup>${p.si}</sup>⁄<sub>${tot}</sub>·log₂(<sup>${p.si}</sup>⁄<sub>${tot}</sub>)\n           − <sup>${p.no}</sup>⁄<sub>${tot}</sub>·log₂(<sup>${p.no}</sup>⁄<sub>${tot}</sub>)\n           = <strong>${p.H.toFixed(3)}</strong>\n           ${p.H===0 ? '&nbsp;<span style=\"color:#2d6a4f;font-weight:bold;\">← pure node ✓</span>' : ''}\n         </div>\n         <div style=\"flex:1;max-width:160px;\">\n           <div style=\"height:8px;background:#e8ecf0;border-radius:4px;overflow:hidden;\">\n             <div style=\"height:100%;width:${p.H*100}%;background:linear-gradient(to right,#2d6a4f,#9d0208);border-radius:4px;\"></div>\n           </div>\n           <div style=\"font-size:0.77em;color:#999;margin-top:2px;\">Impurity: ${(p.H*100).toFixed(0)}%</div>\n         </div>\n       </div>`;\n  }\n  else if (p.t === 'gains') {\n    const mx = Math.max(...p.gains.map(g=>g.g));\n    div.innerHTML =\n      `<strong style=\"color:#1a3a5c;\">Gain(S, A) — Information Gain per Attribute</strong>\n       <table style=\"width:100%;margin-top:7px;border-collapse:collapse;font-size:0.85em;\">\n         <tr style=\"color:#666;border-bottom:1px solid #ddd;\">\n           <th style=\"text-align:left;padding:2px 8px;\">Attribute</th>\n           <th style=\"text-align:left;padding:2px 8px;\">Gain</th>\n           <th style=\"padding:2px 8px;min-width:110px;\"></th>\n           <th style=\"padding:2px 4px;\"></th>\n         </tr>\n         ${p.gains.map(g => `\n           <tr style=\"border-bottom:1px solid #eef;${g.best?'background:#f0f5ff;':''}\">\n             <td style=\"padding:4px 8px;font-weight:${g.best?'bold':'normal'};\">${g.a}</td>\n             <td style=\"padding:4px 8px;font-weight:${g.best?'bold':'normal'};\">${g.g.toFixed(3)}</td>\n             <td style=\"padding:4px 8px;\">\n               <div style=\"height:7px;background:#e0e8f0;border-radius:3px;overflow:hidden;\">\n                 <div style=\"height:100%;width:${g.g/mx*100}%;background:${g.best?'#1a3a5c':'#7ca3c0'};border-radius:3px;\"></div>\n               </div>\n             </td>\n             <td style=\"padding:4px 6px;color:#1a6f25;font-weight:bold;white-space:nowrap;\">${g.best?'← selected':''}</td>\n           </tr>`).join('')}\n       </table>`;\n  }\n  else if (p.t === 'sub') {\n    div.innerHTML =\n      `<strong style=\"color:#1a3a5c;\">Child Subsets Resulting from Split</strong>\n       <div style=\"display:flex;gap:9px;margin-top:8px;flex-wrap:wrap;\">\n         ${p.subs.map(s => `\n           <div style=\"flex:1;min-width:155px;border:1px solid ${s.pure?'#2d6a4f':'#bbc'};\n                       border-radius:5px;padding:7px 11px;background:${s.pure?'#f0faf4':'#fafafa'};\">\n             <div style=\"font-weight:bold;font-size:0.82em;color:#333;margin-bottom:4px;\">${s.lbl}</div>\n             <div style=\"font-size:0.81em;margin-bottom:3px;\">\n               <span style=\"background:#2d6a4f;color:#fff;padding:0 6px;border-radius:3px;\">Yes: ${s.si}</span>\n               <span style=\"background:#9d0208;color:#fff;padding:0 6px;border-radius:3px;margin-left:4px;\">No: ${s.no}</span>\n             </div>\n             <div style=\"font-size:0.81em;\">H = <strong>${s.H.toFixed(3)}</strong>\n               ${s.pure?'<span style=\"color:#2d6a4f;\"> ← pure ✓</span>':''}\n             </div>\n           </div>`).join('')}\n       </div>`;\n  }\n  else if (p.t === 'rules') {\n    div.innerHTML =\n      `<strong style=\"color:#1a3a5c;\">Extracted IF-THEN Classification Rules</strong>\n       <ol style=\"margin:6px 0 0;padding-left:18px;line-height:2;font-size:0.82em;\">\n         <li><code>IF Outlook = Overcast</code>\n             → <span style=\"background:#2d6a4f;color:#fff;padding:0 7px;border-radius:3px;\">Yes</span></li>\n         <li><code>IF Outlook = Sunny ∧ Humidity = High</code>\n             → <span style=\"background:#9d0208;color:#fff;padding:0 7px;border-radius:3px;\">No</span></li>\n         <li><code>IF Outlook = Sunny ∧ Humidity = Normal</code>\n             → <span style=\"background:#2d6a4f;color:#fff;padding:0 7px;border-radius:3px;\">Yes</span></li>\n         <li><code>IF Outlook = Rain ∧ Wind = Weak</code>\n             → <span style=\"background:#2d6a4f;color:#fff;padding:0 7px;border-radius:3px;\">Yes</span></li>\n         <li><code>IF Outlook = Rain ∧ Wind = Strong</code>\n             → <span style=\"background:#9d0208;color:#fff;padding:0 7px;border-radius:3px;\">No</span></li>\n       </ol>\n       <div style=\"margin-top:5px;font-size:0.78em;color:#888;\">\n         Training Accuracy: 15/15 = 100% &nbsp;·&nbsp; Temperature was unselected across all splits\n       </div>`;\n  }\n}\n\n/* ── controller ─────────────────────────────────────────── */\nlet cur = 0;\n\nfunction render() {\n  const s = STEPS[cur];\n  document.getElementById('id3-badge').textContent = s.badge;\n  document.getElementById('id3-desc').textContent  = s.desc;\n  document.getElementById('id3-ctr').textContent   = `${cur+1} / ${STEPS.length}`;\n  document.getElementById('id3-prev').disabled = (cur === 0);\n  document.getElementById('id3-next').disabled = (cur === STEPS.length-1);\n  drawTree(s);\n  renderPanel(s.panel);\n}\n\nwindow.id3Nav = function(d) {\n  cur = Math.max(0, Math.min(STEPS.length-1, cur+d));\n  render();\n};\n\nrender();\n})();\n</script>\n```\n\n## Extracting Classification Rules\n\nA primary benefit of decision trees is their direct conversion into classification rules. Each root-to-leaf path produces a single IF-THEN rule.\n\nFrom the tree above, we extract:\n\n1. IF `Outlook = Sunny` AND `Humidity = High`, THEN `Play = No`.\n2. IF `Outlook = Sunny` AND `Humidity = Normal`, THEN `Play = Yes`.\n3. IF `Outlook = Overcast`, THEN `Play = Yes`.\n4. IF `Outlook = Rain` AND `Wind = Weak`, THEN `Play = Yes`.\n5. IF `Outlook = Rain` AND `Wind = Strong`, THEN `Play = No`.\n\n::: {.callout-note appearance=\"minimal\"}\nDefinition. A classification rule extracted from a decision tree is a logical implication comprising conditions along a root-to-leaf path:\n$$\n\\text{IF } (A_1=v_1) \\land (A_2=v_2) \\land \\cdots \\land (A_k=v_k) \\text{ THEN } y=c.\n$$ {#eq-classification-rule}\n:::\n\nThese rules are intuitive and easy to communicate to non-technical domain experts. Consequently, decision trees are widely applied in medical diagnostics, credit scoring, predictive maintenance, and customer churn analysis [@breiman1984; @james2021].\n\n## Implementation with `scikit-learn`\n\nWhile the preceding examples computed entropy and information gain manually, production environments utilize optimized machine learning libraries. In Python, `scikit-learn` provides efficient decision tree implementations [@pedregosa2011].\n\nCategorical features are typically one-hot encoded before fitting a tree configured with `criterion=\"entropy\"`.\n\n::: {#10d54669 .cell execution_count=9}\n``` {.python .cell-code}\nfrom sklearn.compose import ColumnTransformer\nfrom sklearn.preprocessing import OneHotEncoder\nfrom sklearn.tree import DecisionTreeClassifier, plot_tree\nfrom sklearn.pipeline import Pipeline\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.metrics import accuracy_score, classification_report\n\nX = df.drop(columns=\"Play\")\ny = df[\"Play\"]\n\ncategorical_features = X.columns.tolist()\n\npreprocess = ColumnTransformer(\n    transformers=[\n        (\"cat\", OneHotEncoder(handle_unknown=\"ignore\"), categorical_features)\n    ]\n)\n\nmodel = DecisionTreeClassifier(\n    criterion=\"entropy\",\n    max_depth=3,\n    random_state=42\n)\n\nclf = Pipeline(steps=[\n    (\"preprocess\", preprocess),\n    (\"model\", model)\n])\n\nclf.fit(X, y)\nclf.predict(X)\n```\n\n::: {.cell-output .cell-output-display execution_count=9}\n```\narray(['No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes',\n       'Yes', 'Yes', 'Yes', 'No', 'No'], dtype=object)\n```\n:::\n:::\n\n\nOn small datasets, evaluating performance on training data serves only as a technical sanity check. Real-world validation requires held-out test sets or cross-validation.\n\n::: {#92048a40 .cell execution_count=10}\n``` {.python .cell-code}\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y,\n    test_size=0.30,\n    random_state=42,\n    stratify=y\n)\n\nclf.fit(X_train, y_train)\ny_pred = clf.predict(X_test)\n\nprint(\"Accuracy:\", accuracy_score(y_test, y_pred))\nprint(classification_report(y_test, y_pred))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAccuracy: 0.6\n              precision    recall  f1-score   support\n\n          No       0.50      1.00      0.67         2\n         Yes       1.00      0.33      0.50         3\n\n    accuracy                           0.60         5\n   macro avg       0.75      0.67      0.58         5\nweighted avg       0.80      0.60      0.57         5\n\n```\n:::\n:::\n\n\n## Tree Visualization\n\n::: {#ac716fbc .cell execution_count=11}\n``` {.python .cell-code}\nimport matplotlib.pyplot as plt\n\nclf.fit(X, y)\n\nfeature_names = clf.named_steps[\"preprocess\"].get_feature_names_out()\ntree_model = clf.named_steps[\"model\"]\n\nplt.figure(figsize=(14, 7))\nplot_tree(\n    tree_model,\n    feature_names=feature_names,\n    class_names=tree_model.classes_,\n    filled=True,\n    rounded=True\n)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](6-1-clasificacion_arboles_files/figure-html/cell-12-output-1.png){width=1061 height=537}\n:::\n:::\n\n\nVisualizing trees allows inspecting feature usage and split points. On larger trees, visual diagrams can become unwieldy; hyperparameters such as `max_depth`, `min_samples_split`, and `min_samples_leaf` should be tuned to maintain model interpretability and prevent overfitting.\n\n## Computational Complexity\n\nThe computational complexity of tree building depends on the number of records $n$, number of attributes $m$, number of classes, and split evaluation costs. For categorical features, a simplified per-node split evaluation cost is $O(mn)$.\n\nSumming across tree levels, a balanced tree of depth $d$ processes roughly $n$ examples per level, yielding a total induction complexity estimate of:\n\n$$\nO(mn d),\n$$\n\nwhere $d$ is tree depth. In the worst case, depth can reach $n$, incurring higher costs and producing non-generalizable unpruned trees. Continuous features require sorting or threshold scanning, modifying training complexity [@hastie2009; @pedregosa2011].\n\n::: {.callout-note appearance=\"minimal\"}\nDefinition. For $n$ examples, $m$ attributes, and tree depth $d$, a simplified computational complexity estimate for categorical tree induction is:\n$$\nT(n,m,d) = O(mnd).\n$$ {#eq-tree-complexity}\n:::\n\nInference with a trained tree is highly efficient: classifying a new record requires traversing a single path from root to leaf, taking $O(d)$ time.\n\n## Pros and Cons\n\nDecision trees offer several major advantages:\n\n- Intuitive interpretability;\n- Direct extraction of human-readable rules;\n- Seamless handling of both numerical and categorical variables;\n- Minimal feature scaling requirements;\n- Natural capture of non-linear feature interactions.\n\nHowever, they also carry key limitations:\n\n- High risk of overfitting if grown unconstrained;\n- Instability and sensitivity to small training data fluctuations;\n- ID3 bias toward attributes with many distinct categories;\n- Standard ID3 lacks native handling of continuous numerical features;\n- Greedy local optimization does not guarantee a globally optimal tree.\n\nThe greedy nature of ID3 means it selects locally optimal splits at each node without backtracking. While computationally efficient, this does not guarantee globally optimal trees. In practice, techniques like pruning, cross-validation, and ensemble methods (Random Forests, Gradient Boosting) substantially improve generalization performance [@breiman1984; @hastie2009].\n\n## Conclusions\n\nSupervised classification aims to assign categorical labels to new instances based on historical observations. Decision trees offer an intuitive, interpretable framework for solving classification tasks through sequential feature tests.\n\nHunt's algorithm provides the general recursive blueprint for tree construction. ID3 specifies a split selection criterion grounded in entropy and Information Gain. Entropy measures class impurity, while Information Gain quantifies impurity reduction following a split.\n\nThe baseball example illustrated how initial entropy is computed, candidate features are evaluated, root nodes selected, and branches recursively grown until pure leaves are reached. Converting trained trees into IF-THEN rules bridges the gap between quantitative predictive modeling and human explainability.\n\nIn real-world machine learning pipelines, decision trees require careful hyperparameter tuning and regularization to avoid overfitting. Nevertheless, they remain a foundational model family in data science due to their unique balance of simplicity, transparency, and competitive predictive capability.\n\n## References {.unnumbered}\n\n::: {#refs}\n:::\n\n",
    "supporting": [
      "6-1-clasificacion_arboles_files/figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}