project:
  type: book
  output-dir: docs
  resources:
    - lectures/          # ← único cambio: copia lectures/ a docs/lectures/

book:
  title: "Almacenes y Minería de Datos"
  author: "Diego Villaba"
  search: true
  repo-url: https://github.com/DiegoViillalba/almacenamienes-y-mineria-de-datos
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  language: es
  sidebar:
    style: "floating"
    collapse-toggle: true
  
  chapters:
    - index.qmd
    - part: "Almacennes de datos"
      contents:
        - unidades/almacenes/1-1-introduccion.qmd
        - unidades/almacenes/1-2-modelo-multidim.qmd
    - part: "Introducción a la Minería de Datos"
      contents:
        - unidades/intro_mineria/2-1-introduccion.qmd
    - part: "Análisis Exploratorio de Datos"
      contents:
        - unidades/intro_mineria/2-2-eda_exploratorio.qmd
        - section: "Ejemplos EDA"
          contents:
            - unidades/intro_mineria/2-10-CRISP_DM_bigmart.qmd
            - unidades/intro_mineria/2-3-example_localizacion_bigmart.qmd
            - unidades/intro_mineria/2-4-variabilidad_bigmart.qmd
            - unidades/intro_mineria/2-5-forma_bigmart.qmd
            - unidades/intro_mineria/2-6-heterogeneidad_bigmart.qmd
            - unidades/intro_mineria/2-7-concentracion_bigmart.qmd
            - unidades/intro_mineria/2-9-correlacion_bigmart.qmd
        - unidades/intro_mineria/multivariado/2-11-analisis-multivariado.qmd
    - part: "Preprocesamiento y Patrones Frecuentes"
      contents:
        - unidades/preprocesamiento/4-1-introduccion.qmd
        - unidades/preprocesamiento/4-2-datos-faltantes.qmd
  appendices:
    - presentaciones.qmd


format:
  html:
    css: visionbook.css
    anchor-sections: true
    fontsize: "16px"
    linestretch: 1.6
    mainfont: "Palatino"
    monofont: "Fira Mono"
    smooth-scroll: true
    toc-depth: 3
    # code stuff
    code-link: true
    code-fold: false
    code-tools: false
    highlight-style: printing
    code-block-bg: true
    code-overflow: wrap
    # css: ./scripts/custom-style.css
    theme:
      light: cosmo
      dark: darkly
    fig-align: "center"
    reference-location: margin
    cap-location: margin
    mathjax: true
    lightbox: true
    crossref:
      custom:
        - key: alg
          kind: float
          reference-prefix: Algorithm
    grid:
      gutter-width: 2em

    # include-before-body: sectionstat.js
    # include-in-header: sectionstat.html
    other-links:
      - text: Contáctame
        href: mailto:diego.villalba@ciencias.unam.mx
        icon: envelope

bibliography: references.bib