project:
  type: book
  output-dir: docs
  resources:
    - lectures/          # ← único cambio: copia lectures/ a docs/lectures/
    - google5c21f1e0999649d3.html

book:
  title: "Almacenes y Minería de Datos"
  author: "Diego Villaba"
  search: true
  repo-url: https://github.com/DiegoViillalba/almacenamienes-y-mineria-de-datos
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  language: es
  sidebar:
    style: "floating"
    collapse-toggle: true
  
  chapters:
    - index.qmd
    - part: "Almacennes de datos"
      contents:
        - unidades/almacenes/1-1-introduccion.qmd
        - unidades/almacenes/1-2-modelo-multidim.qmd
    - part: "Introducción a la Minería de Datos"
      contents:
        - unidades/intro_mineria/2-1-introduccion.qmd
    - part: "Análisis Exploratorio de Datos"
      contents:
        - unidades/intro_mineria/2-2-eda_exploratorio.qmd
        - section: "Ejemplos EDA"
          contents:
            - unidades/intro_mineria/2-10-CRISP_DM_bigmart.qmd
            - unidades/intro_mineria/2-3-example_localizacion_bigmart.qmd
            - unidades/intro_mineria/2-4-variabilidad_bigmart.qmd
            - unidades/intro_mineria/2-5-forma_bigmart.qmd
            - unidades/intro_mineria/2-6-heterogeneidad_bigmart.qmd
            - unidades/intro_mineria/2-7-concentracion_bigmart.qmd
            - unidades/intro_mineria/2-9-correlacion_bigmart.qmd
        - unidades/intro_mineria/multivariado/2-11-analisis-multivariado.qmd
        - unidades/intro_mineria/multivariado/2-12-analisis-multivariado-examples.qmd
    - part: "Preprocesamiento de Datos"
      contents:
        - unidades/preprocesamiento/4-1-introduccion.qmd
        - section: "Integración de Datos"
          contents:
            - unidades/preprocesamiento/4-3-conversion.qmd
        - section: "Limpieza de Datos"
          contents:
            - unidades/preprocesamiento/4-6-ruido.qmd
            - unidades/preprocesamiento/4-2-datos-faltantes.qmd
        - section: "Reducción de datos"
          contents:
            - unidades/preprocesamiento/4-4-PCA.qmd
            - unidades/preprocesamiento/4-5-chi2.qmd
    - part: "Reglas de Asociación"
      contents:
        - unidades/reglas_asociacion/5-1-introduccion.qmd
        - unidades/reglas_asociacion/5-2-metricas-extra.qmd
        - unidades/reglas_asociacion/5-3-fp_growth.qmd
    - part: "Clasficadores"
      contents:
        - unidades/clasificadores/6-1-clasificacion_arboles.qmd
        - unidades/clasificadores/6-1-clasificacion_cart.qmd
        - unidades/clasificadores/6-2-metricas_clasificacion.qmd
        - unidades/clasificadores/6-3-ejercicio.qmd


  appendices:
    - presentaciones.qmd


format:
  html:
    css: visionbook.css
    anchor-sections: true
    fontsize: "16px"
    linestretch: 1.6
    mainfont: "Palatino"
    monofont: "Fira Mono"
    smooth-scroll: true
    toc-depth: 3
    include-in-header:
      text: |
        <!-- Google Tag Manager -->
        <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-NQJGJRC5');</script>
        <!-- End Google Tag Manager -->
    include-after-body:
      text: |
        <!-- Google Tag Manager (noscript) -->
        <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NQJGJRC5"
        height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
        <!-- End Google Tag Manager (noscript) -->
    # code stuff
    code-link: true
    code-fold: false
    code-tools: false
    highlight-style: printing
    code-block-bg: true
    code-overflow: wrap
    # css: ./scripts/custom-style.css
    theme:
      light: cosmo
      dark: darkly
    fig-align: "center"
    reference-location: margin
    cap-location: margin
    mathjax: true
    lightbox: true
    crossref:
      custom:
        - key: alg
          kind: float
          reference-prefix: Algorithm
    grid:
      gutter-width: 2em

    # include-before-body: sectionstat.js
    # include-in-header: sectionstat.html
    other-links:
      - text: Contáctame
        href: mailto:diego.villalba@ciencias.unam.mx
        icon: envelope

bibliography: references.bib