project:
  type: book
  output-dir: docs

book:
  title: "Almacenes y Minería de Datos"
  author: "Tu Nombre"
  language: es
  sidebar:
    style: "floating"
  
  chapters:
    - index.qmd
    - part: "Almacennes de datos"
      chapters:
        - unidades/almacenes/1-1-introduccion.qmd
        - unidades/almacenes/1-2-modelo-multidim.qmd
    - part: "Pre-procesamiento de datos"
    #   chapters:
    #     - unidades/02-preprocesamiento.qmd
    #     - unidades/04-patrones-frecuentes.qmd
    # - part: "Modelado Predictivo"
    #   chapters:
    #     - unidades/05-clasificacion.qmd
    #     - unidades/06-agrupamiento.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-summary: "Ver código"
    number-sections: true

bibliography: references.bib