{
  "hash": "3ef727af3dfce0e6f39fc25bdaad3ea4",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Introducción al Preprocesamiento de Datos y Calidad de Datos\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    toc-title: \"Contenido\"\n    code-fold: true\n    code-tools: true\n    theme: cosmo\n    highlight-style: github\nexecute:\n  echo: true\n  warning: false\n  message: false\njupyter: python3\n---\n\n# Introducción al Preprocesamiento de Datos y Calidad de Datos\n\nEn la disciplina de la ciencia de datos y la ingeniería de *machine learning*, el modelado algorítmico (entrenamiento de redes neuronales, ensambles de árboles, etc.) suele acaparar la mayor parte de la atención mediática, académica y de los recién llegados al campo. Sin embargo, en el mundo real e industrial, los profesionales y equipos de datos invierten abrumadoramente entre el 70% y el 80% de su tiempo, esfuerzo y presupuesto en tareas de recolección, limpieza, integración, transformación y validación de datos. \n\nEsta etapa fundamental, densa y en ocasiones tediosa, se conoce formalmente como **Preprocesamiento de Datos**. Sin ella, ningún sistema de IA es viable en producción.\n\n## 1. La Intuición: \"Garbage In, Garbage Out\"\n\nEl principio empírico más antiguo, persistente y vigente de las ciencias de la computación dicta: *\"Garbage In, Garbage Out\"* (Basura entra, basura sale). Un modelo predictivo, sin importar cuán sofisticado sea teóricamente (desde una sencilla regresión lineal OLS hasta un *Large Language Model* con cientos de billones de parámetros), es en el fondo un estimador y optimizador matemático que opera sobre matrices numéricas y tensores. \n\nComo tal, la formulación matemática subyacente requiere, por definición de sus axiomas de diseño, que las entradas ($\\mathcal{X}$) pertenezcan a espacios vectoriales bien definidos, posean valores numéricos válidos en el campo de los reales ($\\mathbb{R}$), presenten distribuciones probabilísticas manejables o estables, y estén libres de ruidos destructivos o inconsistencias estructurales.\n\n### El Caso Práctico: El Desastre Cotidiano (BigMart Sales)\n\nImaginemos un escenario extremadamente habitual utilizando nuestro marco conductor del dataset **BigMart Sales**. Extraemos una pequeña muestra de datos operacionales de los productos en diversas tiendas. Debido a errores humanos, migraciones de bases de datos heredadas o fallas de software en las interfaces de captura, el *DataFrame* crudo podría tener el siguiente aspecto:\n\n| Item_Identifier | Item_Weight | Item_MRP | Outlet_Establishment_Year | Item_Fat_Content |\n|:---:|:---:|:---:|:---:|:---:|\n| FDA15 | 9.30 | 249.80 | 1999 | Low Fat |\n| DRC01 | -5.00 | 0.00 | 09-Jan-2009 | low fat |\n| FDN15 | NaN | 1200000.0 | 1998 | LF |\n| FDX07 | 19.20 | NaN | 14/02/1998 | Regular |\n| NCD19 | 200.00 | 53.86 | 1985-01-20 | reg |\n\nAnalicemos detenidamente, desde un prisma algorítmico, los problemas estructurales que colapsarían inmediatamente cualquier motor de Machine Learning si intentáramos alimentar esta matriz tabular directamente, sin un pipeline de curación intermedio:\n\n1. **Valores Física y Lógicamente Imposibles**: Encontramos pesos negativos (`-5.00`) o biológicamente irreales para un producto de supermercado (`200.00` kg). Un árbol de decisión creará divisiones (*splits*) en nodos absurdos, y un modelo lineal intentará usar esos coeficientes de manera desastrosa.\n2. **Formatos Inconsistentes y Polimórficos**: Los años de establecimiento coexisten en una plétora de formatos de cadena de texto incompatibles (`YYYY`, `DD-Mon-YYYY`, `DD/MM/YYYY`). Para el motor matemático, no tienen valor temporal ni jerarquía secuencial; son sólo tokens léxicos heterogéneos.\n3. **Categorías Sucias y Duplicadas Semánticamente**: Entradas como \"Low Fat\", \"low fat\", y \"LF\" representan exactamente la misma clase abstracta desde el punto de vista del dominio de negocio, al igual que \"Regular\" y \"reg\". Sin embargo, para un modelo que codifique estas representaciones (por ejemplo, mediante una matriz dispersa con *One-Hot Encoding*), cada una de estas variaciones léxicas mínimas será tratada algorítmicamente como una categoría ortogonal independiente, inflando artificialmente la dimensionalidad del espacio (maldición de la dimensionalidad) y destruyendo la señal estadística al diluir la frecuencia de las muestras en las clases correctas.\n4. **Valores Atípicos Extremos (*Outliers* Estructurales)**: Un precio MRP de `1,200,000` (posiblemente un error de tipado con ceros extra, o un dato atípico) comparado con una media poblacional normal puede sesgar dramática e irremediablemente las funciones empíricas de costo basadas en errores cuadráticos (como el MSE). Esto fuerza iterativamente a los gradientes en el descenso estocástico a explotar (*exploding gradients*), o fuerza a que los coeficientes de los hiperplanos se hiper-ajusten para acomodar e \"intentar explicar\" un único punto anómalo, descuidando el 99% restante de la distribución general (pérdida masiva de generalización).\n5. **Valores Ausentes o Vacíos (*Missing Values / NaN*)**: En el espacio informático y en punto flotante (IEEE 754), `NaN` (Not a Number) es un estado especial. La inmensa mayoría de las implementaciones algebraicas matriciales devolverán y propagarán infinitamente `NaN` si un solo elemento de la operación cruzada es `NaN`.\n\nSi pasamos este dataset directamente a un motor estadístico de regresión, el sistema simplemente se estrellará lanzando una excepción de tipo (*Type Error / Value Error*).\n\n## 2. Desarrollo Manual Paso a Paso: Abriendo la Caja Negra\n\nPara desmitificar lo que hacen las librerías de software bajo su moderna y opaca abstracción, vamos a tomar un micro-dataset reducido y aplicaremos las transformaciones lógicas y aritméticas requeridas estrictamente a mano, paso a paso.\n\nConsideremos esta matriz inicial $\\mathbf{X}_{\\text{crudo}}$ compuesta por solo 3 registros (instancias $x^{(i)}$) y 2 características:\n\n| Observación ($x^{(i)}$) | Item_Weight (Variable Numérica) | Item_Fat_Content (Variable Textual Categórica) |\n|---|---|---|\n| $x^{(1)}$ | 10.0 | \"Low Fat\" |\n| $x^{(2)}$ | NaN | \"LF\" |\n| $x^{(3)}$ | 20.0 | \"Regular\" |\n\nNuestro objetivo cardinal es transformar esta tabla heterogénea en un espacio numérico denso estructurado $\\mathbb{R}^{3 \\times 3}$.\n\n### Paso 2.1: Estandarización Textual (Corrección, Mapeo y Normalización)\n\nLo primero que debe afrontarse es unificar las diversas representaciones semánticas existentes en el vector categórico `Item_Fat_Content`. Definimos matemáticamente una función discreta de mapeo categórico $f_{\\text{map}}(x)$:\n\n$$\nf_{\\text{map}}(x) = \n\\begin{cases} \n\\text{\"Low Fat\"} & \\text{si } x \\in \\{\\text{\"Low Fat\"}, \\text{\"low fat\"}, \\text{\"LF\"}\\} \\\\\n\\text{\"Regular\"} & \\text{si } x \\in \\{\\text{\"Regular\"}, \\text{\"reg\"}\\} \\\\\n\\end{cases}\n$$\n\nAplicando iterativamente el operador $f_{\\text{map}}$:\n- $x^{(1)}_{\\text{Fat}} = \\text{\"Low Fat\"} \\longrightarrow \\text{\"Low Fat\"}$\n- $x^{(2)}_{\\text{Fat}} = \\text{\"LF\"} \\longrightarrow \\text{\"Low Fat\"}$\n- $x^{(3)}_{\\text{Fat}} = \\text{\"Regular\"} \\longrightarrow \\text{\"Regular\"}$\n\n### Paso 2.2: Imputación Manual de Valores Ausentes\n\nAl observar nuestra matriz actualizada, encontramos que el valor correspondiente a $x^{(2)}_{\\text{Weight}}$ sigue siendo computacionalmente inmanejable: `NaN`. Imputamos utilizando el estimador de tendencia central ($\\mu$) sobre el soporte de valores presentes:\n\n$$ \\mu_{\\text{Weight}} = \\frac{1}{N_{\\text{validos}}} \\sum_{i \\in \\text{validos}} \\text{Weight}_{i} = \\frac{10.0 + 20.0}{2} = 15.0 $$\n\nSustituimos entonces operativamente el valor ausente: $x^{(2)}_{\\text{Weight}} \\leftarrow 15.0$.\n\n### Paso 2.3: Codificación de Variables Categóricas (Vectorización / Discretización)\n\nDado que las matemáticas operan en $\\mathbb{R}^n$, mapeamos a sub-vectores binarios ortogonales mediante *One-Hot Encoding*. En nuestro caso, el vocabulario semántico finito es $V = \\{\\text{\"Low Fat\"}, \\text{\"Regular\"}\\}$.\n\nProyectamos dimensionalmente creando dos columnas booleanas numéricas: `Fat_Low` y `Fat_Reg`.\n- Codificación para $\\text{\"Low Fat\"} \\rightarrow [1, 0]$\n- Codificación para $\\text{\"Regular\"} \\rightarrow [0, 1]$\n\nNuestra matriz tabular intermedia evoluciona así:\n\n| Weight_imputada | Fat_Low | Fat_Reg |\n|---|---|---|\n| 10.0 | 1 | 0 |\n| 15.0 | 1 | 0 |\n| 20.0 | 0 | 1 |\n\n### Paso 2.4: Escalado Numérico de Características (*Feature Standardization*)\n\nPara que un algoritmo converja isométricamente, debemos estandarizar numéricamente las columnas continuas (Z-score normalisation):\n\n$$ z_i = \\frac{x_i - \\mu}{\\sigma} $$\n\nCalculamos rigurosamente la media empírica ($\\mu$) y la desviación estándar poblacional ($\\sigma$) del vector `Weight_imputada`:\n- $\\mu = \\frac{10.0 + 15.0 + 20.0}{3} = 15.0$\n- $\\sigma = \\sqrt{\\frac{(10.0-15.0)^2 + (15.0-15.0)^2 + (20.0-15.0)^2}{3}} = \\sqrt{\\frac{(-5)^2 + 0 + 5^2}{3}} \\approx 4.08248$\n\nAplicando uniformemente la normalización $z$:\n- $z^{(1)} = \\frac{10.0 - 15.0}{4.082} \\approx -1.2247$\n- $z^{(2)} = \\frac{15.0 - 15.0}{4.082} = 0.0000$\n- $z^{(3)} = \\frac{20.0 - 15.0}{4.082} \\approx 1.2247$\n\n### Resultado Final y Conclusión del Flujo Manual\n\nNuestra matriz final resultante:\n\n$$\n\\mathbf{X}_{\\text{modelo}} =\n\\begin{bmatrix}\n-1.2247 & 1 & 0 \\\\\n 0.0000 & 1 & 0 \\\\\n 1.2247 & 0 & 1\n\\end{bmatrix}\n$$\n\n## Laboratorio Interactivo: Simulador de Pipeline y Fuga de Datos (BigMart)\n\nA continuación, experimenta interactivamente con el impacto del Data Leakage y los pasos del pipeline de preprocesamiento sobre una muestra simplificada de datos.\n\n::: {.content-visible when-format=\"html\"}\n```{=html}\n<div class=\"interactive-lab\" style=\"border: 1px solid #e0e0e0; border-radius: 8px; padding: 20px; background: #fafafa; margin: 20px 0; font-family: sans-serif;\">\n  <h3 style=\"margin-top: 0;\">Simulador de Pipeline y Fuga de Datos (BigMart)</h3>\n  \n  <div style=\"display: flex; gap: 20px; flex-wrap: wrap;\">\n    <div style=\"flex: 1; min-width: 250px;\">\n      <h4>Controles del Pipeline</h4>\n      <label style=\"display: block; margin-bottom: 8px;\">\n        <input type=\"checkbox\" id=\"chkCleanFat\" onchange=\"updatePipeline()\"> 1. Limpieza de `Item_Fat_Content` ('LF' -> 'Low Fat')\n      </label>\n      <label style=\"display: block; margin-bottom: 8px;\">\n        <input type=\"checkbox\" id=\"chkImputeWeight\" onchange=\"updatePipeline()\"> 2. Imputación de `Item_Weight` (Media)\n      </label>\n      <label style=\"display: block; margin-bottom: 8px;\">\n        <input type=\"checkbox\" id=\"chkScaleMRP\" onchange=\"updatePipeline()\"> 3. Escalado de `Item_MRP` (Z-Score)\n      </label>\n      <label style=\"display: block; margin-bottom: 8px;\">\n        <input type=\"checkbox\" id=\"chkOHE\" onchange=\"updatePipeline()\"> 4. One-Hot Encoding de `Outlet_Type`\n      </label>\n      \n      <hr style=\"margin: 15px 0; border: 0; border-top: 1px solid #ccc;\">\n      <h4>Modo de Ajuste (Fit)</h4>\n      <label style=\"display: block; margin-bottom: 8px; color: #2e7d32; font-weight: bold;\">\n        <input type=\"radio\" name=\"fitMode\" value=\"train\" checked onchange=\"updatePipeline()\"> Ajustar en Train (Correcto)\n      </label>\n      <label style=\"display: block; margin-bottom: 8px; color: #c62828; font-weight: bold;\">\n        <input type=\"radio\" name=\"fitMode\" value=\"leak\" onchange=\"updatePipeline()\"> Ajustar en Train+Test (Data Leakage!)\n      </label>\n    </div>\n    \n    <div style=\"flex: 2; min-width: 300px;\">\n      <h4>Datos Resultantes en Tiempo Real</h4>\n      <div style=\"background: #fff; border: 1px solid #ddd; padding: 10px; border-radius: 4px; overflow-x: auto;\">\n        <table id=\"pipelineTable\" style=\"width: 100%; border-collapse: collapse; text-align: right;\">\n          <thead>\n            <tr style=\"border-bottom: 2px solid #ccc;\">\n              <th style=\"padding: 5px; text-align: left;\">Set</th>\n              <th style=\"padding: 5px;\">Item_Weight</th>\n              <th style=\"padding: 5px;\">Item_Fat_Content</th>\n              <th style=\"padding: 5px;\">Item_MRP</th>\n              <th style=\"padding: 5px;\">Outlet_Type</th>\n            </tr>\n          </thead>\n          <tbody id=\"pipelineTbody\">\n          </tbody>\n        </table>\n      </div>\n      <div id=\"leakWarning\" style=\"margin-top: 15px; padding: 10px; background: #ffebee; color: #c62828; border-left: 4px solid #c62828; display: none;\">\n        <strong>¡Advertencia de Data Leakage!</strong> Estás calculando la media poblacional usando información del Test Set. La media verdadera del Train era <span id=\"trueMean\"></span>, pero ahora usas <span id=\"leakedMean\"></span>. ¡Tu modelo creerá erróneamente que conoce la distribución del futuro!\n      </div>\n    </div>\n  </div>\n</div>\n\n<script>\n  // Datos iniciales simulados\n  const rawData = [\n    { set: 'Train', weight: 10.0, fat: 'Low Fat', mrp: 150.0, outlet: 'Supermarket' },\n    { set: 'Train', weight: 20.0, fat: 'LF', mrp: 200.0, outlet: 'Grocery' },\n    { set: 'Train', weight: null, fat: 'reg', mrp: 100.0, outlet: 'Supermarket' },\n    { set: 'Test', weight: 40.0, fat: 'Regular', mrp: 250.0, outlet: 'Supermarket' } // Outlier en Test\n  ];\n\n  function updatePipeline() {\n    const chkCleanFat = document.getElementById('chkCleanFat').checked;\n    const chkImputeWeight = document.getElementById('chkImputeWeight').checked;\n    const chkScaleMRP = document.getElementById('chkScaleMRP').checked;\n    const chkOHE = document.getElementById('chkOHE').checked;\n    const fitMode = document.querySelector('input[name=\"fitMode\"]:checked').value;\n    \n    let processedData = JSON.parse(JSON.stringify(rawData));\n    \n    // 1. Limpieza Fat\n    if (chkCleanFat) {\n      processedData.forEach(d => {\n        if (d.fat === 'LF' || d.fat === 'low fat') d.fat = 'Low Fat';\n        if (d.fat === 'reg') d.fat = 'Regular';\n      });\n    }\n    \n    // Cálculos de ajuste (Fit)\n    let fitData = fitMode === 'train' ? processedData.filter(d => d.set === 'Train') : processedData;\n    \n    // Parámetros Weight\n    let validWeights = fitData.filter(d => d.weight !== null).map(d => d.weight);\n    let meanWeight = validWeights.reduce((a, b) => a + b, 0) / validWeights.length;\n    let trueTrainMean = processedData.filter(d => d.set === 'Train' && d.weight !== null).map(d => d.weight).reduce((a, b) => a + b, 0) / 2;\n    \n    // Parámetros MRP\n    let validMRPs = fitData.map(d => d.mrp);\n    let meanMRP = validMRPs.reduce((a, b) => a + b, 0) / validMRPs.length;\n    let stdMRP = Math.sqrt(validMRPs.map(x => Math.pow(x - meanMRP, 2)).reduce((a, b) => a + b, 0) / validMRPs.length);\n    \n    // Warning UI\n    const leakWarning = document.getElementById('leakWarning');\n    if (fitMode === 'leak' && chkImputeWeight) {\n      leakWarning.style.display = 'block';\n      document.getElementById('trueMean').innerText = trueTrainMean.toFixed(2);\n      document.getElementById('leakedMean').innerText = meanWeight.toFixed(2);\n    } else {\n      leakWarning.style.display = 'none';\n    }\n    \n    // 2. Imputar Weight\n    if (chkImputeWeight) {\n      processedData.forEach(d => {\n        if (d.weight === null) d.weight = meanWeight;\n      });\n    }\n    \n    // 3. Escalar MRP\n    if (chkScaleMRP) {\n      processedData.forEach(d => {\n        d.mrp = (d.mrp - meanMRP) / stdMRP;\n      });\n    }\n    \n    // Renderizado HTML\n    let theadHtml = `\n      <tr style=\"border-bottom: 2px solid #ccc;\">\n        <th style=\"padding: 5px; text-align: left;\">Set</th>\n        <th style=\"padding: 5px;\">Item_Weight</th>\n        <th style=\"padding: 5px;\">Item_Fat_Content</th>\n        <th style=\"padding: 5px;\">Item_MRP</th>`;\n    \n    if (chkOHE) {\n      theadHtml += `<th style=\"padding: 5px;\">Outlet_Supermarket</th><th style=\"padding: 5px;\">Outlet_Grocery</th>`;\n    } else {\n      theadHtml += `<th style=\"padding: 5px;\">Outlet_Type</th>`;\n    }\n    theadHtml += `</tr>`;\n    document.querySelector('#pipelineTable thead').innerHTML = theadHtml;\n    \n    let tbodyHtml = '';\n    processedData.forEach(d => {\n      let weightStr = d.weight === null ? '<span style=\"color:red\">NaN</span>' : d.weight.toFixed(2);\n      let mrpStr = chkScaleMRP ? d.mrp.toFixed(4) : d.mrp.toFixed(2);\n      let rowStyle = d.set === 'Test' ? 'background: #f0f8ff;' : '';\n      \n      tbodyHtml += `<tr style=\"border-bottom: 1px solid #eee; ${rowStyle}\">\n        <td style=\"padding: 5px; text-align: left;\"><strong>${d.set}</strong></td>\n        <td style=\"padding: 5px;\">${weightStr}</td>\n        <td style=\"padding: 5px;\">${d.fat}</td>\n        <td style=\"padding: 5px;\">${mrpStr}</td>`;\n        \n      if (chkOHE) {\n        let isSuper = d.outlet === 'Supermarket' ? 1 : 0;\n        let isGroC = d.outlet === 'Grocery' ? 1 : 0;\n        tbodyHtml += `<td style=\"padding: 5px;\">${isSuper}</td><td style=\"padding: 5px;\">${isGroC}</td>`;\n      } else {\n        tbodyHtml += `<td style=\"padding: 5px;\">${d.outlet}</td>`;\n      }\n      tbodyHtml += `</tr>`;\n    });\n    \n    document.getElementById('pipelineTbody').innerHTML = tbodyHtml;\n  }\n  \n  // Init\n  updatePipeline();\n</script>\n```\n:::\n::: {.content-visible when-format=\"pdf\"}\n*(Nota: Este laboratorio interactivo con controles dinámicos está disponible en la versión web del libro).*\n:::\n\n## 3. Formalización Teórica y Analítica\n\n### 3.1. Las 6 Dimensiones Fundamentales de la Calidad de Datos\n\nDe acuerdo a organismos internacionales rectores y estándares metodológicos y normativos industriales globales como ISO/IEC 25012 y el exhaustivo marco conceptual DAMA-DMBOK, la \"calidad de los datos\" no puede evaluarse como un atributo escalar abstracto, dicotómico o monolítico. La calidad se perfila, diagnostica y mide en un prisma de seis dimensiones ortogonales e interrelacionadas:\n\n1. **Completitud (*Completeness*)**: Proporción probabilística de los elementos de datos obligatorios o esperados que, de hecho, se encuentran presentes o poblados (no nulos) respecto a la cardinalidad total de datos registrados en el esquema objetivo.\n   $$ C = 1 - \\frac{\\sum_{i=1}^{N} \\mathbb{I}(x_i \\text{ es un objeto nulo})}{N} $$\n   Donde $\\mathbb{I}$ es la conocida función matemática indicatriz o característica (toma valor 1 si se cumple la condición argumental, 0 en caso contrario).\n\n2. **Validez (*Validity*)**: Métrica estricta de cumplimiento estructural y semántico. Define el grado en que los conjuntos de datos respetan a cabalidad las reglas de sintaxis subyacentes, tales como formatos definidos por expresiones regulares, tipología estricta de base de datos (`float64`, `datetime`, `VARCHAR`), pertenencia a dominios enumerados fijos y acotación temporal o espacial (rangos admisibles preestablecidos).\n   $$ V = \\frac{| \\{ x \\in D \\mid f_{\\text{validador\\_sintaxis}}(x) = \\text{True} \\} |}{|D|} $$\n\n3. **Precisión o Exactitud (*Accuracy*)**: Dimensiona el grado subyacente en el cual la representación informática captura, simula o refleja con fidelidad métrica el \"mundo real\" ontológico o la entidad veraz objetiva que pretende describir.\n\n4. **Consistencia Lógica (*Consistency*)**: Mide la mitigación o la ausencia rigurosa de paradojas y contradicciones axiomáticas, ya sea intrínsecas (dentro de una misma fila tabular) o inter-relacionales. Si los axiomas de negocio estipulan reglas, los datos no deben infringirlas.\n\n5. **Unicidad y Singularidad (*Uniqueness*)**: Garantía fundamental matemática de inyectividad en los identificadores de llave primaria (*Primary Keys* o identificadores unívocos). Asegura formalmente que ninguna entidad, objeto o instancia de la vida física real o del mundo abstracto de negocio se encuentre insertada, modelada o registrada más de una vez en el conjunto matriz o tabla dimensional principal.\n\n6. **Oportunidad o Actualidad (*Timeliness*)**: Representa paramétricamente la vida media funcional o la vigencia de los datos para el proceso decisional estadístico. \n\n::: {.callout-note title=\"Data Contracts en Plataformas Modernas\"}\nEn la arquitectura de la ingeniería de datos escalable moderna de alto volumen, estas dimensiones ya no se validan asíncronamente o \"después de que el modelo falle\". Se garantizan a priori, de forma proactiva y declarativa mediante el paradigma de *Data Contracts*[^1], protegiendo el perímetro del data lake, integrándose con esquemas estrictos (Protobuf/Avro) y asegurando que los dominios productivos asuman responsabilidad programática total sobre sus *SLA* (Acuerdos de Nivel de Servicio) de calidad antes de exponerlos analíticamente.\n:::\n\n### 3.2. Formulación Algebraica del Pipeline Computacional\n\nA un nivel topológico y funcional formal, podemos conceptualizar y definir axiomáticamente todo el pipeline y orquestación del proceso complejo de transformación como un macro-operador matemático compuesto direccionalmente, al cual denominamos formalmente simplemente *Pipeline* y denotamos mediante $\\mathcal{T}$.\n\nSea, bajo este rigor, $\\mathcal{X}_{\\text{crudo}}$ el hiper-espacio multidimensional heterogéneo original de variables de entrada dispares. Definimos correlativamente $\\mathcal{X}_{\\text{modelo}}$ como el espacio métrico vectorial denso objetivo estrictamente euclidiano. Así, el pipeline se enuncia de la siguiente manera, como una composición anidada determinista de $k$ transformaciones modulares y discretas secuenciales $f_i$:\n\n$$ \\mathcal{T} = f_k \\circ f_{k-1} \\circ \\dots \\circ f_2 \\circ f_1: \\mathcal{X}_{\\text{crudo}} \\to \\mathcal{X}_{\\text{modelo}} $$\n\n#### Propiedades Matemáticas y Limitaciones Estructurales Deseables\n\n1. **Idempotencia**[^2] del Operador Funcional: La propiedad exige que $\\mathcal{T}(\\mathcal{T}(\\mathbf{X})) = \\mathcal{T}(\\mathbf{X})$.\n2. **Coherencia y Consistencia Semántica de Esquema de Ingesta (Schema Consistency)**: Cada función y operador subyacente $f_i$ modular del Pipeline instanciado debe exponer e implementar rigurosamente firmas tipadas paramétricas y contratos formales de entrada y salida enteramente deterministas, predictibles y blindados.\n3. **Desacoplamiento Estructural Profundo y Principio de Inmutabilidad**[^4] entre Fase de Ajuste y Estimación Paramétrica (Fit) vs Aplicación (Transform): \n   - El estado de la función paramétrica se ancla: $\\Theta_i = \\text{Fit}( \\mathbf{X}_{\\text{train\\_subset}}, f_i )$\n   - Se ajusta uniformemente el *batch* o cohorte original interno: $\\mathbf{X}'_{\\text{train\\_subset}} = \\text{Transform}( \\mathbf{X}_{\\text{train\\_subset}}, \\Theta_i )$\n   - Se procesan *batches* estocásticos nuevos no observados usando el estado histórico heredado inmutable: $\\mathbf{X}'_{\\text{eval\\_test}} = \\text{Transform}( \\mathbf{X}_{\\text{eval\\_test}}, \\Theta_i )$\n\n::: {.callout-important title=\"Regla de oro absoluta en producción y auditoría\"}\n**NUNCA**, bajo ninguna circunstancia, justificación apresurada de plazos límite de entrega comercial, ni en experimentación descuidada en cuadernos interactivos, se debe invocar a la baja o activar el ciclo de vida del método mutador de estado iterativo y optimizador profundo `.fit()` o de aprendizaje implícito de un ensamblador de pipelines modulares o subrutina de transformador estadístico en un esquema iterativo, sobre un espacio de particiones validativo u observacional inexplorado (usualmente el conjunto de *Test* o *Validation Holdout split*). Infringir y violar deliberadamente (o accidentalmente) esta premisa arquitectónica de asilamiento inocula, inyecta e introduce directamente el defecto estocástico latente, metodológico, persistente, sistemático, e insidioso más letal y ruinosamente costoso, silencioso y destructivo documentado en toda la disciplina moderna formal y matemática pura en *Machine Learning*: el letal e invisible fenómeno denominado formalmente en la academia como *Data Leakage*[^3].\n:::\n\n## 4. Implementación Computacional Industrial usando el Ecosistema Python (Pandas y Scikit-Learn)\n\nEn los ecosistemas pragmáticos modernos y en el estándar del stack open source maduro industrial impulsado por el pujante ecosistema integrador basado fundamentalmente en el lenguaje Python productivo, la venerable y rápida librería subyacente `pandas` asume valientemente y provee eficientemente las complejas estructuras semánticas e inmutables densas de datos, mientras que, concurrentemente, el macro framework `scikit-learn` nos facilita toda una robusta y testeada capa de abstracción composicional jerárquica estrictamente orientada e instanciada a objetos fuertemente acoplados (Estimadores) para arquitectar, empaquetar, componer y construir los formales pipelines matemáticos entrelazados.\n\nEn este instante, procedamos con cautela y rigor formal a escribir e implementar directamente un pipeline sistémico unificado, exhaustivo, metodológicamente íntegro y arquitecturalmente moderno.\n\n::: {#28ee3b90 .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nimport numpy as np\nfrom sklearn.pipeline import Pipeline\nfrom sklearn.compose import ColumnTransformer\nfrom sklearn.impute import SimpleImputer\nfrom sklearn.preprocessing import StandardScaler, OneHotEncoder, RobustScaler\nfrom sklearn.base import BaseEstimator, TransformerMixin\n\n# 1. Instanciamos y replicamos pragmáticamente los datos crudos anómalos del ejemplo ilustrativo de BigMart\ndata_dict = {\n    'Item_Identifier': ['FDA15', 'DRC01', 'FDN15', 'FDX07', 'NCD19'],\n    'Item_Weight': [9.30, -5.00, np.nan, 19.20, 200.00],\n    'Item_MRP': [249.80, 0.00, 1200000.0, np.nan, 53.86],\n    'Outlet_Establishment_Year': ['1999', '09-Jan-2009', '1998', '14/02/1998', '1985-01-20'],\n    'Item_Fat_Content': ['Low Fat', 'low fat', 'LF', 'Regular', 'reg']\n}\n\nX_raw = pd.DataFrame(data_dict)\nprint(\"================== [ DIAGNÓSTICO INICIAL ] ==================\\n\")\nprint(\"-> Visualización sin filtros algorítmicos del DataFrame Crudo Original Subyacente en bruto:\\n\")\ndisplay(X_raw)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n================== [ DIAGNÓSTICO INICIAL ] ==================\n\n-> Visualización sin filtros algorítmicos del DataFrame Crudo Original Subyacente en bruto:\n\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Item_Identifier</th>\n      <th>Item_Weight</th>\n      <th>Item_MRP</th>\n      <th>Outlet_Establishment_Year</th>\n      <th>Item_Fat_Content</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>FDA15</td>\n      <td>9.3</td>\n      <td>249.80</td>\n      <td>1999</td>\n      <td>Low Fat</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>DRC01</td>\n      <td>-5.0</td>\n      <td>0.00</td>\n      <td>09-Jan-2009</td>\n      <td>low fat</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>FDN15</td>\n      <td>NaN</td>\n      <td>1200000.00</td>\n      <td>1998</td>\n      <td>LF</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>FDX07</td>\n      <td>19.2</td>\n      <td>NaN</td>\n      <td>14/02/1998</td>\n      <td>Regular</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>NCD19</td>\n      <td>200.0</td>\n      <td>53.86</td>\n      <td>1985-01-20</td>\n      <td>reg</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n### 4.1. Ingeniería y Programación de Transformadores Híbridos Personalizados (*Custom Transformers* OOP)\n\nFrecuentemente en la inmensa mayoría de interacciones y despliegues productivos cotidianos, las operaciones asimétricas estocásticas y lógicas de validación curativa, limpieza profunda paramétrica e ingeniería deductiva de preprocesamiento avanzado basadas fundamentalmente en semántica, reglas abstractas de dominio empírico específico anclado a negocio no se hallan disponibles trivialmente por defecto o de manera canónica dentro de la biblioteca central de `scikit-learn`. Frente a esto, la solución arquitectónica paradigmática en OOP consiste indudablemente y obligatoriamente en instanciar y derivar objetos que extiendan y hereden estandarizada y funcionalmente de la super-clase matriz `BaseEstimator` simultáneamente integrando conjuntamente el potente interfaz o mixin compositivo estandarizado de la librería matriz fundamental `TransformerMixin`.\n\n::: {#f1612054 .cell execution_count=2}\n``` {.python .cell-code}\nclass RangoLogicoWeightCleaner(BaseEstimator, TransformerMixin):\n    \"\"\"\n    Transformador algorítmico lógico paramétrico orientado a limpiar anomalías (Outliers) evidentes en pesos de items.\n    Obliga a que los pesos converjan al intervalo [1.0, 50.0]. Valores fuera de rango \n    se fuerzan al estado 'NaN' (Missing Value) habilitando a futuros eslabones (imputadores)\n    para que recojan la anomalía.\n    \"\"\"\n    \n    def __init__(self, umbral_inferior=1.0, umbral_superior=50.0):\n        self.umbral_inferior = umbral_inferior\n        self.umbral_superior = umbral_superior\n\n    def fit(self, X_param, y_etiquetas=None):\n        return self\n    \n    def transform(self, X_param, y_etiquetas=None):\n        # Salvaguardamos iterativamente el estado base forzando un deep clone\n        X_buffer = X_param.copy()\n        \n        # Validamos que la columna exista\n        if 'Item_Weight' in X_buffer.columns:\n            mascara_logica_outliers = (X_buffer['Item_Weight'] < self.umbral_inferior) | (X_buffer['Item_Weight'] > self.umbral_superior)\n            X_buffer.loc[mascara_logica_outliers, 'Item_Weight'] = np.nan\n            \n        return X_buffer\n\nclass CategoryStandardizer(BaseEstimator, TransformerMixin):\n    \"\"\"\n    Estandariza categorías semánticas dispares utilizando un diccionario provisto.\n    \"\"\"\n    def __init__(self, mapping_dict):\n        self.mapping_dict = mapping_dict\n        \n    def fit(self, X, y=None):\n        return self\n    \n    def transform(self, X, y=None):\n        X_ = X.copy()\n        col = X_.columns[0]\n        # Reemplazar y poner en minúsculas para seguridad\n        X_[col] = X_[col].astype(str).str.lower().replace(self.mapping_dict)\n        return X_\n```\n:::\n\n\n### 4.2. Orquestación del Grafo Composicional de Limpieza con `ColumnTransformer`\n\nUtilizando el versátil componente `ColumnTransformer`, implementaremos un enrutador o multiplexador de flujos tabulares. Este objeto enrutará condicionalmente los diferentes subconjuntos de columnas a diferentes pipelines paralelos especializados (con comportamientos distintos según tipos numéricos, heurísticos o discretos), para ulteriormente condensar, fusionar lateralmente y colapsar todos los tensores devueltos en una única matriz.\n\n::: {#c5d7ab48 .cell execution_count=3}\n``` {.python .cell-code}\n# -------------------------------------------------------------------------\n# DEFINICIÓN ARQUITECTÓNICA DE RAMAS PARALELAS (BRANCHES)\n# -------------------------------------------------------------------------\n\n# Rama Especializada A (Peso): Limpieza Heurística Rango -> Imputación Mediana -> Escalado\nweight_pipeline = Pipeline([\n    ('weight_cleaner', RangoLogicoWeightCleaner()),\n    ('imputer', SimpleImputer(strategy='median')),\n    ('scaler', StandardScaler())\n])\n\n# Rama Especializada B (Precios MRP): Imputación Media -> Escalado Robusto\n# NOTA: Para mitigar matemáticamente el impacto generado por el outlier severo de \"1.2 millones\",\n# empleamos deliberadamente el 'RobustScaler', que re-centra usando la mediana y comprime\n# usando el Rango Intercuartílico (IQR).\nmrp_pipeline = Pipeline([\n    ('imputer', SimpleImputer(strategy='mean')),\n    ('scaler', RobustScaler())\n])\n\n# Rama Especializada C (Semántica y Categórica Nominal): Estandarización -> Imputación Moda -> Discretización One Hot\ndiccionario_mapeo_semantico = {\n    'low fat': 'low fat', 'lf': 'low fat',\n    'regular': 'regular', 'reg': 'regular'\n}\ncat_pipeline = Pipeline([\n    ('standardizer', CategoryStandardizer(mapping_dict=diccionario_mapeo_semantico)),\n    ('imputer', SimpleImputer(strategy='most_frequent')),\n    ('onehot', OneHotEncoder(sparse_output=False, handle_unknown='ignore'))\n])\n\n# Ensamblado Macro-Arquitectónico en el Objeto global ColumnTransformer \npreprocessor = ColumnTransformer(\n    transformers=[\n        ('weight_proc', weight_pipeline, ['Item_Weight']), \n        ('mrp_proc', mrp_pipeline, ['Item_MRP']),\n        ('cat_proc', cat_pipeline, ['Item_Fat_Content'])\n    ],\n    remainder='drop' # Eliminamos temporalmente variables Fechas e Identificadores ruidosos\n)\n\n# --- Flujo de Trabajo Simulado ---\n# En un escenario productivo dividiríamos con `train_test_split`.\nX_processed = preprocessor.fit_transform(X_raw)\n\nprint(\"\\n================== [ MATRIZ NUMÉRICA TRANSFORMADA FINAL ] ==================\\n\")\nprint(\"-> Visualización matricial densa lista para el modelo ML:\\n\")\ndisplay(pd.DataFrame(X_processed))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n================== [ MATRIZ NUMÉRICA TRANSFORMADA FINAL ] ==================\n\n-> Visualización matricial densa lista para el modelo ML:\n\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>0</th>\n      <th>1</th>\n      <th>2</th>\n      <th>3</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>-1.581139</td>\n      <td>0.000000</td>\n      <td>1.0</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>0.000000</td>\n      <td>-0.000833</td>\n      <td>1.0</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>0.000000</td>\n      <td>3.998873</td>\n      <td>1.0</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>1.581139</td>\n      <td>0.999347</td>\n      <td>0.0</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>0.000000</td>\n      <td>-0.000653</td>\n      <td>0.0</td>\n      <td>1.0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## 5. Prácticas Críticas y Riesgos Inherentes Globales en Entornos de Producción (MLOps)\n\n### 5.1. Degradaciones Latentes Dinámicas: Feature Drift y Concept Drift\nUna vez que el modelo estocástico subyacente predictivo e algorítmico iterativo final se encuentra desplegado, la inmaculada distribución analítica probabilística teórica de los datos cambia de forma insidiosa con el tiempo. \n\nEsta deriva se conoce canónicamente como ***Feature drift* (o *Covariate Shift*)**[^5]. \nPor ejemplo, si la media de precios sube debido a una hiperinflación, nuestro `StandardScaler` (el cual congeló la media del set de entrenamiento en el objeto `.fit()`) fallará y estandarizará incorrectamente todos los nuevos *batches* masivos de datos. En consecuencia, el modelo perderá drásticamente toda generalización. Por ello, el monitoreo continuo de la observabilidad y la comparativa de los flujos de datos en producción es una obligatoriedad absoluta.\n\n::: {.callout-tip title=\"Mejores prácticas y mitigaciones de oro irrenunciables en la industria\"}\nPara blindar la robustez y escalabilidad de los pipelines macro paramétricos en MLOps, se postulan las siguientes implementaciones:\n\n1. **Serialización Múltiple Heurística Unificada**: Como dogma, encapsula e integra el predictor y todo tu Pipeline de preprocesamiento en un estado inmutable y persiste ambos eslabones como un único artefacto binario usando la liberaría `joblib` o herramientas de gestión MLOps como `MLflow`.\n2. **Validación Preventiva Defensiva Perimetral (Run-time Validation)**: Resulta neurálgico incorporar y utilizar proactivamente barreras defensivas, validadores sintácticos y guardianes como *Pandera* o *Great Expectations* justo antes de que los datos ingresen al método `.transform()`. Si una anomalía de tipo ocurre, el flujo debe detenerse de emergencia, emitiendo una aserción y alerta antes de que el motor corrompa e inyecte basura numérica a los modelos.\n:::\n\n## Resumen de Pilares Axiomáticos\n- **La Maldición Operacional \"Garbage In, Garbage Out\"**: El estado inicial cualitativo del crudo dato dicta irremediablemente el límite superior de rendimiento de cualquier IA.\n- **Principio Fundamental de Aislamiento (Fit vs Transform Split)**: Mantener segregados los universos de datos de *Train* y *Hold-Out Validation* durante toda etapa de preprocesamiento es una máxima científica innegociable en *machine learning* iterativo. \n\n---\n\n[^1]: **Data Contracts (Contratos de Datos)**: Son compromisos técnicos declarativos formales inmutables (especificados en YAML o JSON Schemas) entre equipos productores de *datasets* y consumidores algorítmicos. Fuerzan expectativas unívocas y Service Level Agreements paramétricos estocásticos lógicos.\n[^2]: **Idempotencia Transaccional Computacional**: Propiedad algorítmica axiomática en la cual el resultado tras aplicar una transformación u operación sobre un objeto múltiples veces es estrictamente idéntico al obtenido tras aplicarlo una única primera vez.\n[^3]: **Data Leakage (Fuga de Datos Analítica)**: Defecto fatídico algorítmico que ocurre trágicamente cuando información de los datos de evaluación (test) se derrama, cruza o influye las métricas (como la media poblacional calculada) durante la fase de modelado algorítmico o preprocesamiento formativo.\n[^4]: **Principio de Inmutabilidad en Pipelines**: Patrón rector arquitectural donde las tablas matrices orígenes (como DataFrames o Tensores) provistos por el usuario jamás deben ser sobrescritos, mutados o alterados asimétricamente *in situ* durante la ejecución.\n[^5]: **Feature drift vs Concept drift**: El *Feature drift* emerge cuando la distribución probabilística basal de las variables de entrada fluctúa ($P(\\mathcal{X})$ cambia) sostenidamente (e.g., Inflación). El *Concept drift* se materializa abruptamente cuando la relación causal subyacente que mapea $X$ a $Y$ ($P(\\mathcal{Y}|\\mathcal{X})$) se rompe (e.g., Cambios masivos de comportamiento poblacional tras una pandemia).\n\n",
    "supporting": [
      "4-1-introduccion_files/figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}