project:
  type: default
  output-dir: _output
  render:
    - "03-eda/*.qmd"
    - "04-preprocesamiento/*.qmd"
    - "05-patrones/*.qmd"
    - "06-clasificacion/*.qmd"
    - "!_templates/"
    - "!_drafts/"

format:
  revealjs:
    theme: assets/unam-theme.scss
    logo: assets/Logo_FC_Color.png
    slide-number: true
    controls: true
    transition: slide
    background-transition: fade
    highlight-style: github
    code-overflow: wrap
    embed-resources: false
    lib-dir: libs
    html-math-method: katex
    fig-align: center
    footer: "Facultad de Ciencias UNAM · Almacenes y Minería de Datos"

execute:
  warning: false
  message: false
  cache: false

lang: es
