{
  "hash": "cdc06a6446df66e855476041423c8541",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Medidas de variabilidad\"\nauthor: \"Diego Villalba\"\ndate: today\nlang: es\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    number-sections: true\n    code-fold: true\n    code-tools: true\n    code-summary: \"Mostrar código\"\n    fig-align: center\n    theme: cosmo\n  pdf:\n    toc: true\n    toc-depth: 3\n    number-sections: true\nexecute:\n  echo: true\n  warning: false\n  message: false\n  cache: false\njupyter: python3\nbibliography: [referencias_eda.bib, ../../references.bib]\ncrossref:\n  fig-title: \"Figura\"\n  tbl-title: \"Tabla\"\n  eq-prefix: \"Ec.\"\n---\n\n## El problema: cumplir el promedio no basta\n\nDos equipos entregan ocho pedidos cada uno. En ambos casos, el tiempo medio es\nde 15.5 minutos:\n\n| Pedido ordenado | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | Media |\n|:---|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n| Equipo Regular | 12 | 14 | 15 | 15 | 16 | 16 | 17 | 19 | 15.5 |\n| Equipo Irregular | 5 | 8 | 12 | 15 | 16 | 19 | 23 | 26 | 15.5 |\n\nSi solo se reporta el promedio, los equipos parecen equivalentes. Sin embargo,\npara quien espera su pedido no lo son: con el primer equipo casi todos los\ntiempos están cerca de 15.5; con el segundo pueden ser muy cortos o muy largos.\n\nLa **variabilidad** describe cuánto difieren los valores entre sí o respecto de\nun centro. Es una propiedad de una variable cuantitativa:[^cuantitativa] no\nbasta saber dónde está el centro de la distribución, también importa cuánto se\nextiende alrededor de él [@tukey1977eda; @nist2012handbook].\n\n::: {.callout-note appearance=\"minimal\"}\n### Dos casos que servirán como brújula\n\n- Si los ocho pedidos tardaran exactamente 15.5 minutos, la variabilidad\n  debería ser **cero**.\n- Si unos tiempos se alejan del centro mientras otros se acercan de manera que\n  la media no cambia, la variabilidad debería **aumentar**.\n\nUna buena medida de dispersión debe distinguir estos casos, pero no todas\nresponden igual ante valores extremos ni se expresan en las mismas unidades.\n:::\n\n## Primera mirada: la amplitud total\n\nEl **rango** resta el mínimo al máximo. Si\n$x_{(1)}\\le\\cdots\\le x_{(n)}$ son los datos ordenados,[^estadistico-orden]\n\n$$\nR=x_{(n)}-x_{(1)}. \\tag{1}\n$$\n\nPara el Equipo Regular,\n\n$$\nR_R=19-12=7\\ \\text{minutos};\n$$\n\npara el Equipo Irregular,\n\n$$\nR_I=26-5=21\\ \\text{minutos}.\n$$\n\nEl segundo equipo cubre una amplitud tres veces mayor. La conclusión es útil,\npero se apoya únicamente en dos observaciones. Si el tiempo 19 del primer\nequipo fuera un error de captura y en realidad fuera 49, su rango saltaría de\n7 a 37 minutos aunque los otros siete tiempos permanecieran intactos.\n\n::: {.callout-important appearance=\"minimal\"}\nEl rango contesta “¿qué tan separados están los dos extremos?”. No contesta\n“¿qué tan lejos del centro está un pedido típico?”. Para esa segunda pregunta\nnecesitamos usar todos los datos.\n:::\n\n## De las desviaciones a la varianza\n\n### El obstáculo de los signos\n\nTomemos los tiempos del Equipo Regular:\n\n$$\nx=(12,14,15,15,16,16,17,19).\n$$\n\nSu suma es 124 y su media es\n\n$$\n\\bar{x}=\\frac{124}{8}=15.5.\n$$\n\nUna **desviación** es la distancia con signo $x_i-\\bar{x}$ entre una\nobservación y la media:\n\n| $x_i$ | 12 | 14 | 15 | 15 | 16 | 16 | 17 | 19 |\n|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n| $x_i-15.5$ | $-3.5$ | $-1.5$ | $-0.5$ | $-0.5$ | $0.5$ | $0.5$ | $1.5$ | $3.5$ |\n\nLas desviaciones suman cero. Esto no demuestra ausencia de variabilidad: las\ndistancias a la izquierda y a la derecha de la media se cancelan. Elevarlas al\ncuadrado evita la cancelación y da más peso a las desviaciones grandes:\n\n| $x_i-15.5$ | $-3.5$ | $-1.5$ | $-0.5$ | $-0.5$ | $0.5$ | $0.5$ | $1.5$ | $3.5$ |\n|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n| $(x_i-15.5)^2$ | 12.25 | 2.25 | 0.25 | 0.25 | 0.25 | 0.25 | 2.25 | 12.25 |\n\nLa **suma de cuadrados** es\n\n$$\nSS=\\sum_{i=1}^{8}(x_i-15.5)^2=30\\ \\text{minutos}^2. \\tag{2}\n$$\n\nLa suma crece si hay más observaciones, aunque la dispersión no cambie. Por\neso se divide entre una cantidad relacionada con el número de datos. El\ndivisor correcto depende de qué representan esos ocho pedidos.\n\n## ¿Población completa o muestra?\n\n### Cuando los datos son todo lo que queremos describir\n\nSi esos ocho pedidos son **todos** los pedidos del turno y la pregunta se\nlimita a describir ese turno, constituyen la población de interés.[^poblacion]\nLa varianza poblacional es\n\n$$\n\\sigma^2=\\frac{1}{N}\\sum_{i=1}^{N}(x_i-\\mu)^2. \\tag{3}\n$$\n\ndonde $N$ es el tamaño de la población y $\\mu$ su media. Para el turno:\n\n$$\n\\sigma^2=\\frac{30}{8}=3.75\\ \\text{minutos}^2.\n$$\n\nLa varianza queda en unidades **cuadradas** porque también lo están sus\nsumandos. Para regresar a la escala de los datos se extrae la raíz cuadrada:\n\n$$\n\\sigma=\\sqrt{3.75}=1.9365\\ \\text{minutos}. \\tag{4}\n$$\n\nLa desviación estándar poblacional es, por tanto, de aproximadamente 1.94\nminutos.\n\n### Cuando los datos pretenden representar más casos\n\nSi los ocho pedidos son una muestra aleatoria de todos los pedidos que el\nequipo podría atender, $\\bar{x}$ y $s^2$ son **estadísticos** usados para\nestimar parámetros desconocidos de una población mayor.[^parametro]\nLa varianza muestral usual es\n\n$$\ns^2=\\frac{1}{n-1}\\sum_{i=1}^{n}(x_i-\\bar{x})^2. \\tag{5}\n$$\n\nEn el ejemplo,\n\n$$\ns^2=\\frac{30}{8-1}=4.2857\\ \\text{minutos}^2,\n\\qquad\ns=\\sqrt{4.2857}=2.0702\\ \\text{minutos}.\n$$\n\nNo cambiaron los datos ni la suma de cuadrados: cambió la finalidad. Dividir\nentre $n$ describe exactamente la colección observada; dividir entre $n-1$\nproduce, bajo muestreo independiente de una población con varianza finita, un\nestimador insesgado de $\\sigma^2$ [@freedman2007statistics].[^insesgado]\n\n### ¿De dónde sale el grado de libertad perdido?\n\nUna vez calculada $\\bar{x}$, las desviaciones cumplen\n\n$$\n\\sum_{i=1}^{n}(x_i-\\bar{x})=0.\n$$\n\nSi conocemos $n-1$ desviaciones, la última ya no puede variar libremente: debe\nser el número que haga cero la suma. Quedan $n-1$ **grados de libertad**.[^gl]\nLa llamada corrección de Bessel compensa además que la media muestral fue\najustada con los mismos datos y hace a $s^2$ insesgada. Esto no significa que\n$s$ sea insesgada ni que siempre deba dividirse entre $n-1$.\n\n::: {.callout-warning appearance=\"minimal\"}\n### Una convención no se elige por el tamaño del archivo\n\nNo use $n-1$ solo porque hay pocos datos ni $n$ solo porque hay muchos. Primero\ndefina el universo de la afirmación: “estos ocho pedidos” pide descripción\npoblacional; “el desempeño futuro del equipo” plantea una inferencia desde una\nmuestra y requiere, además, justificar cómo se obtuvieron los pedidos.\n:::\n\n## Misma media, diferente variabilidad\n\nPara el Equipo Irregular, la media también es 15.5, pero\n\n$$\n\\begin{aligned}\nSS_I\n&=(-10.5)^2+(-7.5)^2+(-3.5)^2+(-0.5)^2\\\\\n&\\quad +(0.5)^2+(3.5)^2+(7.5)^2+(10.5)^2\\\\\n&=358.\n\\end{aligned}\n$$\n\nSi los ocho pedidos son la población de cada turno,\n\n$$\n\\sigma_I^2=\\frac{358}{8}=44.75,\n\\qquad\n\\sigma_I=\\sqrt{44.75}=6.6895\\ \\text{minutos}.\n$$\n\nLa tabla reúne lo aprendido:\n\n| Medida poblacional | Equipo Regular | Equipo Irregular |\n|:---|---:|---:|\n| Media | 15.5 min | 15.5 min |\n| Rango | 7 min | 21 min |\n| Varianza | 3.75 min$^2$ | 44.75 min$^2$ |\n| Desviación estándar | 1.94 min | 6.69 min |\n\nLa media no distingue los equipos; las tres medidas de variabilidad sí. La\ndesviación estándar suele ser más fácil de comunicar que la varianza porque\nestá en minutos, pero la varianza es central en muchos algoritmos por sus\npropiedades algebraicas.\n\n::: {.callout-note appearance=\"minimal\"}\n### Cómo leer una desviación estándar\n\n$\\sigma=1.94$ minutos no significa que todos los pedidos estén a 1.94 minutos\nde la media ni que sea la distancia absoluta promedio. Es la raíz del promedio\nde distancias **cuadradas**. Si la distribución fuera aproximadamente normal,\nalrededor del 68% de los valores caería entre $\\mu-\\sigma$ y $\\mu+\\sigma$; esa\nregla no se traslada automáticamente a distribuciones sesgadas o multimodales.[^normal]\n:::\n\n## Laboratorio: mover los pedidos y observar las medidas\n\n::: {.content-visible when-format=\"html\"}\n```{=html}\n<style>\n#variability-lab{--ink:#172033;--muted:#5b6474;--blue:#2563eb;--orange:#d97706;--green:#16835f;max-width:1040px;margin:1.4rem auto;font-family:system-ui,sans-serif;color:var(--ink)}\n#variability-lab .lab-shell{border:1px solid #d7dde8;border-radius:18px;padding:1.15rem;background:linear-gradient(135deg,#f8fbff,#fffaf2);box-shadow:0 10px 28px rgba(23,32,51,.08)}\n#variability-lab .lab-title{font-size:1.18rem;font-weight:750;margin:0 0 .25rem}\n#variability-lab .lab-intro{color:var(--muted);margin:.2rem 0 1rem}\n#variability-lab .lab-layout{display:grid;grid-template-columns:minmax(250px,.8fr) minmax(360px,1.4fr);gap:1rem;align-items:start}\n#variability-lab .preset-row{display:flex;flex-wrap:wrap;gap:.45rem;margin-bottom:.8rem}\n#variability-lab button{border:1px solid #aeb9cb;background:#fff;border-radius:999px;padding:.4rem .7rem;cursor:pointer;color:var(--ink)}\n#variability-lab button:hover,#variability-lab button:focus{border-color:var(--blue);outline:2px solid #bfdbfe}\n#variability-lab .control-row{display:grid;grid-template-columns:4.5rem 1fr 2.3rem;gap:.45rem;align-items:center;font-size:.82rem;margin:.3rem 0}\n#variability-lab input{width:100%;accent-color:var(--blue)}\n#variability-lab output{font-variant-numeric:tabular-nums;text-align:right;font-weight:700}\n#variability-lab .metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:.55rem;margin-top:.85rem}\n#variability-lab .metric{background:#fff;border:1px solid #dce2eb;border-radius:10px;padding:.55rem;text-align:center}\n#variability-lab .metric span{display:block;color:var(--muted);font-size:.74rem}\n#variability-lab .metric strong{font-size:1.02rem;font-variant-numeric:tabular-nums}\n#variability-lab svg{width:100%;height:auto;background:#fff;border:1px solid #dce2eb;border-radius:12px}\n#variability-lab .lab-reading{margin:.7rem 0 0;color:var(--muted);font-size:.88rem}\n@media(max-width:760px){#variability-lab .lab-layout{grid-template-columns:1fr}#variability-lab .metrics{grid-template-columns:repeat(2,1fr)}}\n</style>\n<div id=\"variability-lab\" aria-labelledby=\"variability-lab-title\">\n  <div class=\"lab-shell\">\n    <p id=\"variability-lab-title\" class=\"lab-title\">Laboratorio de tiempos de entrega</p>\n    <p class=\"lab-intro\">Mueva cualquier pedido o cargue un escenario. La línea azul marca la media y la naranja la mediana.</p>\n    <div class=\"preset-row\">\n      <button type=\"button\" data-preset=\"regular\">Equipo Regular</button>\n      <button type=\"button\" data-preset=\"irregular\">Equipo Irregular</button>\n      <button type=\"button\" data-preset=\"extreme\">Un retraso extremo</button>\n      <button type=\"button\" data-preset=\"equal\">Todos iguales</button>\n    </div>\n    <div class=\"lab-layout\">\n      <div data-controls></div>\n      <div>\n        <svg data-plot viewBox=\"0 0 680 300\" role=\"img\" aria-label=\"Recta numérica de tiempos de entrega con media y mediana\"></svg>\n        <p class=\"lab-reading\" data-reading aria-live=\"polite\"></p>\n      </div>\n    </div>\n    <div class=\"metrics\" aria-live=\"polite\">\n      <div class=\"metric\"><span>Media</span><strong data-metric=\"mean\"></strong></div>\n      <div class=\"metric\"><span>Rango</span><strong data-metric=\"range\"></strong></div>\n      <div class=\"metric\"><span>Varianza poblacional</span><strong data-metric=\"variance\"></strong></div>\n      <div class=\"metric\"><span>Desv. estándar poblacional</span><strong data-metric=\"sd\"></strong></div>\n      <div class=\"metric\"><span>IQR (mitades)</span><strong data-metric=\"iqr\"></strong></div>\n      <div class=\"metric\"><span>MAD</span><strong data-metric=\"mad\"></strong></div>\n    </div>\n  </div>\n</div>\n<script>\n(() => {\n  const root=document.getElementById('variability-lab'); if(!root)return;\n  const scenarios={regular:[12,14,15,15,16,16,17,19],irregular:[5,8,12,15,16,19,23,26],extreme:[12,14,15,15,16,16,17,45],equal:[16,16,16,16,16,16,16,16]};\n  const controls=root.querySelector('[data-controls]'),svg=root.querySelector('[data-plot]'),NS='http://www.w3.org/2000/svg';\n  const median=a=>{const b=[...a].sort((x,y)=>x-y),m=b.length>>1;return b.length%2?b[m]:(b[m-1]+b[m])/2};\n  const quartiles=a=>{const b=[...a].sort((x,y)=>x-y),m=b.length>>1;return b.length%2?[median(b.slice(0,m)),median(b.slice(m+1))]:[median(b.slice(0,m)),median(b.slice(m))]};\n  const add=(tag,attrs,text='')=>{const e=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));e.textContent=text;svg.appendChild(e);return e};\n  scenarios.regular.forEach((v,i)=>{const label=document.createElement('label');label.className='control-row';label.innerHTML=`<span>Pedido ${i+1}</span><input type=\"range\" min=\"0\" max=\"50\" step=\"1\" value=\"${v}\" data-value=\"${i}\"><output>${v}</output>`;controls.appendChild(label)});\n  const inputs=[...root.querySelectorAll('[data-value]')];\n  function update(){\n    const x=inputs.map(el=>+el.value);inputs.forEach(el=>el.nextElementSibling.value=el.value);\n    const sorted=[...x].sort((a,b)=>a-b),mean=x.reduce((a,b)=>a+b,0)/x.length,med=median(x),[q1,q3]=quartiles(x),variance=x.reduce((s,v)=>s+(v-mean)**2,0)/x.length,sd=Math.sqrt(variance),mad=median(x.map(v=>Math.abs(v-med))),range=sorted.at(-1)-sorted[0];\n    const values={mean,range,variance,sd,iqr:q3-q1,mad};Object.entries(values).forEach(([k,v])=>root.querySelector(`[data-metric=\"${k}\"]`).textContent=v.toFixed(2));\n    root.querySelector('[data-reading]').textContent=`El 50% central va de ${q1.toFixed(1)} a ${q3.toFixed(1)} min. Compare cuánto se mueve cada medida al cargar “Un retraso extremo”.`;\n    svg.replaceChildren();const left=55,right=650,base=220,min=Math.min(0,sorted[0]-3),max=Math.max(30,sorted.at(-1)+3),sx=v=>left+(v-min)/(max-min)*(right-left);\n    add('line',{x1:left,y1:base,x2:right,y2:base,stroke:'#64748b','stroke-width':'2'});\n    for(let t=Math.ceil(min/5)*5;t<=max;t+=5){add('line',{x1:sx(t),y1:base-6,x2:sx(t),y2:base+6,stroke:'#64748b'});add('text',{x:sx(t),y:base+25,'text-anchor':'middle',fill:'#5b6474','font-size':'12'},t)}\n    const seen={};x.forEach((v,i)=>{seen[v]=(seen[v]||0)+1;const y=base-18-(seen[v]-1)*22;add('circle',{cx:sx(v),cy:y,r:8,fill:'#16835f',opacity:'.84'});add('text',{x:sx(v),y:y-12,'text-anchor':'middle',fill:'#172033','font-size':'10'},i+1)});\n    add('line',{x1:sx(mean),y1:35,x2:sx(mean),y2:base,stroke:'#2563eb','stroke-width':'3'});add('text',{x:sx(mean),y:25,'text-anchor':'middle',fill:'#2563eb','font-size':'13','font-weight':'700'},`media ${mean.toFixed(2)}`);\n    add('line',{x1:sx(med),y1:62,x2:sx(med),y2:base,stroke:'#d97706','stroke-width':'3','stroke-dasharray':'6 5'});add('text',{x:sx(med),y:55,'text-anchor':'middle',fill:'#d97706','font-size':'13','font-weight':'700'},`mediana ${med.toFixed(2)}`);\n    add('text',{x:(left+right)/2,y:282,'text-anchor':'middle',fill:'#5b6474','font-size':'13'},'Tiempo (minutos)');\n  }\n  inputs.forEach(el=>el.addEventListener('input',update));root.querySelectorAll('[data-preset]').forEach(btn=>btn.addEventListener('click',()=>{scenarios[btn.dataset.preset].forEach((v,i)=>inputs[i].value=v);update()}));update();\n})();\n</script>\n```\n:::\n\n::: {.content-visible unless-format=\"html\"}\nEl laboratorio de la versión HTML permite mover los ocho tiempos y actualiza\nmedia, rango, varianza poblacional, desviación estándar, IQR y MAD. Sus cuatro\nescenarios de referencia son:\n\n| Escenario | Datos | Media | $\\sigma$ | IQR | MAD |\n|:---|:---|---:|---:|---:|---:|\n| Regular | 12, 14, 15, 15, 16, 16, 17, 19 | 15.5 | 1.94 | 2.0 | 1.0 |\n| Irregular | 5, 8, 12, 15, 16, 19, 23, 26 | 15.5 | 6.69 | 11.0 | 3.5 |\n| Retraso extremo | 12, 14, 15, 15, 16, 16, 17, 45 | 18.75 | 10.02 | 2.0 | 1.0 |\n| Todos iguales | 16, 16, 16, 16, 16, 16, 16, 16 | 16.0 | 0.00 | 0.0 | 0.0 |\n\nEl retraso extremo mueve con fuerza la media y la desviación estándar, pero no\ncambia el IQR ni el MAD bajo la convención de cuartiles usada en el capítulo.\n:::\n\n## Variabilidad del centro: IQR y MAD\n\nLa varianza y la desviación estándar usan todos los valores y reaccionan con\nfuerza a un extremo porque elevan las desviaciones al cuadrado. Cuando hay\ncolas largas, errores o eventos extraordinarios, conviene acompañarlas con\nmedidas **robustas**.[^robusta]\n\n### Intervalo intercuartílico\n\nLos cuartiles $Q_1$ y $Q_3$ dejan aproximadamente 25% y 75% de los datos a su\nizquierda. El **intervalo intercuartílico** es\n\n$$\nIQR=Q_3-Q_1. \\tag{6}\n$$\n\nPara evitar ambigüedad, usaremos el método de medianas de las mitades: con un\nnúmero par de datos, $Q_1$ es la mediana de la mitad inferior y $Q_3$ la de la\nmitad superior.[^cuartiles]\n\nEn el Equipo Regular,\n\n$$\nL=(12,14,15,15),\\qquad U=(16,16,17,19),\n$$\n\n$$\nQ_1=\\frac{14+15}{2}=14.5,\n\\qquad\nQ_3=\\frac{16+17}{2}=16.5,\n$$\n\n$$\nIQR=16.5-14.5=2\\ \\text{minutos}.\n$$\n\nAsí, la mitad central de los tiempos ocupa un intervalo de 2 minutos. Para el\nEquipo Irregular, $Q_1=10$, $Q_3=21$ e $IQR=11$ minutos.\n\nLa regla de Tukey identifica como **candidatos** a valores atípicos los que\ncaen fuera de\n\n$$\n[Q_1-1.5IQR,\\;Q_3+1.5IQR]. \\tag{7}\n$$\n\nPara el Equipo Regular los límites son\n\n$$\n[14.5-1.5(2),\\;16.5+1.5(2)]=[11.5,19.5].\n$$\n\nNingún tiempo queda fuera. La regla es una señal de investigación, no una orden\npara borrar observaciones [@tukey1977eda]. Un retraso puede ser real y contener\ninformación operacional importante.\n\n### Desviación absoluta mediana\n\nLa **MAD** (*median absolute deviation*) reemplaza la media por la mediana y\nlos cuadrados por distancias absolutas:\n\n$$\nMAD=\\operatorname{mediana}_i\\{|x_i-\\tilde{x}|\\}, \\tag{8}\n$$\n\ndonde $\\tilde{x}$ es la mediana. Para el Equipo Regular,\n\n$$\n\\tilde{x}=\\frac{15+16}{2}=15.5\n$$\n\ny las distancias absolutas ordenadas son\n\n$$\n(0.5,0.5,0.5,0.5,1.5,1.5,3.5,3.5).\n$$\n\nPor tanto,\n\n$$\nMAD=\\frac{0.5+1.5}{2}=1\\ \\text{minuto}.\n$$\n\nSi se desea una escala comparable con la desviación estándar bajo una\ndistribución normal, se usa con frecuencia\n\n$$\nMAD_N=1.4826\\,MAD=1.4826\\ \\text{minutos}. \\tag{9}\n$$\n\nLa constante no vuelve normales a los datos: solo calibra la medida bajo ese\nmodelo [@rousseeuw1993alternatives]. En datos discretos o con muchos empates,\nla MAD puede ser cero aunque no todos los valores sean iguales.\n\n### Un retraso extremo\n\nCompare el turno regular con $x^*=(12,14,15,15,16,16,17,45)$, donde solo el\núltimo tiempo cambió:\n\n| Medida poblacional | Turno regular | Con retraso extremo | Cambio |\n|:---|---:|---:|---:|\n| Media | 15.50 | 18.75 | +3.25 |\n| Desviación estándar | 1.94 | 10.02 | +8.09 |\n| Rango | 7.00 | 33.00 | +26.00 |\n| IQR | 2.00 | 2.00 | 0.00 |\n| MAD | 1.00 | 1.00 | 0.00 |\n\nIQR y MAD no “ignoran” por definición los valores extremos: su resistencia\nproviene de posiciones centrales y puede desaparecer si la contaminación\nalcanza una fracción suficiente de los datos. Por eso se reportan junto con la\ndistribución y no como sustitutos automáticos de toda medida clásica.\n\n## Comparar variabilidad entre escalas\n\nSuponga que otro proceso registra tiempos en segundos. Su desviación estándar\nserá 60 veces mayor aunque la regularidad física sea la misma. Las medidas en\nunidades originales no permiten comparar directamente variables con escalas\nmuy distintas.\n\nEl **coeficiente de variación** mide dispersión relativa:\n\n$$\nCV=\\frac{\\sigma}{|\\mu|}\n\\quad\\text{o, en una muestra,}\\quad\nCV_m=\\frac{s}{|\\bar{x}|}. \\tag{10}\n$$\n\nPara el turno regular considerado como población,\n\n$$\nCV=\\frac{1.9365}{15.5}=0.1249=12.49\\%.\n$$\n\nPara el turno irregular,\n\n$$\nCV=\\frac{6.6895}{15.5}=0.4316=43.16\\%.\n$$\n\nEl segundo turno tiene una dispersión equivalente a 43.16% de su media. El CV\nes adimensional y no cambia al convertir minutos a segundos, pero solo es\ninterpretable en escalas de razón con cero absoluto.[^razon] No debe emplearse\nsi la media es cero o cercana a cero; tampoco para comparar temperaturas en\ngrados Celsius, cuyo cero es convencional.\n\n## Formalización y propiedades\n\nSea $X$ una variable aleatoria numérica con media $\\mu=\\mathbb{E}[X]$ y segundo\nmomento finito. Su varianza se define como\n\n$$\n\\operatorname{Var}(X)=\\mathbb{E}\\!\\left[(X-\\mu)^2\\right]\n=\\mathbb{E}[X^2]-\\mu^2. \\tag{11}\n$$\n\nLa segunda igualdad se obtiene al expandir el cuadrado y usar la linealidad de\nla esperanza. La desviación estándar es\n\n$$\n\\operatorname{SD}(X)=\\sqrt{\\operatorname{Var}(X)}. \\tag{12}\n$$\n\nEstas definiciones implican propiedades que una implementación debe respetar:\n\n1. $\\operatorname{Var}(X)\\ge0$ y vale cero exactamente cuando $X$ es constante\n   con probabilidad uno.\n2. Sumar una constante cambia la ubicación, no la dispersión:\n   $\\operatorname{Var}(X+b)=\\operatorname{Var}(X)$.\n3. Cambiar la escala multiplica la varianza por el cuadrado:\n   $\\operatorname{Var}(aX)=a^2\\operatorname{Var}(X)$.\n4. En consecuencia,\n   $\\operatorname{SD}(aX+b)=|a|\\operatorname{SD}(X)$; la desviación estándar\n   conserva las unidades originales.\n\nPara $a=60$, convertir minutos a segundos multiplica la varianza por 3600 y la\ndesviación estándar por 60. En cambio, $CV$ permanece igual si $a>0$ porque\nnumerador y denominador reciben el mismo factor.\n\n::: {.callout-warning appearance=\"minimal\"}\n### Variabilidad observada no equivale a incertidumbre de la media\n\nLa desviación estándar describe diferencias **entre observaciones**. El error\nestándar de la media describe cuánto variaría $\\bar{x}$ entre muestras del\nmismo tamaño; bajo observaciones independientes es $s/\\sqrt{n}$. Son preguntas\ndistintas y no deben intercambiarse.[^error-estandar]\n:::\n\n## Implementación reproducible\n\nLa función siguiente hace explícitas dos decisiones que a menudo quedan\nocultas: si se usa divisor poblacional o muestral, y cómo se calculan los\ncuartiles.\n\n::: {#01c071fe .cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\n\ndef mediana(valores):\n    valores = np.sort(np.asarray(valores, dtype=float))\n    n = valores.size\n    mitad = n // 2\n    return valores[mitad] if n % 2 else (valores[mitad - 1] + valores[mitad]) / 2\n\ndef cuartiles_mitades(valores):\n    valores = np.sort(np.asarray(valores, dtype=float))\n    n = valores.size\n    mitad = n // 2\n    inferior = valores[:mitad]\n    superior = valores[mitad + 1:] if n % 2 else valores[mitad:]\n    return mediana(inferior), mediana(superior)\n\ndef resumen_variabilidad(valores, tipo=\"poblacion\"):\n    x = np.asarray(valores, dtype=float)\n    if x.ndim != 1 or x.size < 2 or not np.isfinite(x).all():\n        raise ValueError(\"Se requieren al menos dos valores finitos.\")\n    if tipo not in {\"poblacion\", \"muestra\"}:\n        raise ValueError(\"tipo debe ser 'poblacion' o 'muestra'.\")\n\n    ddof = 0 if tipo == \"poblacion\" else 1\n    centro = x.mean()\n    centro_robusto = mediana(x)\n    q1, q3 = cuartiles_mitades(x)\n    desviacion = x.std(ddof=ddof)\n    cv = desviacion / abs(centro) if centro != 0 else np.nan\n\n    return pd.Series({\n        \"n\": x.size,\n        \"media\": centro,\n        \"rango\": x.max() - x.min(),\n        \"varianza\": x.var(ddof=ddof),\n        \"desviación estándar\": desviacion,\n        \"Q1\": q1,\n        \"Q3\": q3,\n        \"IQR\": q3 - q1,\n        \"MAD\": mediana(np.abs(x - centro_robusto)),\n        \"CV\": cv,\n    })\n\nregular = np.array([12, 14, 15, 15, 16, 16, 17, 19])\nirregular = np.array([5, 8, 12, 15, 16, 19, 23, 26])\n\npd.DataFrame({\n    \"Regular (población)\": resumen_variabilidad(regular, \"poblacion\"),\n    \"Regular (muestra)\": resumen_variabilidad(regular, \"muestra\"),\n    \"Irregular (población)\": resumen_variabilidad(irregular, \"poblacion\"),\n}).round(4)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Regular (población)</th>\n      <th>Regular (muestra)</th>\n      <th>Irregular (población)</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>n</th>\n      <td>8.0000</td>\n      <td>8.0000</td>\n      <td>8.0000</td>\n    </tr>\n    <tr>\n      <th>media</th>\n      <td>15.5000</td>\n      <td>15.5000</td>\n      <td>15.5000</td>\n    </tr>\n    <tr>\n      <th>rango</th>\n      <td>7.0000</td>\n      <td>7.0000</td>\n      <td>21.0000</td>\n    </tr>\n    <tr>\n      <th>varianza</th>\n      <td>3.7500</td>\n      <td>4.2857</td>\n      <td>44.7500</td>\n    </tr>\n    <tr>\n      <th>desviación estándar</th>\n      <td>1.9365</td>\n      <td>2.0702</td>\n      <td>6.6895</td>\n    </tr>\n    <tr>\n      <th>Q1</th>\n      <td>14.5000</td>\n      <td>14.5000</td>\n      <td>10.0000</td>\n    </tr>\n    <tr>\n      <th>Q3</th>\n      <td>16.5000</td>\n      <td>16.5000</td>\n      <td>21.0000</td>\n    </tr>\n    <tr>\n      <th>IQR</th>\n      <td>2.0000</td>\n      <td>2.0000</td>\n      <td>11.0000</td>\n    </tr>\n    <tr>\n      <th>MAD</th>\n      <td>1.0000</td>\n      <td>1.0000</td>\n      <td>5.5000</td>\n    </tr>\n    <tr>\n      <th>CV</th>\n      <td>0.1249</td>\n      <td>0.1336</td>\n      <td>0.4316</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n### Ver la dispersión antes de resumirla\n\nUn gráfico de puntos conserva los ocho valores y deja visible que ambos equipos\ncomparten centro. El resumen numérico explica luego cuánto difieren.\n\n::: {#a2266432 .cell execution_count=2}\n``` {.python .cell-code}\nimport matplotlib.pyplot as plt\n\nfig, ax = plt.subplots(figsize=(8, 3.2))\nfor y, (nombre, valores, color) in enumerate([\n    (\"Regular\", regular, \"#2563eb\"),\n    (\"Irregular\", irregular, \"#d97706\"),\n]):\n    ax.scatter(valores, np.full(valores.size, y), s=75, color=color,\n               edgecolor=\"white\", linewidth=0.8, label=nombre)\n\nax.axvline(15.5, color=\"#334155\", linestyle=\"--\", linewidth=1.5,\n           label=\"Media común = 15.5\")\nax.set(yticks=[0, 1], yticklabels=[\"Regular\", \"Irregular\"],\n       xlabel=\"Tiempo de entrega (minutos)\",\n       title=\"Mismo centro, diferente dispersión\")\nax.grid(axis=\"x\", alpha=0.25)\nax.legend(frameon=False, loc=\"upper center\", ncol=3)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](2-4-variabilidad_files/figure-html/cell-3-output-1.png){width=758 height=298}\n:::\n:::\n\n\n### Sensibilidad frente a un extremo\n\nAhora conservamos siete tiempos y desplazamos solo el octavo. Esta simulación\ntraduce a código el experimento del laboratorio.\n\n::: {#30b9e49a .cell execution_count=3}\n``` {.python .cell-code}\nbase = np.array([12, 14, 15, 15, 16, 16, 17])\nfilas = []\nfor ultimo in range(17, 51):\n    x = np.append(base, ultimo)\n    resumen = resumen_variabilidad(x, \"poblacion\")\n    for medida in [\"desviación estándar\", \"IQR\", \"MAD\"]:\n        filas.append({\n            \"Último tiempo\": ultimo,\n            \"Medida\": medida,\n            \"Valor\": resumen[medida],\n        })\n\nsensibilidad = pd.DataFrame(filas)\nfig, ax = plt.subplots(figsize=(8, 4.2))\nfor medida, grupo in sensibilidad.groupby(\"Medida\", sort=False):\n    ax.plot(grupo[\"Último tiempo\"], grupo[\"Valor\"], linewidth=2,\n            label=medida)\nax.set(xlabel=\"Tiempo del octavo pedido (minutos)\",\n       ylabel=\"Dispersión (minutos)\",\n       title=\"Una observación extrema no mueve igual todas las medidas\")\nax.grid(alpha=0.25)\nax.legend(frameon=False)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](2-4-variabilidad_files/figure-html/cell-4-output-1.png){width=759 height=394}\n:::\n:::\n\n\nEl gráfico no declara que una medida sea siempre superior. Si interesa modelar\nvariación cuadrática alrededor de la media, la desviación estándar responde a\nla pregunta correcta. Si interesa el comportamiento central bajo\ncontaminación, IQR o MAD suelen describirlo mejor [@huber2009robust].\n\n## Guía de decisión\n\n| Pregunta | Medida principal | Unidades | Precaución |\n|:---|:---|:---|:---|\n| ¿Qué distancia hay entre extremos? | Rango | Originales | Usa solo dos valores y suele crecer con $n$. |\n| ¿Cuál es la variación cuadrática alrededor de la media? | Varianza | Cuadradas | Sensible a extremos; distinguir $N$ de $n-1$. |\n| ¿Cuál es la escala típica de variación alrededor de la media? | Desviación estándar | Originales | No es una distancia absoluta promedio. |\n| ¿Qué amplitud ocupa el 50% central? | IQR | Originales | Depende de la convención de cuartiles. |\n| ¿Cuál es la desviación central resistente? | MAD | Originales | Puede valer cero con muchos empates. |\n| ¿Qué tan grande es la dispersión respecto de la media? | CV | Ninguna | Exige escala de razón y media alejada de cero. |\n\nEn un análisis responsable, la elección nace de la pregunta y del mecanismo de\ndatos. No se selecciona la cifra más pequeña ni se elimina un extremo solo\npara reducir la variabilidad.\n\n## Puentes con minería de datos\n\n- **Estandarización.** Transformar $z_i=(x_i-\\bar{x})/s$ pone variables en una\n  escala comparable, pero transmite la sensibilidad de la media y de $s$ a\n  valores extremos. Una alternativa robusta usa mediana y MAD.\n- **$k$-means.** La inercia suma distancias cuadradas a centroides; por eso los\n  atributos de gran escala y los extremos pueden dominar la partición.\n- **Detección de anomalías.** Una regla basada en $z$ presupone que media y\n  desviación estándar resumen bien la distribución. Cercas de Tukey o puntajes\n  basados en MAD son alternativas exploratorias, no pruebas automáticas de\n  error.\n- **Validación de modelos.** La media de un error no basta: su variabilidad\n  entre particiones o periodos revela estabilidad. Debe distinguirse esa\n  dispersión del error estándar de la media.\n\n## Puente al caso BigMart\n\nEl capítulo [Medidas de variabilidad en Big Mart Sales](2-4-variabilidad_bigmart.qmd)\ntraslada la misma secuencia a ventas, precios, peso y visibilidad:\n\n1. visualizar primero la distribución y detectar unidades, asimetrías y\n   extremos;\n2. decidir si los registros se describen como colección observada o se usan\n   para inferir sobre una población;\n3. reportar una medida clásica y, cuando corresponda, una robusta;\n4. usar el CV solo en variables con escala de razón y media suficientemente\n   alejada de cero.\n\nLos nombres de las columnas cambian, pero no las preguntas que justifican cada\nmedida.\n\n## Ejercicios formativos\n\n1. **Cálculo manual.** Para $x=(6,8,8,10,13)$, calcule rango, media, suma de\n   cuadrados, varianza poblacional, varianza muestral y ambas desviaciones\n   estándar. Explique por qué las varianzas tienen unidades cuadradas.\n2. **Misma media.** Construya dos conjuntos de cinco tiempos con media 20: uno\n   con desviación estándar poblacional menor que 2 y otro mayor que 8. Dibuje\n   ambos en una recta antes de calcular.\n3. **Grados de libertad.** Proponga cuatro desviaciones respecto de una media.\n   Después de fijar tres, determine la cuarta y explique por qué solo tres son\n   libres.\n4. **Cuartiles.** Para $(2,3,5,7,8,11,14,30)$ calcule $Q_1$, $Q_3$, IQR y las\n   cercas de Tukey con el método de medianas de las mitades. ¿El 30 es un\n   candidato atípico? ¿Eso basta para borrarlo?\n5. **Resistencia.** Reemplace el 30 del ejercicio anterior por 300. Compare\n   rango, desviación estándar poblacional, IQR y MAD antes y después. Explique\n   por qué no todas cambian en la misma proporción.\n6. **Escala relativa.** Dos máquinas llenan botellas. La máquina A tiene media\n   250 ml y $s=5$ ml; la B, media 1,000 ml y $s=12$ ml. Compare su variación\n   absoluta y relativa. ¿Cuál es más estable según cada criterio?\n7. **Unidades y origen.** Demuestre con código que convertir los tiempos del\n   Equipo Regular a segundos multiplica $s^2$ por $60^2$, multiplica $s$ por\n   60 y deja igual el CV. Explique por qué sumar 273.15 a temperaturas Celsius\n   cambia el CV aunque no cambie su desviación estándar.\n8. **Decisión analítica.** Una distribución de tiempos tiene fuerte asimetría\n   derecha y varios retrasos reales. Diseñe un reporte con al menos un gráfico,\n   una medida clásica y una robusta. Justifique qué información conserva cada\n   elemento.\n\n## Referencias {.unnumbered}\n\n::: {#refs}\n:::\n\n[^cuantitativa]: Una **variable cuantitativa** representa cantidades para las que las diferencias numéricas tienen significado. No toda etiqueta codificada con números es cuantitativa: asignar 1, 2 y 3 a tres colores no convierte sus diferencias en distancias.\n[^estadistico-orden]: $x_{(i)}$ denota el dato que ocupa la posición $i$ después de ordenar. Los paréntesis distinguen una posición ordenada de la observación original $x_i$.\n[^poblacion]: La **población** es el conjunto completo sobre el que se formula una afirmación. No tiene que ser enorme: los ocho pedidos de un turno son una población si la pregunta se limita exactamente a ese turno.\n[^parametro]: Un **parámetro** es una característica fija pero posiblemente desconocida de una población, como $\\mu$ o $\\sigma^2$. Un **estadístico** se calcula con una muestra, como $\\bar{x}$ o $s^2$, y cambia de una muestra a otra.\n[^insesgado]: Un estimador es **insesgado** si, al imaginar todas las muestras posibles obtenidas bajo el mismo diseño, el promedio de sus estimaciones coincide con el parámetro. No garantiza que una muestra particular produzca el valor exacto.\n[^gl]: Los **grados de libertad** cuentan cuántas cantidades pueden variar independientemente después de imponer restricciones. Aquí hay $n$ desviaciones y una restricción lineal —que sumen cero—, por lo que quedan $n-1$.\n[^normal]: La **distribución normal** es un modelo continuo, simétrico y con forma de campana determinado por su media y varianza. La regla 68% es una propiedad de ese modelo, no una definición de desviación estándar.\n[^robusta]: Una medida es **robusta** si una fracción pequeña de observaciones atípicas no puede alterarla arbitrariamente. Robustez no significa insensibilidad total ni garantiza que el dato extremo sea erróneo.\n[^cuartiles]: Existen varias definiciones válidas de cuartiles porque una muestra finita no determina de manera única los percentiles entre posiciones. El software puede interpolar y producir valores distintos. Debe declararse el método al reproducir resultados [@hyndman1996quantiles].\n[^razon]: Una **escala de razón** posee un cero que significa ausencia de la cantidad, por lo que afirmaciones como “el doble” tienen sentido. Kelvin, masa y duración la poseen; Celsius no, porque su cero es un punto convencional.\n[^error-estandar]: El **error estándar** es la desviación estándar de la distribución muestral de un estimador. Cuantifica incertidumbre inferencial, no la dispersión individual de los datos.\n\n",
    "supporting": [
      "2-4-variabilidad_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}