project:
  type: website

website:
  title: "Mi portafolio de datos"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - analisis.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true