{
  "hash": "f560ed4802ac98a10f6cbe56464ad6fe",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Medidas de heterogeneidad en Big Mart Sales\"\nauthor: \"Diego Villalba\"\ndate: today\nlang: es\nnumber-sections: true\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: true\n    code-tools: true\n    code-summary: \"Mostrar código\"\n    page-layout: full\n  pdf:\n    toc: true\njupyter: python3\nbibliography: referencias_eda.bib\n---\n\n<!-- TODO: MENCIONAR QUE PARA UNA MEJRO COMPARACIÓN EN MEDIDAS DE HETEOOGENEIDAD ES NECESARIO COLOCAR LOS VALORES MAXIMOS A UNA COSTADO. -->\n\n\n## Introducción\n\n::: {.callout-tip appearance=\"minimal\"}\nEste caso aplica la diversidad categórica y la comparación entre grupos desarrolladas en [Medidas de heterogeneidad](2-6-heterogeneidad.qmd).\n:::\n\nDespués de estudiar la localización, la variabilidad y la forma de las distribuciones, el análisis exploratorio de datos debe avanzar hacia una pregunta más estructural: **¿el comportamiento observado es homogéneo en toda la población o cambia de manera importante entre grupos?**. Esta cuestión introduce el concepto de **heterogeneidad**, una dimensión central del EDA cuando el dataset contiene segmentaciones naturales, como categorías de producto, tipos de tienda, tamaños de outlet o ubicaciones geográficas.\n\nEn términos estadísticos, la heterogeneidad alude a la existencia de diferencias sistemáticas entre subpoblaciones. Tales diferencias pueden expresarse en el centro de la distribución, en su dispersión, en su forma o incluso en la presencia diferencial de valores extremos. En un problema de negocio como BigMart, detectar heterogeneidad es indispensable, pues permite identificar si ciertos tipos de tiendas venden consistentemente más, si algunas categorías presentan patrones de ventas más variables, o si la estructura comercial cambia según el entorno del outlet.\n\nEn este capítulo se trabaja la heterogeneidad como una extensión natural del análisis univariado. La idea principal es que una variable numérica no debe interpretarse de manera aislada, sino también en relación con variables categóricas relevantes.\n\n::: {.callout-note appearance=\"minimal\"}\n**Definición operativa.** La heterogeneidad aparece cuando la distribución de ventas cambia entre subgrupos o cuando la composición categórica presenta diversidad relevante [@shannon1948mathematical; @simpson1949measurement].\n:::\n\n## Preparación del entorno\n\nTrabajaremos con el siguiente [dataset BigMart](../../data/bigmart_sales.csv), usando Python, pandas, NumPy y Plotly.\n\n::: {.cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport plotly.express as px\nimport plotly.graph_objects as go\n\nDATA_PATH = \"../../data/bigmart_sales.csv\"\ndf = pd.read_csv(DATA_PATH)\ndf.head()\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Item_Identifier</th>\n      <th>Item_Weight</th>\n      <th>Item_Fat_Content</th>\n      <th>Item_Visibility</th>\n      <th>Item_Type</th>\n      <th>Item_MRP</th>\n      <th>Outlet_Identifier</th>\n      <th>Outlet_Establishment_Year</th>\n      <th>Outlet_Size</th>\n      <th>Outlet_Location_Type</th>\n      <th>Outlet_Type</th>\n      <th>Item_Outlet_Sales</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>FDA15</td>\n      <td>9.30</td>\n      <td>Low Fat</td>\n      <td>0.016047</td>\n      <td>Dairy</td>\n      <td>249.8092</td>\n      <td>OUT049</td>\n      <td>1999</td>\n      <td>Medium</td>\n      <td>Tier 1</td>\n      <td>Supermarket Type1</td>\n      <td>3735.1380</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>DRC01</td>\n      <td>5.92</td>\n      <td>Regular</td>\n      <td>0.019278</td>\n      <td>Soft Drinks</td>\n      <td>48.2692</td>\n      <td>OUT018</td>\n      <td>2009</td>\n      <td>Medium</td>\n      <td>Tier 3</td>\n      <td>Supermarket Type2</td>\n      <td>443.4228</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>FDN15</td>\n      <td>17.50</td>\n      <td>Low Fat</td>\n      <td>0.016760</td>\n      <td>Meat</td>\n      <td>141.6180</td>\n      <td>OUT049</td>\n      <td>1999</td>\n      <td>Medium</td>\n      <td>Tier 1</td>\n      <td>Supermarket Type1</td>\n      <td>2097.2700</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>FDX07</td>\n      <td>19.20</td>\n      <td>Regular</td>\n      <td>0.000000</td>\n      <td>Fruits and Vegetables</td>\n      <td>182.0950</td>\n      <td>OUT010</td>\n      <td>1998</td>\n      <td>NaN</td>\n      <td>Tier 3</td>\n      <td>Grocery Store</td>\n      <td>732.3800</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>NCD19</td>\n      <td>8.93</td>\n      <td>Low Fat</td>\n      <td>0.000000</td>\n      <td>Household</td>\n      <td>53.8614</td>\n      <td>OUT013</td>\n      <td>1987</td>\n      <td>High</td>\n      <td>Tier 3</td>\n      <td>Supermarket Type1</td>\n      <td>994.7052</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nConviene verificar las variables categóricas y numéricas del conjunto de datos.\n\n::: {.cell execution_count=2}\n``` {.python .cell-code}\ndf.info()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 8523 entries, 0 to 8522\nData columns (total 12 columns):\n #   Column                     Non-Null Count  Dtype  \n---  ------                     --------------  -----  \n 0   Item_Identifier            8523 non-null   object \n 1   Item_Weight                7060 non-null   float64\n 2   Item_Fat_Content           8523 non-null   object \n 3   Item_Visibility            8523 non-null   float64\n 4   Item_Type                  8523 non-null   object \n 5   Item_MRP                   8523 non-null   float64\n 6   Outlet_Identifier          8523 non-null   object \n 7   Outlet_Establishment_Year  8523 non-null   int64  \n 8   Outlet_Size                6113 non-null   object \n 9   Outlet_Location_Type       8523 non-null   object \n 10  Outlet_Type                8523 non-null   object \n 11  Item_Outlet_Sales          8523 non-null   float64\ndtypes: float64(4), int64(1), object(7)\nmemory usage: 799.2+ KB\n```\n:::\n:::\n\n\n::: {.cell execution_count=3}\n``` {.python .cell-code}\nnum_cols = df.select_dtypes(include=np.number).columns.tolist()\ncat_cols = df.select_dtypes(exclude=np.number).columns.tolist()\n\nnum_cols, cat_cols\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```\n(['Item_Weight',\n  'Item_Visibility',\n  'Item_MRP',\n  'Outlet_Establishment_Year',\n  'Item_Outlet_Sales'],\n ['Item_Identifier',\n  'Item_Fat_Content',\n  'Item_Type',\n  'Outlet_Identifier',\n  'Outlet_Size',\n  'Outlet_Location_Type',\n  'Outlet_Type'])\n```\n:::\n:::\n\n\n## Fundamentos teóricos\n\nLa heterogeneidad puede analizarse desde varias perspectivas. Si $Y$ es una variable numérica de interés y $G$ una variable categórica que define grupos, pueden estudiarse diferencias en:\n\n### Centro por grupo\n\nSe comparan medidas como:\n\n$$\n\\bar{y}_g = \\frac{1}{n_g}\\sum_{i \\in g} y_i,\n$$\n\nasí como la mediana y otros cuantiles dentro de cada grupo $g$.\n\n### Dispersión por grupo\n\nLa variabilidad interna de cada subpoblación puede resumirse mediante la desviación estándar, el rango intercuartílico o el coeficiente de variación. Dos grupos pueden tener medias semejantes y, sin embargo, diferir de forma sustancial en estabilidad o consistencia.\n\n### Forma por grupo\n\nLa heterogeneidad también puede aparecer en la asimetría o en la presencia de colas pesadas. Algunos grupos pueden concentrarse en rangos estrechos y otros exhibir ventas con distribución muy extendida.\n\n### Participación relativa de cada grupo\n\nFinalmente, también es útil estudiar cuánto contribuye cada grupo al total de observaciones o al total de ventas. Esta dimensión conecta la heterogeneidad con el estudio posterior de la concentración.\n\n## Variable objetivo y grupos de interés\n\nEn este capítulo tomaremos nuevamente como variable principal a $\\texttt{Item\\_Outlet\\_Sales}$. Como ejes de segmentación se consideran, al menos, las siguientes variables categóricas:\n\n- $\\texttt{Outlet\\_Type}$,\n- $\\texttt{Outlet\\_Size}$,\n- $\\texttt{Outlet\\_Location\\_Type}$,\n- $\\texttt{Item\\_Type}$.\n\nAntes de comparar grupos, es útil revisar su tamaño.\n\n::: {.cell execution_count=4}\n``` {.python .cell-code}\nfor col in [\"Outlet_Type\", \"Outlet_Size\", \"Outlet_Location_Type\", \"Item_Type\"]:\n    print(f\"\\n{col}\")\n    print(df[col].value_counts(dropna=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nOutlet_Type\nOutlet_Type\nSupermarket Type1    5577\nGrocery Store        1083\nSupermarket Type3     935\nSupermarket Type2     928\nName: count, dtype: int64\n\nOutlet_Size\nOutlet_Size\nMedium    2793\nNaN       2410\nSmall     2388\nHigh       932\nName: count, dtype: int64\n\nOutlet_Location_Type\nOutlet_Location_Type\nTier 3    3350\nTier 2    2785\nTier 1    2388\nName: count, dtype: int64\n\nItem_Type\nItem_Type\nFruits and Vegetables    1232\nSnack Foods              1200\nHousehold                 910\nFrozen Foods              856\nDairy                     682\nCanned                    649\nBaking Goods              648\nHealth and Hygiene        520\nSoft Drinks               445\nMeat                      425\nBreads                    251\nHard Drinks               214\nOthers                    169\nStarchy Foods             148\nBreakfast                 110\nSeafood                    64\nName: count, dtype: int64\n```\n:::\n:::\n\n\nEste paso es importante porque la interpretación de diferencias entre grupos debe considerar el tamaño muestral. Un grupo muy pequeño puede mostrar estadísticas inestables o aparentes extremos debidos a pocos casos.\n\n## Heterogeneidad por tipo de outlet\n\nComenzamos con una variable de alto interés de negocio: $\\texttt{Outlet\\_Type}$.\n\n::: {.cell execution_count=5}\n``` {.python .cell-code}\noutlet_type_summary = (\n    df.groupby(\"Outlet_Type\")[\"Item_Outlet_Sales\"]\n      .agg([\"count\", \"mean\", \"median\", \"std\", \"min\", \"max\"])\n      .sort_values(\"mean\", ascending=False)\n)\noutlet_type_summary\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>count</th>\n      <th>mean</th>\n      <th>median</th>\n      <th>std</th>\n      <th>min</th>\n      <th>max</th>\n    </tr>\n    <tr>\n      <th>Outlet_Type</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Supermarket Type3</th>\n      <td>935</td>\n      <td>3694.038558</td>\n      <td>3364.9532</td>\n      <td>2127.760054</td>\n      <td>241.6854</td>\n      <td>13086.9648</td>\n    </tr>\n    <tr>\n      <th>Supermarket Type1</th>\n      <td>5577</td>\n      <td>2316.181148</td>\n      <td>1990.7420</td>\n      <td>1515.965558</td>\n      <td>73.2380</td>\n      <td>10256.6490</td>\n    </tr>\n    <tr>\n      <th>Supermarket Type2</th>\n      <td>928</td>\n      <td>1995.498739</td>\n      <td>1655.1788</td>\n      <td>1375.932889</td>\n      <td>69.2432</td>\n      <td>6768.5228</td>\n    </tr>\n    <tr>\n      <th>Grocery Store</th>\n      <td>1083</td>\n      <td>339.828500</td>\n      <td>256.9988</td>\n      <td>260.851582</td>\n      <td>33.2900</td>\n      <td>1775.6886</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {.cell execution_count=6}\n``` {.python .cell-code}\nfig = px.box(\n    df,\n    x=\"Outlet_Type\",\n    y=\"Item_Outlet_Sales\",\n    color=\"Outlet_Type\",\n    title=\"Distribución de ventas por tipo de outlet\"\n)\nfig.update_layout(showlegend=False)\nfig.show()\n```\n\n::: {.cell-output .cell-output-display}\n```\nUnable to display output for mime type(s): text/html\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```\nUnable to display output for mime type(s): text/html\n```\n:::\n:::\n\n\n::: {.cell execution_count=7}\n``` {.python .cell-code}\nfig = px.bar(\n    outlet_type_summary.reset_index(),\n    x=\"Outlet_Type\",\n    y=\"mean\",\n    error_y=\"std\",\n    title=\"Media y desviación estándar de ventas por tipo de outlet\",\n    text_auto=True\n)\nfig.show()\n```\n\n::: {.cell-output .cell-output-display}\n```\nUnable to display output for mime type(s): text/html\n```\n:::\n:::\n\n\nA partir de este análisis se observa una **heterogeneidad clara por tipo de outlet**, lo que indica que `Outlet_Type` sí está asociado con diferencias relevantes en el nivel de ventas.\n\nEn primer lugar, `Supermarket Type3` destaca como el segmento con **mayor nivel de ventas**, tanto en la **media** (**3694.039**) como en la **mediana** (**3364.953**). Además, su boxplot se ubica claramente por encima del resto, lo que sugiere un desempeño consistentemente superior.\n\nEn segundo lugar, `Supermarket Type1` y `Supermarket Type2` presentan niveles de ventas **intermedios**, aunque `Supermarket Type1` muestra valores centrales algo mayores (**media = 2316.181**, **mediana = 1990.742**) que `Supermarket Type2` (**media = 1995.499**, **mediana = 1655.179**). Esto sugiere que, aunque ambos formatos son comparables, no tienen exactamente el mismo comportamiento comercial.\n\nPor otro lado, `Grocery Store` aparece como el grupo con **menor nivel de ventas**, con una **media de 339.829** y una **mediana de 256.999**, muy por debajo de los supermercados. Esto revela una diferencia estructural importante entre este tipo de outlet y los demás.\n\nEn términos de **variabilidad**, `Supermarket Type3` también presenta la mayor dispersión (**std = 2127.760**), lo que indica que no solo vende más, sino que sus ventas son más heterogéneas. `Supermarket Type1` y `Supermarket Type2` también muestran dispersión considerable, mientras que `Grocery Store` tiene una variabilidad mucho menor en términos absolutos (**std = 260.852**), coherente con su escala de ventas más baja.\n\nLos boxplots también muestran la presencia de **valores atípicos** en todos los grupos, especialmente en los supermercados. Esto sugiere que dentro de cada tipo de outlet existen productos o combinaciones producto-tienda con desempeños excepcionalmente altos.\n\nEn conjunto, este resultado tiene varias implicaciones para el EDA:\n\n- `Outlet_Type` debe considerarse una **variable clave de segmentación**;\n- no conviene analizar `Item_Outlet_Sales` como si proviniera de una sola población homogénea;\n- es recomendable profundizar con comparaciones entre grupos, distribuciones segmentadas y medidas robustas;\n- en etapas posteriores, `Outlet_Type` probablemente será una variable explicativa importante en cualquier análisis predictivo o inferencial.\n\nEn síntesis, el análisis muestra que el tipo de outlet introduce diferencias sustanciales tanto en el **nivel** como en la **dispersión** de las ventas, por lo que esta variable merece un lugar central dentro del EDA.\n\n## Heterogeneidad por tamaño del outlet\n\nEl tamaño del outlet puede influir tanto en el volumen típico de ventas como en la dispersión observada.\n\n::: {.cell execution_count=8}\n``` {.python .cell-code}\noutlet_size_summary = (\n    df.groupby(\"Outlet_Size\")[\"Item_Outlet_Sales\"]\n      .agg([\"count\", \"mean\", \"median\", \"std\"])\n      .sort_values(\"mean\", ascending=False)\n)\noutlet_size_summary\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>count</th>\n      <th>mean</th>\n      <th>median</th>\n      <th>std</th>\n    </tr>\n    <tr>\n      <th>Outlet_Size</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Medium</th>\n      <td>2793</td>\n      <td>2681.603542</td>\n      <td>2251.0698</td>\n      <td>1855.210528</td>\n    </tr>\n    <tr>\n      <th>High</th>\n      <td>932</td>\n      <td>2298.995256</td>\n      <td>2050.6640</td>\n      <td>1533.531664</td>\n    </tr>\n    <tr>\n      <th>Small</th>\n      <td>2388</td>\n      <td>1912.149161</td>\n      <td>1544.6560</td>\n      <td>1582.370364</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {.cell execution_count=9}\n``` {.python .cell-code}\nfig = px.violin(\n    df,\n    x=\"Outlet_Size\",\n    y=\"Item_Outlet_Sales\",\n    color=\"Outlet_Size\",\n    box=True,\n    points=False,\n    title=\"Ventas por tamaño de outlet\"\n)\nfig.update_layout(showlegend=False)\nfig.show()\n```\n\n::: {.cell-output .cell-output-display}\n```\nUnable to display output for mime type(s): text/html\n```\n:::\n:::\n\n\nLos violin plots son especialmente útiles aquí porque combinan información sobre dispersión y forma dentro de cada grupo. Si dos grupos tienen medianas parecidas pero densidades internas distintas, la heterogeneidad va más allá del simple promedio.\n\nEste análisis también muestra **heterogeneidad por tamaño del outlet**, aunque con diferencias menos extremas que las observadas por `Outlet_Type`. Aun así, `Outlet_Size` aporta información relevante para el EDA porque parece asociarse tanto con el nivel típico de ventas como con su dispersión.\n\nEn primer lugar, los outlets de tamaño `Medium` presentan el mayor nivel de ventas, con una **media de 2681.604** y una **mediana de 2251.070**. Les siguen los outlets `High`, con **media = 2298.995** y **mediana = 2050.664`, mientras que los outlets `Small` muestran los valores más bajos (**media = 1912.149**, **mediana = 1544.656**). Esto sugiere que el tamaño del outlet sí introduce diferencias sistemáticas en el comportamiento comercial.\n\nEn términos de dispersión, `Medium` también presenta la mayor variabilidad (**std = 1855.211**), seguido por `Small` (**std = 1582.370**) y `High` (**std = 1533.532**). Los violin plots refuerzan esta idea al mostrar que no solo cambian los niveles centrales, sino también la forma interna de la distribución en cada grupo.\n\nPara el EDA, esto tiene varias consecuencias:\n\n- `Outlet_Size` debe considerarse una **variable relevante de segmentación**, ya que las ventas no parecen distribuirse igual entre tamaños de tienda;\n- no basta con comparar solo promedios: la forma de los violines sugiere diferencias en **concentración, dispersión y densidad interna** entre grupos;\n- conviene cruzar `Outlet_Size` con otras variables categóricas, especialmente `Outlet_Type`, para ver si parte de esta heterogeneidad se explica por la combinación entre ambas;\n- en análisis posteriores, `Outlet_Size` puede funcionar como una **variable explicativa útil**, aunque probablemente con menor poder discriminante que `Outlet_Type`;\n- dado que esta variable tenía valores faltantes en etapas previas, su papel analítico resulta todavía más importante, porque ayuda a decidir si conviene imputarla y preservarla en lugar de descartarla.\n\nEn síntesis, el tamaño del outlet no solo afecta el nivel típico de ventas, sino también la estructura de su distribución. Por ello, en el EDA conviene tratarlo como un factor de heterogeneidad relevante y no como una simple característica secundaria del establecimiento.\n\n## Heterogeneidad por ubicación del outlet\n\nOtra dimensión natural del análisis es $\\texttt{Outlet\\_Location\\_Type}$, que puede reflejar diferencias territoriales o de mercado.\n\n::: {.cell execution_count=10}\n``` {.python .cell-code}\nlocation_summary = (\n    df.groupby(\"Outlet_Location_Type\")[\"Item_Outlet_Sales\"]\n      .agg([\"count\", \"mean\", \"median\", \"std\"])\n      .sort_values(\"mean\", ascending=False)\n)\nlocation_summary\n```\n\n::: {.cell-output .cell-output-display execution_count=10}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>count</th>\n      <th>mean</th>\n      <th>median</th>\n      <th>std</th>\n    </tr>\n    <tr>\n      <th>Outlet_Location_Type</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Tier 2</th>\n      <td>2785</td>\n      <td>2323.990559</td>\n      <td>2004.0580</td>\n      <td>1520.543543</td>\n    </tr>\n    <tr>\n      <th>Tier 3</th>\n      <td>3350</td>\n      <td>2279.627651</td>\n      <td>1812.3076</td>\n      <td>1912.451333</td>\n    </tr>\n    <tr>\n      <th>Tier 1</th>\n      <td>2388</td>\n      <td>1876.909159</td>\n      <td>1487.3972</td>\n      <td>1561.649293</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {.cell execution_count=11}\n``` {.python .cell-code}\nfig = px.box(\n    df,\n    x=\"Outlet_Location_Type\",\n    y=\"Item_Outlet_Sales\",\n    color=\"Outlet_Location_Type\",\n    title=\"Ventas por tipo de localización del outlet\"\n)\nfig.update_layout(showlegend=False)\nfig.show()\n```\n\n::: {.cell-output .cell-output-display}\n```\nUnable to display output for mime type(s): text/html\n```\n:::\n:::\n\n\nEl análisis por `Outlet_Location_Type` revela también **heterogeneidad territorial en las ventas**, aunque con diferencias más moderadas que las observadas por tipo de outlet.\n\nEn términos de nivel central, `Tier 2` presenta el mayor promedio (**mean = 2323.991**, **median = 2004.058**), seguido muy de cerca por `Tier 3` (**mean = 2279.628**, **median = 1812.308**). En contraste, `Tier 1` muestra los valores más bajos (**mean = 1876.909**, **median = 1487.397**), lo que sugiere que las ventas tienden a ser menores en este tipo de localización.\n\nEn cuanto a la dispersión, `Tier 3` presenta la mayor variabilidad (**std = 1912.451**), lo que indica una mayor heterogeneidad en el desempeño de ventas dentro de este grupo. Los boxplots también muestran la presencia de **valores extremos** en todas las ubicaciones, especialmente en `Tier 3`.\n\nPara el EDA, esto sugiere que:\n\n- `Outlet_Location_Type` introduce **diferencias territoriales en el nivel de ventas**;\n- `Tier 2` y `Tier 3` tienen comportamientos relativamente similares en el centro de la distribución, aunque `Tier 3` muestra mayor dispersión;\n- `Tier 1` parece corresponder a ubicaciones con **menor desempeño promedio**;\n- conviene explorar **interacciones entre ubicación, tipo y tamaño del outlet**, ya que parte de la heterogeneidad observada podría explicarse por la combinación de estas variables.\n\nEn síntesis, la localización del outlet añade otra dimensión de segmentación en el EDA y refuerza la idea de que las ventas no provienen de una población homogénea, sino de **subgrupos con comportamientos distintos**.\n\n## Heterogeneidad por tipo de producto\n\nLa variable $\\texttt{Item\\_Type}$ suele contener más niveles que las anteriores, por lo que conviene resumir y ordenar cuidadosamente la información.\n\n::: {.cell execution_count=12}\n``` {.python .cell-code}\nitem_type_summary = (\n    df.groupby(\"Item_Type\")[\"Item_Outlet_Sales\"]\n      .agg([\"count\", \"mean\", \"median\", \"std\"])\n      .sort_values(\"mean\", ascending=False)\n)\nitem_type_summary.head(10)\n```\n\n::: {.cell-output .cell-output-display execution_count=12}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>count</th>\n      <th>mean</th>\n      <th>median</th>\n      <th>std</th>\n    </tr>\n    <tr>\n      <th>Item_Type</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Starchy Foods</th>\n      <td>148</td>\n      <td>2374.332773</td>\n      <td>1968.1048</td>\n      <td>1773.945328</td>\n    </tr>\n    <tr>\n      <th>Seafood</th>\n      <td>64</td>\n      <td>2326.065928</td>\n      <td>2055.3246</td>\n      <td>1842.988719</td>\n    </tr>\n    <tr>\n      <th>Fruits and Vegetables</th>\n      <td>1232</td>\n      <td>2289.009592</td>\n      <td>1830.9500</td>\n      <td>1799.503459</td>\n    </tr>\n    <tr>\n      <th>Snack Foods</th>\n      <td>1200</td>\n      <td>2277.321739</td>\n      <td>1944.1360</td>\n      <td>1705.121755</td>\n    </tr>\n    <tr>\n      <th>Household</th>\n      <td>910</td>\n      <td>2258.784300</td>\n      <td>1981.4208</td>\n      <td>1692.245757</td>\n    </tr>\n    <tr>\n      <th>Dairy</th>\n      <td>682</td>\n      <td>2232.542597</td>\n      <td>1650.8511</td>\n      <td>1884.404698</td>\n    </tr>\n    <tr>\n      <th>Canned</th>\n      <td>649</td>\n      <td>2225.194904</td>\n      <td>1860.2452</td>\n      <td>1645.235638</td>\n    </tr>\n    <tr>\n      <th>Breads</th>\n      <td>251</td>\n      <td>2204.132226</td>\n      <td>1860.2452</td>\n      <td>1644.235914</td>\n    </tr>\n    <tr>\n      <th>Meat</th>\n      <td>425</td>\n      <td>2158.977911</td>\n      <td>1829.6184</td>\n      <td>1695.231081</td>\n    </tr>\n    <tr>\n      <th>Hard Drinks</th>\n      <td>214</td>\n      <td>2139.221622</td>\n      <td>1816.6353</td>\n      <td>1606.191587</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {.cell execution_count=13}\n``` {.python .cell-code}\nfig = px.bar(\n    item_type_summary.reset_index(),\n    x=\"mean\",\n    y=item_type_summary.reset_index()[\"Item_Type\"],\n    orientation=\"h\",\n    title=\"Media de ventas por tipo de producto\",\n    labels={\"mean\": \"Media de ventas\", \"y\": \"Tipo de producto\"}\n)\nfig.show()\n```\n\n::: {.cell-output .cell-output-display}\n```\nUnable to display output for mime type(s): text/html\n```\n:::\n:::\n\n\n::: {.cell execution_count=14}\n``` {.python .cell-code}\ntop_item_types = item_type_summary.head(8).index.tolist()\nfig = px.box(\n    df[df[\"Item_Type\"].isin(top_item_types)],\n    x=\"Item_Type\",\n    y=\"Item_Outlet_Sales\",\n    color=\"Item_Type\",\n    title=\"Distribución de ventas en los tipos de producto con mayor media\"\n)\nfig.update_layout(showlegend=False)\nfig.show()\n```\n\n::: {.cell-output .cell-output-display}\n```\nUnable to display output for mime type(s): text/html\n```\n:::\n:::\n\n\nEl análisis por `Item_Type` muestra que también existe **heterogeneidad por categoría de producto**, aunque menos marcada que la observada por `Outlet_Type`. Aun así, las diferencias son suficientes para justificar una exploración segmentada.\n\nEn términos de promedio, las categorías con mayores ventas son `Starchy Foods` (**mean = 2374.333**), `Seafood` (**mean = 2326.066**) y `Fruits and Vegetables` (**mean = 2289.010**). Sin embargo, estas dos primeras tienen tamaños muestrales mucho menores (**148** y **64** observaciones, respectivamente), por lo que sus medias deben interpretarse con más cautela.\n\nEntre las categorías con mayor presencia en el dataset, `Fruits and Vegetables` (**1232** casos), `Snack Foods` (**1200**) y `Household` (**910**) combinan **niveles altos de ventas** con una base de observaciones más sólida, lo que las vuelve especialmente relevantes para el EDA.\n\nLos boxplots sugieren además que estas categorías no solo difieren en el nivel central, sino también en su **dispersión** y en la presencia de **valores extremos**. Por ejemplo, `Household`, `Fruits and Vegetables` y `Snack Foods` muestran colas superiores amplias y varios valores altos, lo que sugiere comportamientos heterogéneos dentro de cada tipo de producto.\n\nPara el EDA, esto tiene varias implicaciones:\n\n- `Item_Type` debe considerarse una **variable de segmentación importante**;\n- conviene distinguir entre categorías con **muchas observaciones** y categorías con **poca representación**, para no sobredimensionar diferencias basadas en muestras pequeñas;\n- resulta útil cruzar `Item_Type` con variables como `Outlet_Type` u `Outlet_Size`, ya que parte de la heterogeneidad podría depender de la interacción entre producto y tienda;\n- en etapas posteriores, `Item_Type` puede aportar valor explicativo, pero probablemente con efecto desigual según la categoría.\n\nEn síntesis, el tipo de producto introduce diferencias reales en las ventas, pero su interpretación debe combinar **nivel de ventas**, **dispersión** y **tamaño muestral** para evitar conclusiones apresuradas.\n\n## Tablas comparativas con múltiples indicadores\n\nUna forma útil de sistematizar la heterogeneidad es construir tablas resumen que integren varias medidas por grupo.\n\n::: {.cell execution_count=15}\n``` {.python .cell-code}\ndef group_profile(df, group_col, target=\"Item_Outlet_Sales\"):\n    out = (\n        df.groupby(group_col)[target]\n          .agg(\n              n=\"count\",\n              media=\"mean\",\n              mediana=\"median\",\n              desviacion=\"std\",\n              q1=lambda x: x.quantile(0.25),\n              q3=lambda x: x.quantile(0.75)\n          )\n          .reset_index()\n    )\n    out[\"iqr\"] = out[\"q3\"] - out[\"q1\"]\n    out[\"cv\"] = out[\"desviacion\"] / out[\"media\"]\n    return out.sort_values(\"media\", ascending=False)\n\nprofile_outlet_type = group_profile(df, \"Outlet_Type\")\nprofile_outlet_type\n```\n\n::: {.cell-output .cell-output-display execution_count=15}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Outlet_Type</th>\n      <th>n</th>\n      <th>media</th>\n      <th>mediana</th>\n      <th>desviacion</th>\n      <th>q1</th>\n      <th>q3</th>\n      <th>iqr</th>\n      <th>cv</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>3</th>\n      <td>Supermarket Type3</td>\n      <td>935</td>\n      <td>3694.038558</td>\n      <td>3364.9532</td>\n      <td>2127.760054</td>\n      <td>2044.33890</td>\n      <td>4975.52340</td>\n      <td>2931.1845</td>\n      <td>0.575998</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Supermarket Type1</td>\n      <td>5577</td>\n      <td>2316.181148</td>\n      <td>1990.7420</td>\n      <td>1515.965558</td>\n      <td>1151.16820</td>\n      <td>3135.91800</td>\n      <td>1984.7498</td>\n      <td>0.654511</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Supermarket Type2</td>\n      <td>928</td>\n      <td>1995.498739</td>\n      <td>1655.1788</td>\n      <td>1375.932889</td>\n      <td>981.55565</td>\n      <td>2702.64865</td>\n      <td>1721.0930</td>\n      <td>0.689518</td>\n    </tr>\n    <tr>\n      <th>0</th>\n      <td>Grocery Store</td>\n      <td>1083</td>\n      <td>339.828500</td>\n      <td>256.9988</td>\n      <td>260.851582</td>\n      <td>153.79980</td>\n      <td>458.73620</td>\n      <td>304.9364</td>\n      <td>0.767598</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {.cell execution_count=16}\n``` {.python .cell-code}\nprofile_location = group_profile(df, \"Outlet_Location_Type\")\nprofile_location\n```\n\n::: {.cell-output .cell-output-display execution_count=16}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Outlet_Location_Type</th>\n      <th>n</th>\n      <th>media</th>\n      <th>mediana</th>\n      <th>desviacion</th>\n      <th>q1</th>\n      <th>q3</th>\n      <th>iqr</th>\n      <th>cv</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1</th>\n      <td>Tier 2</td>\n      <td>2785</td>\n      <td>2323.990559</td>\n      <td>2004.0580</td>\n      <td>1520.543543</td>\n      <td>1171.80800</td>\n      <td>3110.6176</td>\n      <td>1938.80960</td>\n      <td>0.654281</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Tier 3</td>\n      <td>3350</td>\n      <td>2279.627651</td>\n      <td>1812.3076</td>\n      <td>1912.451333</td>\n      <td>731.38130</td>\n      <td>3307.6944</td>\n      <td>2576.31310</td>\n      <td>0.838931</td>\n    </tr>\n    <tr>\n      <th>0</th>\n      <td>Tier 1</td>\n      <td>2388</td>\n      <td>1876.909159</td>\n      <td>1487.3972</td>\n      <td>1561.649293</td>\n      <td>593.72715</td>\n      <td>2803.0180</td>\n      <td>2209.29085</td>\n      <td>0.832032</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nEstas tablas permiten pasar de una observación visual a una descripción más precisa: no solo se identifican grupos “más altos” o “más bajos”, sino también grupos más o menos variables y con distinta estabilidad relativa.\n\n## Heterogeneidad cruzada\n\nEn muchos problemas reales, la segmentación relevante no depende de una sola variable categórica. Una comparación cruzada, por ejemplo entre tipo de outlet y localización, ayuda a identificar patrones más finos.\n\n::: {.cell execution_count=17}\n``` {.python .cell-code}\npivot_mean = pd.pivot_table(\n    df,\n    values=\"Item_Outlet_Sales\",\n    index=\"Outlet_Type\",\n    columns=\"Outlet_Location_Type\",\n    aggfunc=\"mean\"\n)\npivot_mean\n```\n\n::: {.cell-output .cell-output-display execution_count=17}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th>Outlet_Location_Type</th>\n      <th>Tier 1</th>\n      <th>Tier 2</th>\n      <th>Tier 3</th>\n    </tr>\n    <tr>\n      <th>Outlet_Type</th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Grocery Store</th>\n      <td>340.329723</td>\n      <td>NaN</td>\n      <td>339.351662</td>\n    </tr>\n    <tr>\n      <th>Supermarket Type1</th>\n      <td>2313.099451</td>\n      <td>2323.990559</td>\n      <td>2298.995256</td>\n    </tr>\n    <tr>\n      <th>Supermarket Type2</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>1995.498739</td>\n    </tr>\n    <tr>\n      <th>Supermarket Type3</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>3694.038558</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {.cell execution_count=18}\n``` {.python .cell-code}\nfig = px.imshow(\n    pivot_mean,\n    text_auto=True,\n    aspect=\"auto\",\n    title=\"Media de ventas: tipo de outlet vs localización\"\n)\nfig.show()\n```\n\n::: {.cell-output .cell-output-display}\n```\nUnable to display output for mime type(s): text/html\n```\n:::\n:::\n\n\nLa heterogeneidad cruzada muestra que una sola variable categórica no siempre basta para describir el comportamiento de las ventas. En este caso, la combinación entre `Outlet_Type` y `Outlet_Location_Type` permite detectar patrones más específicos que no se observan con la misma claridad al analizar cada variable por separado.\n\nEl resultado más visible es que `Supermarket Type3` en `Tier 3` presenta la media de ventas más alta (**3694.039**), mientras que `Grocery Store` mantiene niveles muy bajos tanto en `Tier 1` (**340.330**) como en `Tier 3` (**339.352**). Por su parte, `Supermarket Type1` muestra un comportamiento bastante estable entre ubicaciones, con medias de **2313.099** en `Tier 1`, **2323.991** en `Tier 2` y **2298.995** en `Tier 3`.\n\nPara el EDA, esto tiene varias implicaciones:\n\n- la variación en ventas no depende solo del tipo de outlet ni solo de la ubicación, sino de su **combinación**;\n- `Supermarket Type1` parece ser un formato relativamente estable entre territorios, mientras que otros tipos están mucho más concentrados en ciertas ubicaciones;\n- existen combinaciones ausentes (`NaN`), lo que indica que no todos los formatos de outlet están presentes en todas las localizaciones, y eso también forma parte de la estructura real del negocio;\n- conviene seguir explorando **interacciones** entre variables categóricas, porque parte de la heterogeneidad puede estar oculta cuando se estudian los factores por separado;\n- en etapas posteriores, estas combinaciones pueden ser útiles para construir variables explicativas más informativas que cada factor individual por sí solo.\n\nEn síntesis, este análisis refuerza una idea central del EDA: las ventas no provienen de grupos simples, sino de **segmentos combinados** donde el contexto del outlet importa tanto como su categoría individual.\n\n## Entropía de Shannon como medida de heterogeneidad\n\nHasta ahora, la heterogeneidad se ha estudiado comparando promedios, medianas, dispersiones y distribuciones entre grupos. Sin embargo, también es útil contar con una medida **global** que resuma qué tan **diversificada** o **concentrada** está una variable categórica. Para ello puede utilizarse la **entropía de Shannon**.\n\nSi una categoría concentra casi toda la masa de observaciones o de ventas, la entropía será baja. En cambio, si la distribución está más repartida entre varios grupos, la entropía será mayor. En este sentido, la entropía ofrece una medida sintética de diversidad.\n\nEn términos generales, para una variable categórica con proporciones $p_1, p_2, \\dots, p_k$, la entropía se define como\n\n$$\nH = - \\sum_{i=1}^{k} p_i \\log(p_i)\n$$\n\ndonde valores más altos indican mayor heterogeneidad. Como el valor máximo depende del número de categorías, también conviene trabajar con una **entropía normalizada**:\n\n$$\nH_{\\text{norm}} = \\frac{H}{\\log(k)}\n$$\n\nDe esta forma, el resultado queda entre 0 y 1:\n\n- valores cercanos a **0** indican **alta concentración**;\n- valores cercanos a **1** indican **alta diversidad**.\n\n### Entropía de ventas por variable categórica\n\nEn esta sección calcularemos la entropía sobre la **distribución de ventas** agregadas por categoría, para responder preguntas como: ¿las ventas están repartidas entre muchos grupos o dependen de unos pocos?\n\n::: {.cell execution_count=19}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\n\nvars_cat_heterogeneidad = [\n    \"Outlet_Type\",\n    \"Outlet_Size\",\n    \"Outlet_Location_Type\",\n    \"Item_Type\"\n]\n\ndef shannon_entropy_from_sales(df, cat_var, sales_var=\"Item_Outlet_Sales\"):\n    sales_by_group = df.groupby(cat_var)[sales_var].sum().dropna()\n    p = sales_by_group / sales_by_group.sum()\n    h = -(p * np.log(p)).sum()\n    h_norm = h / np.log(len(p)) if len(p) > 1 else np.nan\n    \n    return pd.Series({\n        \"n_categorias\": len(p),\n        \"entropia\": h,\n        \"entropia_normalizada\": h_norm\n    })\n\nentropy_table = pd.DataFrame({\n    var: shannon_entropy_from_sales(df, var)\n    for var in vars_cat_heterogeneidad\n}).T.reset_index(names=\"variable\")\n\nentropy_table.sort_values(\"entropia_normalizada\", ascending=False).round(4)\n```\n\n::: {.cell-output .cell-output-display execution_count=19}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>variable</th>\n      <th>n_categorias</th>\n      <th>entropia</th>\n      <th>entropia_normalizada</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>2</th>\n      <td>Outlet_Location_Type</td>\n      <td>3.0</td>\n      <td>1.0758</td>\n      <td>0.9792</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Item_Type</td>\n      <td>16.0</td>\n      <td>2.5168</td>\n      <td>0.9078</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Outlet_Size</td>\n      <td>3.0</td>\n      <td>0.9876</td>\n      <td>0.8990</td>\n    </tr>\n    <tr>\n      <th>0</th>\n      <td>Outlet_Type</td>\n      <td>4.0</td>\n      <td>0.8731</td>\n      <td>0.6298</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nLa interpretación debe hacerse con cuidado. Una entropía alta no significa necesariamente “mejor”, sino simplemente que las ventas están más repartidas entre las categorías de esa variable. Una entropía baja, en cambio, sugiere que el negocio está más concentrado en unos pocos segmentos.\n\n::: {.cell execution_count=20}\n``` {.python .cell-code}\nimport plotly.express as px\n\nentropy_plot = entropy_table.sort_values(\"entropia_normalizada\", ascending=True)\n\nfig = px.bar(\n    entropy_plot,\n    x=\"entropia_normalizada\",\n    y=\"variable\",\n    orientation=\"h\",\n    text=\"entropia_normalizada\",\n    title=\"Entropía normalizada de Shannon por variable categórica\",\n    labels={\n        \"entropia_normalizada\": \"Entropía normalizada\",\n        \"variable\": \"Variable categórica\"\n    },\n    range_x=[0, 1]\n)\n\nfig.update_traces(texttemplate=\"%{text:.3f}\", textposition=\"outside\")\nfig.update_layout(height=450, width=900)\n\nfig.show()\n```\n\n::: {.cell-output .cell-output-display}\n```\nUnable to display output for mime type(s): text/html\n```\n:::\n:::\n\n\nSi se desea profundizar en una variable concreta, también puede visualizarse directamente la distribución de las ventas agregadas por categoría. Por ejemplo, para Item_Type:\n\n::: {.cell execution_count=21}\n``` {.python .cell-code}\nsales_item_type = (\n    df.groupby(\"Item_Type\")[\"Item_Outlet_Sales\"]\n      .sum()\n      .sort_values(ascending=False)\n      .reset_index()\n)\n\nsales_item_type[\"proporcion\"] = (\n    sales_item_type[\"Item_Outlet_Sales\"] /\n    sales_item_type[\"Item_Outlet_Sales\"].sum()\n)\n\nfig = px.bar(\n    sales_item_type,\n    x=\"Item_Type\",\n    y=\"proporcion\",\n    text=\"proporcion\",\n    title=\"Proporción de ventas por tipo de producto\",\n    labels={\n        \"Item_Type\": \"Tipo de producto\",\n        \"proporcion\": \"Proporción de ventas\"\n    }\n)\n\nfig.update_traces(texttemplate=\"%{text:.3f}\", textposition=\"outside\")\nfig.update_layout(xaxis_tickangle=45, height=500, width=950)\n\nfig.show()\n```\n\n::: {.cell-output .cell-output-display}\n```\nUnable to display output for mime type(s): text/html\n```\n:::\n:::\n\n\nLos resultados de entropía sugieren que no todas las variables categóricas aportan el mismo tipo de segmentación para el EDA. En particular, `Outlet_Location_Type` presenta la **mayor entropía normalizada** (**0.9792**), seguido por `Item_Type` (**0.9078**) y `Outlet_Size` (**0.8990**). Esto indica que, en estas variables, las ventas están **bastante repartidas** entre sus categorías y no dependen fuertemente de un solo grupo.\n\nEn cambio, `Outlet_Type` muestra una entropía normalizada claramente menor (**0.6298**), lo que sugiere una **mayor concentración** de las ventas en unos pocos tipos de outlet. Esto es coherente con los análisis previos, donde se observó que ciertos formatos, especialmente `Supermarket Type3` y `Supermarket Type1`, concentran gran parte del volumen de ventas.\n\nPara el EDA, esto tiene varias implicaciones:\n\n- `Outlet_Type` aparece como una variable especialmente útil para detectar **concentración comercial**, ya que distingue grupos con pesos muy desiguales en el negocio;\n- `Outlet_Location_Type`, `Outlet_Size` e `Item_Type` reflejan una estructura más **diversificada**, por lo que su utilidad analítica está menos en la concentración y más en comparar patrones internos entre categorías;\n- una entropía alta no elimina la heterogeneidad, sino que indica que el negocio está más repartido entre grupos, por lo que conviene profundizar con medidas de nivel, dispersión y forma dentro de cada categoría;\n- el gráfico de proporciones por `Item_Type` muestra que, aunque la distribución es bastante diversa, algunas categorías como `Fruits and Vegetables` (**0.152**) y `Snack Foods` (**0.147**) tienen un peso algo mayor que otras, por lo que pueden merecer atención especial en análisis posteriores.\n\nEn síntesis, la entropía complementa el EDA porque ayuda a distinguir entre variables que describen un negocio **más concentrado** y variables que describen un negocio **más distribuido**. En este caso, `Outlet_Type` parece ser la variable más útil para estudiar concentración, mientras que `Item_Type`, `Outlet_Size` y `Outlet_Location_Type` son más útiles para explorar diversidad y segmentación interna.\n\n::: {.callout-important appearance=\"minimal\"}\nLa entropía anterior describe diversidad de participaciones. El coeficiente de Gini basado en la curva de Lorenz responde específicamente a desigualdad y se desarrolla, con su fórmula corregida, en [Medidas de concentración en Big Mart Sales](2-7-concentracion_bigmart.qmd).\n:::\n\n## Mini-dashboard de heterogeneidad\n\nA continuación se construye un dashboard compacto que integra varias vistas segmentadas.\n\n::: {.cell execution_count=22}\n``` {.python .cell-code}\nfrom plotly.subplots import make_subplots\n\nfig = make_subplots(\n    rows=2,\n    cols=2,\n    subplot_titles=(\n        \"Media por tipo de outlet\",\n        \"Media por tamaño de outlet\",\n        \"Media por localización\",\n        \"Top 8 tipos de producto\"\n    )\n)\n\nsummary1 = group_profile(df, \"Outlet_Type\")\nsummary2 = group_profile(df.dropna(subset=[\"Outlet_Size\"]), \"Outlet_Size\")\nsummary3 = group_profile(df, \"Outlet_Location_Type\")\nsummary4 = group_profile(df, \"Item_Type\").head(8)\n\nfig.add_trace(\n    go.Bar(x=summary1[\"Outlet_Type\"], y=summary1[\"media\"], name=\"Outlet Type\"),\n    row=1, col=1\n)\nfig.add_trace(\n    go.Bar(x=summary2[\"Outlet_Size\"], y=summary2[\"media\"], name=\"Outlet Size\"),\n    row=1, col=2\n)\nfig.add_trace(\n    go.Bar(x=summary3[\"Outlet_Location_Type\"], y=summary3[\"media\"], name=\"Location\"),\n    row=2, col=1\n)\nfig.add_trace(\n    go.Bar(x=summary4[\"Item_Type\"], y=summary4[\"media\"], name=\"Item Type\"),\n    row=2, col=2\n)\n\nfig.update_layout(\n    title=\"Dashboard básico de heterogeneidad en BigMart\",\n    height=750,\n    showlegend=False\n)\nfig.show()\n```\n\n::: {.cell-output .cell-output-display}\n```\nUnable to display output for mime type(s): text/html\n```\n:::\n:::\n\n\n## Conclusiones del capítulo\n\nEn este capítulo se mostró que la heterogeneidad constituye una dimensión esencial del análisis exploratorio de datos. Comparar grupos permite ampliar la descripción estadística de una variable y pasar de una lectura global a una interpretación segmentada y contextual.\n\nEn el dataset de BigMart, la heterogeneidad se manifiesta en diferencias entre tipos de outlet, tamaños, localizaciones y categorías de producto. Estas comparaciones enriquecen el EDA porque permiten distinguir subestructuras internas del fenómeno, identificar patrones consistentes y detectar segmentos con comportamientos contrastantes.\n\nEste capítulo prepara de manera natural el siguiente paso del proyecto: el estudio de la **concentración**, donde se analizará si una fracción reducida de grupos, productos o outlets explica una proporción sustancial del total de ventas.\n\n",
    "supporting": [
      "2-6-heterogeneidad_bigmart_files/figure-pdf"
    ],
    "filters": []
  }
}