{
  "hash": "76e55b2aff4a6ae573fa9024b6016aa6",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Tratamiento y Procesamiento de Datos Faltantes\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    toc-title: \"Contenido\"\n    code-fold: true\n    code-tools: true\n    theme: cosmo\n    highlight-style: github\nexecute:\n  echo: true\n  warning: false\n  message: false\njupyter: python3\n---\n\n## Introducción: La importancia de los datos faltantes\n\nEn el análisis de datos, es muy frecuente encontrarnos con valores faltantes (también conocidos como *missing values* o `NaN`). A menudo se subestima su importancia, pero la realidad es contundente: **No basta con saber cuántos datos faltan, hay que entender POR QUÉ faltan.**\n\nImaginemos que estamos analizando ventas de supermercados como en nuestro conjunto **BigMart Sales**. Si un producto no tiene registrado su tamaño de tienda (`Outlet_Size`), puede ser porque ciertas ubicaciones pequeñas no reportan esa métrica. Si falta el peso del producto (`Item_Weight`), tal vez proviene de una línea de suministro particular. Ignorar el motivo de la falta de datos y simplemente eliminarlos puede introducir sesgos catastróficos en nuestros modelos.\n\n### Taxonomía de Rubin: Entendiendo los mecanismos de ausencia\n\nEl estadístico Donald Rubin estableció la taxonomía fundamental para clasificar los mecanismos por los cuales faltan los datos[^1]. Estos se dividen intuitivamente en tres categorías:\n\n1. **MCAR (Missing Completely At Random - Faltante Completamente al Azar)**: La probabilidad de que un valor falte es completamente independiente de cualquier otra variable, observada o no observada.\n   *Ejemplo*: Se pierde el registro del peso de un producto (`Item_Weight`) porque un fallo aleatorio en la red corrompió la tabla en el servidor. \n\n2. **MAR (Missing At Random - Faltante al Azar)**: La probabilidad de ausencia depende de otras variables observadas en el dataset, pero no del valor de la variable faltante en sí misma.\n   *Ejemplo*: Es posible que el tamaño de la tienda (`Outlet_Size`) falte sistemáticamente para las tiendas establecidas en un año en particular (`Outlet_Establishment_Year` = 1998). La falta de respuesta depende del año, pero condicionado a ese año, la omisión del tamaño es aleatoria.\n\n3. **MNAR (Missing Not At Random - Faltante No al Azar)**[^4]: La probabilidad de ausencia depende del propio valor no observado.\n   *Ejemplo BigMart*: Los clientes de muy altos o muy bajos ingresos deliberadamente no reportan sus ingresos o gastos en encuestas de satisfacción de la tienda. La ausencia del dato está intrínsecamente ligada a su bajo rendimiento.\n\nEl impacto visual de ignorar esto es significativo. Si eliminamos simplemente los registros con datos faltantes bajo un escenario MAR o MNAR, la distribución observada resultante estará sesgada respecto a la distribución real de la población subyacente.\n\n## Desarrollo manual paso a paso\n\nPara desmitificar los métodos de imputación, veamos un micro-dataset de 4 registros con variables numéricas y categóricas del contexto BigMart, donde existen valores faltantes.\n\n| Producto | Item_Weight ($X_1$) | Item_Outlet_Sales ($X_2$) |\n|---------|---------------------|---------------------------|\n| FDA15   | 9.30                | 3735.13                   |\n| DRC01   | 5.92                | NaN                       |\n| FDN15   | NaN                 | 1098.56                   |\n| FDX07   | 19.20               | 4138.61                   |\n\n### 1. Imputación univariada manual\n\nLa estrategia más sencilla es rellenar con estadísticos básicos (media o mediana) calculados sobre los valores observados de esa misma columna.\n\nPara el **Item_Weight ($X_1$)**:\n- Valores observados: 9.30, 5.92, 19.20.\n- Media: $\\frac{9.30 + 5.92 + 19.20}{3} \\approx 11.47$.\n- El valor faltante del Producto FDN15 se imputa como **11.47**.\n\nPara las **Ventas ($X_2$)**:\n- Valores observados: 3735.13, 1098.56, 4138.61.\n- Media: $\\frac{3735.13 + 1098.56 + 4138.61}{3} \\approx 2990.76$.\n- El valor faltante del Producto DRC01 se imputa como **2990.76**.\n\n### 2. Imputación por KNN (K-Nearest Neighbors) manual\n\nEn lugar de usar un promedio global, usamos los promedios de los registros más similares (vecinos cercanos). Imputemos el **Peso del FDN15**.\n\n- Queremos hallar la distancia entre el FDN15 y el resto.\n- Dado que el Peso falta, medimos la distancia euclidiana basándonos *solo* en las variables observadas en común (en este caso, Ventas $X_2$).\n- Ventas de FDN15 = 1098.56.\n- Distancia(FDN15, FDA15): $|1098.56 - 3735.13| \\approx 2636.57$\n- Distancia(FDN15, DRC01): No computable directamente sin consideraciones extra.\n- Distancia(FDN15, FDX07): $|1098.56 - 4138.61| \\approx 3040.05$\n- Si elegimos $k=1$ vecino (FDA15, el más cercano observable), su Peso es 9.30:\n  Peso imputado de FDN15 = **9.30**.\n\n*(En implementaciones reales como `sklearn.impute.KNNImputer`, se usa la métrica de distancia de características ignorando los valores faltantes y ponderando)*.\n\n### 3. Imputación iterativa (MICE) manual\n\nEl algoritmo de Ecuaciones Encadenadas (MICE) trata cada característica con datos faltantes como una variable dependiente en una regresión sobre el resto de las características.\n\nEl proceso itera ajustando modelos de regresión secuencialmente usando el resto de variables disponibles hasta alcanzar convergencia, preservando la varianza mutua.\n\n## Laboratorio Interactivo: Simulador de Imputación en BigMart\n\n::: {.content-visible when-format=\"html\"}\n```{=html}\n<div class=\"interactive-lab\" style=\"border: 1px solid #e0e0e0; border-radius: 8px; padding: 20px; background: #fafafa; margin: 20px 0; font-family: sans-serif;\">\n  <h3 style=\"margin-top: 0;\">Simulador de Imputación (BigMart)</h3>\n  \n  <div style=\"display: flex; gap: 20px; flex-wrap: wrap;\">\n    <div style=\"flex: 1; min-width: 250px;\">\n      <h4>Estrategia Numérica: `Item_Weight`</h4>\n      <select id=\"weightStrategy\" onchange=\"updateImputation()\" style=\"width: 100%; padding: 5px; margin-bottom: 10px;\">\n        <option value=\"mean\">Media (Mean)</option>\n        <option value=\"median\">Mediana (Median)</option>\n        <option value=\"knn\">KNN Imputer (K-Nearest)</option>\n      </select>\n      \n      <div id=\"knnControls\" style=\"display: none; padding-left: 10px; margin-bottom: 15px; border-left: 3px solid #2196F3;\">\n        <label>K Vecinos: <span id=\"kValue\">3</span></label>\n        <input type=\"range\" id=\"kSlider\" min=\"1\" max=\"5\" value=\"3\" oninput=\"document.getElementById('kValue').innerText=this.value; updateImputation();\" style=\"width: 100%;\">\n      </div>\n      \n      <h4>Estrategia Categórica: `Outlet_Size`</h4>\n      <select id=\"sizeStrategy\" onchange=\"updateImputation()\" style=\"width: 100%; padding: 5px; margin-bottom: 10px;\">\n        <option value=\"mode\">Moda (Más frecuente)</option>\n        <option value=\"indicator\">Indicador de Ausencia ('Missing')</option>\n      </select>\n      \n      <hr style=\"margin: 15px 0; border: 0; border-top: 1px solid #ccc;\">\n      <div style=\"background: #e3f2fd; padding: 10px; border-radius: 4px;\">\n        <strong>Estadísticas `Item_Weight`</strong><br>\n        Media resultante: <span id=\"resMean\" style=\"font-weight:bold;\">--</span><br>\n        Varianza: <span id=\"resVar\" style=\"font-weight:bold;\">--</span>\n      </div>\n    </div>\n    \n    <div style=\"flex: 2; min-width: 300px;\">\n      <h4>Visualización de Muestra</h4>\n      <div style=\"background: #fff; border: 1px solid #ddd; padding: 10px; border-radius: 4px; overflow-x: auto;\">\n        <table style=\"width: 100%; border-collapse: collapse; text-align: left;\">\n          <thead>\n            <tr style=\"border-bottom: 2px solid #ccc;\">\n              <th style=\"padding: 5px;\">ID</th>\n              <th style=\"padding: 5px;\">Sales (Obs)</th>\n              <th style=\"padding: 5px;\">Weight</th>\n              <th style=\"padding: 5px;\">Outlet_Size</th>\n            </tr>\n          </thead>\n          <tbody id=\"imputeTbody\">\n          </tbody>\n        </table>\n      </div>\n    </div>\n  </div>\n</div>\n\n<script>\n  // Muestra simulada\n  const dataSamples = [\n    { id: 'FDA15', sales: 3700, weight: 9.30, size: 'Medium' },\n    { id: 'DRC01', sales: 1200, weight: 5.92, size: null },\n    { id: 'FDN15', sales: 1100, weight: null, size: 'Small' },\n    { id: 'FDX07', sales: 4100, weight: 19.20, size: null },\n    { id: 'NCD19', sales: 3500, weight: null, size: 'High' },\n    { id: 'FDP10', sales: 2500, weight: 15.00, size: 'Medium' }\n  ];\n\n  function updateImputation() {\n    const wStrat = document.getElementById('weightStrategy').value;\n    const sStrat = document.getElementById('sizeStrategy').value;\n    const k = parseInt(document.getElementById('kSlider').value);\n    \n    document.getElementById('knnControls').style.display = wStrat === 'knn' ? 'block' : 'none';\n    \n    let wVals = dataSamples.filter(d => d.weight !== null).map(d => d.weight);\n    let meanW = wVals.reduce((a,b) => a+b,0)/wVals.length;\n    let sortedW = [...wVals].sort((a,b) => a-b);\n    let medianW = sortedW.length % 2 === 0 ? (sortedW[sortedW.length/2 - 1] + sortedW[sortedW.length/2])/2 : sortedW[Math.floor(sortedW.length/2)];\n    \n    let sizes = dataSamples.filter(d => d.size !== null).map(d => d.size);\n    let modeSize = sizes.sort((a,b) => sizes.filter(v => v===a).length - sizes.filter(v => v===b).length).pop();\n    \n    let processed = JSON.parse(JSON.stringify(dataSamples));\n    let finalW = [];\n    \n    processed.forEach((d, i) => {\n      // Impute Weight\n      if (d.weight === null) {\n        if (wStrat === 'mean') d.weight = meanW;\n        else if (wStrat === 'median') d.weight = medianW;\n        else if (wStrat === 'knn') {\n          // simple 1D knn based on sales\n          let others = dataSamples.filter(x => x.weight !== null).map(x => ({dist: Math.abs(x.sales - d.sales), w: x.weight}));\n          others.sort((a,b) => a.dist - b.dist);\n          let sum = 0;\n          let actualK = Math.min(k, others.length);\n          for(let j=0; j<actualK; j++) sum += others[j].w;\n          d.weight = sum / actualK;\n        }\n        d.imputedW = true;\n      }\n      finalW.push(d.weight);\n      \n      // Impute Size\n      if (d.size === null) {\n        if (sStrat === 'mode') d.size = modeSize;\n        else if (sStrat === 'indicator') d.size = 'Missing';\n        d.imputedS = true;\n      }\n    });\n    \n    let finalMean = finalW.reduce((a,b)=>a+b,0)/finalW.length;\n    let finalVar = finalW.reduce((a,b)=>a+Math.pow(b-finalMean,2),0)/finalW.length;\n    \n    document.getElementById('resMean').innerText = finalMean.toFixed(2);\n    document.getElementById('resVar').innerText = finalVar.toFixed(2);\n    \n    let html = '';\n    processed.forEach(d => {\n      let wStyle = d.imputedW ? 'color:#c62828; font-weight:bold;' : '';\n      let sStyle = d.imputedS ? 'color:#c62828; font-weight:bold;' : '';\n      html += `<tr style=\"border-bottom: 1px solid #eee;\">\n        <td style=\"padding: 5px;\">${d.id}</td>\n        <td style=\"padding: 5px;\">${d.sales}</td>\n        <td style=\"padding: 5px; ${wStyle}\">${d.weight.toFixed(2)} ${d.imputedW ? '*' : ''}</td>\n        <td style=\"padding: 5px; ${sStyle}\">${d.size} ${d.imputedS ? '*' : ''}</td>\n      </tr>`;\n    });\n    document.getElementById('imputeTbody').innerHTML = html;\n  }\n  \n  updateImputation();\n</script>\n```\n:::\n::: {.content-visible when-format=\"pdf\"}\n*(Nota: Este laboratorio interactivo con controles dinámicos está disponible en la versión web del libro).*\n:::\n\n## Formalización teórica y matemática\n\n### Definición probabilística de la taxonomía de Rubin\n\nSea $\\mathbf{Y} = (\\mathbf{Y}_{\\text{obs}}, \\mathbf{Y}_{\\text{mis}})$ la matriz de datos completa, particionada en partes observadas y faltantes. Sea $\\mathbf{M} \\in \\{0, 1\\}^{n \\times p}$ la matriz indicatriz de ausencia, donde $M_{ij} = 1$ si $Y_{ij}$ falta y 0 si se observa. Sea $\\boldsymbol{\\psi}$ los parámetros del mecanismo de pérdida de datos.\n\n1. **MCAR**: $P(\\mathbf{M} \\mid \\mathbf{Y}_{\\text{obs}}, \\mathbf{Y}_{\\text{mis}}, \\boldsymbol{\\psi}) = P(\\mathbf{M} \\mid \\boldsymbol{\\psi})$\n   *(La probabilidad de ausencia no depende de los datos)*\n2. **MAR**: $P(\\mathbf{M} \\mid \\mathbf{Y}_{\\text{obs}}, \\mathbf{Y}_{\\text{mis}}, \\boldsymbol{\\psi}) = P(\\mathbf{M} \\mid \\mathbf{Y}_{\\text{obs}}, \\boldsymbol{\\psi})$\n   *(La probabilidad depende solo de lo observado)*\n3. **MNAR**: $P(\\mathbf{M} \\mid \\mathbf{Y}_{\\text{obs}}, \\mathbf{Y}_{\\text{mis}}, \\boldsymbol{\\psi})$ depende inexorablemente de $\\mathbf{Y}_{\\text{mis}}$.\n\n### Sesgo del estimador de la media bajo eliminación por lista\n\nLa eliminación por lista (*listwise deletion* o `dropna` completo) genera estimadores insesgados **solo** si los datos son MCAR[^3]. \n\nBajo mecanismos MAR o MNAR, el valor esperado de la media observada está sesgado:\n$$ \\mathbb{E}[\\bar{Y}_{\\text{obs}}] \\neq \\mathbb{E}[Y] $$\n\n### MICE como muestreador de Gibbs\n\nEl algoritmo MICE (*Multivariate Imputation by Chained Equations*) puede verse teóricamente como una aproximación a un Muestreador de Gibbs. El objetivo es muestrear desde la distribución conjunta multivariada de los datos, iterando a través de distribuciones condicionales univariadas.\n\n## Implementación computacional\n\nA continuación demostramos cómo aplicar estas técnicas utilizando `pandas` y `scikit-learn` de manera robusta.\n\n::: {#af2ccaf1 .cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\nfrom sklearn.impute import SimpleImputer, KNNImputer\nfrom sklearn.experimental import enable_iterative_imputer\nfrom sklearn.impute import IterativeImputer\nfrom sklearn.pipeline import Pipeline\nfrom sklearn.compose import ColumnTransformer\n\n# Generación de datos simulados inspirados en BigMart\nnp.random.seed(42)\nn_samples = 1000\nitem_weight = np.random.normal(12.5, 4.5, n_samples)\nitem_sales = 1000 + item_weight * 120 + np.random.normal(0, 500, n_samples)\n\ndf = pd.DataFrame({'Item_Weight': item_weight, 'Item_Outlet_Sales': item_sales})\n\n# Introducir faltantes MAR (Faltan ventas para los items menos pesados)\nmissing_mask = (df['Item_Weight'] < 10) & (np.random.rand(n_samples) < 0.6)\ndf.loc[missing_mask, 'Item_Outlet_Sales'] = np.nan\n\n# Introducir faltantes MCAR (Faltan pesos al azar)\ndf.loc[np.random.rand(n_samples) < 0.1, 'Item_Weight'] = np.nan\n\nprint(f\"Valores faltantes originales:\\n{df.isnull().sum()}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nValores faltantes originales:\nItem_Weight          109\nItem_Outlet_Sales    182\ndtype: int64\n```\n:::\n:::\n\n\n::: {.callout-important title=\"Regla de oro en producción: Data Leakage\"}\nNUNCA calcules estadísticas de imputación utilizando el conjunto de test. El método `.fit()` de cualquier imputador debe ejecutarse exclusivamente sobre el `X_train`. El `X_test` solo debe pasar por el método `.transform()`. Romper esta regla causa *Data Leakage* (fuga de datos) y resultará en una estimación optimista y engañosa del rendimiento de tu modelo.\n:::\n\n### Estrategias de Imputación\n\n::: {#2980fb77 .cell execution_count=2}\n``` {.python .cell-code}\n# 1. Imputación por Media (con Missing Indicator Trick)\nimputer_mean = Pipeline(steps=[\n    ('imputer', SimpleImputer(strategy='mean', add_indicator=True))\n])\n\n# 2. Imputación por Mediana\nimputer_median = SimpleImputer(strategy='median')\n\n# 3. KNN Imputer\nimputer_knn = KNNImputer(n_neighbors=5)\n\n# 4. Iterative Imputer (MICE)\nimputer_mice = IterativeImputer(random_state=42, max_iter=10)\n\n# Aplicación\ndf_mean = pd.DataFrame(\n    imputer_mean.fit_transform(df[['Item_Weight', 'Item_Outlet_Sales']]), \n    columns=['Item_Weight', 'Item_Outlet_Sales', 'Weight_Missing_Flag', 'Sales_Missing_Flag']\n)\ndf_knn = pd.DataFrame(imputer_knn.fit_transform(df[['Item_Weight', 'Item_Outlet_Sales']]), columns=['Item_Weight', 'Item_Outlet_Sales'])\ndf_mice = pd.DataFrame(imputer_mice.fit_transform(df[['Item_Weight', 'Item_Outlet_Sales']]), columns=['Item_Weight', 'Item_Outlet_Sales'])\n```\n:::\n\n\nVisualización del impacto de la imputación en la distribución de la variable `Item_Outlet_Sales` (donde introdujimos los datos faltantes MAR):\n\n::: {#1a765faa .cell execution_count=3}\n``` {.python .cell-code}\nimport matplotlib.pyplot as plt\nimport seaborn as sns\n\nplt.figure(figsize=(10, 6))\nsns.kdeplot(df['Item_Outlet_Sales'].dropna(), label='Original (Observado)', linewidth=2)\nsns.kdeplot(df_mean['Item_Outlet_Sales'], label='Imputado (Media)', linestyle='--')\nsns.kdeplot(df_knn['Item_Outlet_Sales'], label='Imputado (KNN)', linestyle='-.')\nsns.kdeplot(df_mice['Item_Outlet_Sales'], label='Imputado (MICE)', linestyle=':')\n\nplt.title('Comparación de distribuciones de Sales según método de imputación')\nplt.xlabel('Item_Outlet_Sales')\nplt.ylabel('Densidad')\nplt.legend()\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](4-2-datos-faltantes_files/figure-html/cell-4-output-1.png){width=950 height=566}\n:::\n:::\n\n\n*(Noten cómo la imputación por la media deforma la distribución, creando un pico artificial en el centro y reduciendo la varianza, fenómeno conocido como atenuación de varianza[^2])*\n\n::: {.callout-tip title=\"Mejores prácticas en la industria\"}\n**Trade-off de latencia en producción:**  \nAunque algoritmos como `KNNImputer` e `IterativeImputer` (MICE) suelen ofrecer resultados más precisos preservando distribuciones multivariadas, son computacionalmente costosos. KNN tiene una complejidad de $O(N \\cdot D)$ por inferencia, y MICE requiere evaluar múltiples modelos de regresión. Esto los hace frecuentemente inviables para sistemas de inferencia en tiempo real (microservicios) que exigen latencias estrictas (SLA $< 50\\text{ms}$). En escenarios de producción de alta frecuencia, es estándar recurrir a `SimpleImputer` combinado estrechamente con el *Missingness Indicator Trick*[^5].\n\n**Manejo de variables categóricas:**  \nTratar los `NaN` en columnas categóricas como un valor explícito (e.g., \"FALTANTE\" o \"DESCONOCIDO\") es una práctica robusta y muy difundida. Esto evita descartar registros y permite que el algoritmo (especialmente en modelos basados en árboles) aprenda de forma autónoma cualquier patrón latente (MAR o MNAR) asociado a la ausencia de información.\n\n**Umbrales de descarte:**  \nUna regla de dedo (heurística) en la industria dicta descartar columnas (características) si más del 70-80% de sus valores son nulos, a menos que el dominio de negocio justifique que esa ausencia esporádica tiene un valor predictivo excepcionalmente alto.\n:::\n\n---\n\n[^1]: **Taxonomía de Rubin**: Introduce la diferencia entre mecanismos ignorables (MCAR, MAR) y no ignorables (MNAR). Si los datos son MNAR, los métodos estándar de máxima verosimilitud e imputación generarán resultados sesgados a menos que se modele explícitamente el mecanismo de pérdida.\n[^2]: **Imputación estocástica vs determinista**: Rellenar con la media es determinista; reduce artificialmente la varianza empírica y atenúa las covarianzas (correlaciones), lo que afecta adversamente las estimaciones de intervalos de confianza. Las imputaciones estocásticas (como regresión estocástica o iterativa) agregan un término de ruido para preservar la variabilidad.\n[^3]: **Prueba de Little para MCAR**: Es una prueba estadística formal desarrollada por Roderick J.A. Little para contrastar la hipótesis nula de que los datos faltantes en un dataset son estadísticamente MCAR.\n[^4]: **Maldición del sesgo de atrición (Attrition bias)**: En estudios longitudinales o pruebas A/B de larga duración, la pérdida de usuarios a lo largo del tiempo suele no ser aleatoria (MNAR). Esto introduce un grave sesgo si el análisis final se realiza solo sobre los usuarios que sobrevivieron al estudio.\n[^5]: **Missingness Indicator Trick**: Consiste en imputar el valor numérico (por ejemplo, con la media) y simultáneamente agregar una nueva columna booleana que indique si el valor original era faltante. Esto permite a los modelos (como el Random Forest) usar el propio \"patrón de ausencia\" como una característica predictiva si es que existe alguna señal informativa.\n\n",
    "supporting": [
      "4-2-datos-faltantes_files"
    ],
    "filters": [],
    "includes": {}
  }
}