{
  "hash": "7b659afe8b0bd51b64ccff4a27584b45",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Tratamiento de datos faltantes\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    toc-title: \"Contenido\"\n    code-fold: true\n    code-tools: true\n    theme: cosmo\n    highlight-style: github\nexecute:\n  echo: true\n  warning: false\n  message: false\njupyter: python3\n---\n\n\n\nEn una tabla de ventas como BigMart, `Item_Weight` puede faltar porque falló la captura del proveedor. En cambio, si `Outlet_Size` falta sobre todo en tiendas de cierto tipo, la ausencia contiene información sobre la tienda. Antes de elegir un método, pregunta **qué filas faltan, en qué grupos y desde cuándo**. `NaN`[^nan] indica que no se registró un valor; no explica la causa.\n\n## Un primer ejemplo visual\n\nSupongamos que conocemos el peso de todos los productos de una población simulada y ocultamos algunos a propósito. Podemos comparar la distribución completa con la que quedaría disponible para analizar. En datos reales, la curva completa normalmente no está disponible: aquí la conocemos porque hemos simulado los datos.\n\n::: {.cell fig-height='5.5' fig-width='12' execution_count=2}\n\n::: {.cell-output .cell-output-display}\n```\nUnable to display output for mime type(s): text/html\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```\nUnable to display output for mime type(s): text/html\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nMedia verdadera: 12.043\nMedia observada: 11.119\nProporción missing: 28.650%\n```\n:::\n:::\n\n\nEn este ejemplo, los pesos altos tienen más probabilidad de desaparecer y la media observada queda por debajo de la verdadera. Los histogramas tienen tamaños de muestra distintos; compara sobre todo su **forma** y las medias impresas, no solo la altura de las barras.\n\n## Ejemplo: tres mecanismos de ausencia\n\nUsaremos $R_i=1$ cuando el peso del producto $i$ está ausente. Los nombres MCAR, MAR y MNAR describen **supuestos sobre el proceso que generó la ausencia**, no etiquetas que podamos deducir con certeza de una tabla incompleta[^mecanismos].\n\n### MCAR: pérdida independiente de los datos\n\nUn fallo aleatorio del sistema elimina algunas filas sin tener en cuenta pesos ni características de las tiendas. En la simulación, cada registro tiene la misma probabilidad de perderse.\n\n::: {.cell fig-height='5.5' fig-width='12' execution_count=3}\n\n::: {.cell-output .cell-output-display}\n```\nUnable to display output for mime type(s): text/html\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nProporción missing: 20.57%\nMedia verdadera:    12.0425\nMedia observada:    12.0411\nDesv. estándar verdadera: 2.1935\nDesv. estándar observada: 2.1811\n```\n:::\n:::\n\n\nLa similitud de las medias es esperable en promedio, pero no garantiza que una muestra concreta no tenga error de muestreo. Eliminar filas MCAR también reduce la cantidad de información.\n\n### MAR: pérdida explicada por variables observadas\n\nLa probabilidad de que falte `Item_Weight` depende de `Outlet_Type`, que sí conocemos. Dentro de cada tipo de tienda, el mecanismo simulado ya no depende del peso. Como los pesos también varían por tipo, analizar solo los valores observados cambia la composición de la muestra.\n\n::: {.cell fig-height='5.5' fig-width='12' execution_count=4}\n\n::: {.cell-output .cell-output-display}\n```\nUnable to display output for mime type(s): text/html\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nProporción missing por grupo:\n     Outlet_Type  missing\n0  Grocery Store    0.763\n1    Mini Market    0.173\n2    Supermarket    0.031\n\nMedia verdadera: 12.177 Media observada: 13.693\n```\n:::\n:::\n\n\n::: {.cell fig-height='5.5' fig-width='12' execution_count=5}\n\n::: {.cell-output .cell-output-display}\n```\nUnable to display output for mime type(s): text/html\n```\n:::\n:::\n\n\nLa primera gráfica muestra **dónde** se concentran los faltantes; la segunda muestra el efecto sobre la distribución agregada. La variable auxiliar `Outlet_Type` permite estudiar y modelar ese patrón. MAR no significa que la falta sea aleatoria sin condiciones.\n\n### MNAR: pérdida ligada al valor ausente\n\nImaginemos que un proceso de captura omite con más frecuencia pesos grandes y que esa causa no queda explicada por ninguna columna observada. El mecanismo depende del propio peso que falta.\n\n::: {.cell fig-height='5.5' fig-width='12' execution_count=6}\n\n::: {.cell-output .cell-output-display}\n```\nUnable to display output for mime type(s): text/html\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nMedia verdadera: 12.012\nMedia observada: 10.716\nProporción missing: 62.44%\n```\n:::\n:::\n\n\nNo podemos confirmar MNAR solo mirando los pesos registrados. Necesitamos conocimiento del proceso de captura, una muestra de seguimiento o un análisis de sensibilidad[^sensibilidad].\n\n::: {.callout-note title=\"Antes de imputar\"}\nCuenta los faltantes por columna, por tipo de tienda y por periodo. Verifica si un código especial como `0` o `\"sin dato\"` representa ausencia. Documenta la definición de cada campo y el momento en que estará disponible durante la predicción.\n:::\n\n## De la intuición al cálculo: imputar un peso\n\nEn esta muestra pequeña conocemos `Item_Outlet_Sales` solo como **variable auxiliar de demostración**. Si las ventas son el objetivo de un modelo predictivo, no debemos usarlas para imputar predictores que estarán disponibles antes de la venta[^objetivo].\n\n| Producto | `Item_Weight` (kg) | Ventas observadas |\n|---|---:|---:|\n| FDA15 | 9.30 | 3735.13 |\n| DRC01 | 5.92 | 1200.00 |\n| FDN15 | — | 1098.56 |\n| FDX07 | 19.20 | 4138.61 |\n\n**Media observada.** Para FDN15, la media de los tres pesos registrados es $(9.30+5.92+19.20)/3\\approx 11.47$ kg. Es sencilla, pero todas las filas incompletas reciben el mismo número y la dispersión se contrae.\n\n**Vecino más cercano.** Si comparamos únicamente las ventas disponibles, DRC01 es el más cercano a FDN15: $|1200-1098.56|=101.44$. Con $k=1$ y ese único atributo auxiliar, imputaríamos **5.92 kg**. La distancia y el resultado cambian si añadimos otras variables o las escalamos; `KNNImputer` usa por defecto vecinos con peso uniforme[^knn].\n\n**Pregunta para discutir.** ¿Cuál de los dos valores parece más razonable? No podemos saberlo para FDN15 sin una observación verdadera. Por eso evaluaremos métodos ocultando temporalmente valores que sí conocemos.\n\n## Qué muestran las imputaciones\n\n### Imputación simple y distribución\n\nEsta gráfica de Plotly del capítulo original compara la distribución simulada completa con varias imputaciones simples. La modalidad se calcula después de redondear el peso a una décima; esa discretización solo sirve para ilustrar el método.\n\n::: {.cell fig-height='5.5' fig-width='12' execution_count=7}\n\n::: {.cell-output .cell-output-display}\n```\nUnable to display output for mime type(s): text/html\n```\n:::\n:::\n\n\nObserva el pico que produce reemplazar muchos faltantes por un mismo número. Mantener aproximadamente la media no implica conservar la varianza ni las relaciones con otras columnas.\n\n### KNN: los vecinos importan\n\nEn el siguiente ejemplo original se ocultan valores conocidos de una simulación. El panel derecho permite ver los vecinos y comparar una imputación con el valor ocultado. Los puntos rojos son una referencia didáctica, no información disponible al imputar datos reales.\n\n::: {.cell fig-height='5.5' fig-width='12' execution_count=8}\n\n::: {.cell-output .cell-output-display}\n```\nUnable to display output for mime type(s): text/html\n```\n:::\n:::\n\n\nAl usar KNN, escala las variables numéricas pertinentes y revisa qué columnas entran en la distancia. El vecino más cercano en una dimensión puede ser muy distinto del vecino en varias dimensiones.\n\n### Imputación múltiple: representar incertidumbre\n\nUna sola tabla completada trata cada valor imputado como si fuese conocido. Para inferencia estadística, podemos crear varias tablas plausibles, ajustar el análisis en cada una y combinar estimaciones y varianzas[^multiple]. La figura original usa `IterativeImputer(sample_posterior=True)` para generar cinco realizaciones; el valor predeterminado `sample_posterior=False` genera una imputación determinista y **no equivale por sí solo a imputación múltiple**.\n\n::: {.cell fig-height='5.5' fig-width='12' execution_count=9}\n\n::: {.cell-output .cell-output-display}\n```\nUnable to display output for mime type(s): text/html\n```\n:::\n:::\n\n\nLas cinco nubes muestran incertidumbre entre imputaciones; ninguna recupera necesariamente cada valor individual. Esta simulación visualiza el principio. Un análisis inferencial completo también necesita combinar los resultados de los modelos ajustados en cada tabla.\n\n## Formalización breve\n\nSea $Y=(Y_{\\mathrm{obs}},Y_{\\mathrm{mis}})$ el conjunto completo, $R$ el indicador de ausencia y $X$ las variables auxiliares observadas. De manera esquemática:\n\n- **MCAR:** $P(R\\mid Y,X)=P(R)$. La ausencia es independiente de los valores.\n- **MAR:** $P(R\\mid Y_{\\mathrm{obs}},Y_{\\mathrm{mis}},X)=P(R\\mid Y_{\\mathrm{obs}},X)$. Una vez condicionamos en lo observado, el valor ausente no añade información sobre $R$.\n- **MNAR:** la probabilidad de ausencia todavía depende de $Y_{\\mathrm{mis}}$ después de condicionar en lo observado.\n\nLa media de casos completos estima $E[Y\\mid R=0]$. Coincide con $E[Y]$ si ambos grupos tienen la misma media; MCAR es una condición suficiente para ello, pero no la única. Bajo MAR, incluir las variables observadas que explican la ausencia puede ayudar a corregir sesgos, siempre que el modelo y sus supuestos sean adecuados.\n\nPara una columna numérica, la imputación por media usa $\\hat y_i=\\bar y_{\\mathrm{obs}}$ cuando $R_i=1$. En KNN, $\\hat y_i=k^{-1}\\sum_{j\\in N_k(i)}y_j$, donde $N_k(i)$ reúne vecinos con el valor observado. Ambas producen **estimaciones**, no recuperaciones seguras del dato original.\n\n## Laboratorio: elegir y poner a prueba una imputación\n\n**Objetivo.** Comparar media, mediana y KNN en el mismo ejemplo de productos. **Hipótesis.** Un método que use ventas como variable auxiliar debería ganar cuando peso y ventas guarden una relación útil.\n\n1. Cambia el método y el número de vecinos. Anota la imputación del peso realmente ausente de FDN15.\n2. Ocultamos además el peso conocido de NCD19 **solo para validar**. Compara la predicción con su valor real y registra el error absoluto.\n3. Cambia entre moda y categoría «Faltante» para `Outlet_Size`. Comprueba qué celdas cambian y cuáles no.\n4. Explica por qué el menor error en **una sola fila** no prueba que un método sea mejor para toda la población. Propón una validación con varias filas ocultadas, repetida por grupos y periodos.\n\n::: {.content-visible when-format=\"html\"}\n```{=html}\n<div id=\"missing42-lab\" style=\"border:1px solid #b8cad9;border-radius:8px;padding:1rem;background:#f8fbff;max-width:900px\">\n  <div style=\"display:flex;gap:1rem;flex-wrap:wrap;align-items:end\">\n    <label>Método para el peso<br><select id=\"missing42-method\"><option value=\"mean\">Media</option><option value=\"median\">Mediana</option><option value=\"knn\">KNN por ventas</option></select></label>\n    <label>Vecinos (KNN)<br><input id=\"missing42-k\" type=\"range\" min=\"1\" max=\"4\" value=\"2\"><output id=\"missing42-k-value\">2</output></label>\n    <label><code>Outlet_Size</code><br><select id=\"missing42-size\"><option value=\"mode\">Moda observada</option><option value=\"missing\">Categoría «Faltante»</option></select></label>\n  </div>\n  <p id=\"missing42-result\" aria-live=\"polite\"></p>\n  <div style=\"overflow-x:auto\"><table class=\"table table-sm\"><thead><tr><th>Producto</th><th>Ventas (auxiliar)</th><th>Peso (kg)</th><th>Outlet_Size</th><th>Uso</th></tr></thead><tbody id=\"missing42-rows\"></tbody></table></div>\n  <p><small>El asterisco indica un peso estimado. Para evaluar NCD19, su valor real (12.40 kg) no participa en el cálculo.</small></p>\n</div>\n<script>\n(() => {\n  const rows = [\n    {id:'FDA15',sales:3735.13,weight:9.30,size:'Medium'},\n    {id:'DRC01',sales:1200.00,weight:5.92,size:null},\n    {id:'FDN15',sales:1098.56,weight:null,size:'Small'},\n    {id:'FDX07',sales:4138.61,weight:19.20,size:null},\n    {id:'NCD19',sales:3500.00,weight:12.40,size:'High',validation:true},\n    {id:'FDP10',sales:2500.00,weight:15.00,size:'Medium'}\n  ];\n  const root = document.getElementById('missing42-lab');\n  const method = root.querySelector('#missing42-method');\n  const kInput = root.querySelector('#missing42-k');\n  const size = root.querySelector('#missing42-size');\n  const donors = rows.filter(r => r.weight !== null && !r.validation);\n  const values = donors.map(r => r.weight).sort((a,b) => a-b);\n  const mean = values.reduce((a,b) => a+b,0) / values.length;\n  const median = (values[1] + values[2]) / 2;\n  function estimate(row) {\n    if (method.value === 'mean') return mean;\n    if (method.value === 'median') return median;\n    const neighbors = [...donors].sort((a,b) => Math.abs(a.sales-row.sales)-Math.abs(b.sales-row.sales)).slice(0,Number(kInput.value));\n    return neighbors.reduce((sum,r) => sum+r.weight,0) / neighbors.length;\n  }\n  function render() {\n    const k = Number(kInput.value);\n    root.querySelector('#missing42-k-value').textContent = String(k);\n    kInput.disabled = method.value !== 'knn';\n    const predicted = estimate(rows.find(r => r.validation));\n    const unknown = estimate(rows.find(r => r.id === 'FDN15'));\n    const error = Math.abs(predicted - 12.40);\n    root.querySelector('#missing42-result').textContent = `FDN15: ${unknown.toFixed(2)} kg estimados. Validación NCD19: ${predicted.toFixed(2)} kg frente a 12.40 kg reales; error absoluto = ${error.toFixed(2)} kg. Donantes: ${donors.length}.`;\n    root.querySelector('#missing42-rows').innerHTML = rows.map(r => {\n      const hidden = r.weight === null || r.validation;\n      const weight = hidden ? `${estimate(r).toFixed(2)} *` : r.weight.toFixed(2);\n      const outletSize = r.size ?? (size.value === 'mode' ? 'Medium *' : 'Faltante *');\n      const use = r.validation ? 'Validación' : r.weight === null ? 'Ausente' : 'Donante';\n      return `<tr><td>${r.id}</td><td>${r.sales.toFixed(2)}</td><td>${weight}</td><td>${outletSize}</td><td>${use}</td></tr>`;\n    }).join('');\n  }\n  [method,kInput,size].forEach(el => el.addEventListener('input',render));\n  render();\n})();\n</script>\n```\n:::\n\n::: {.content-visible when-format=\"pdf\"}\nEl laboratorio interactivo se encuentra en la versión HTML. Para resolverlo sin controles: calcula la media y la mediana de $9.30$, $5.92$, $19.20$ y $15.00$; después predice el peso de NCD19 (12.40 kg, ocultado) usando los $k$ vecinos en ventas y compara el error absoluto.\n:::\n\n## Implementación sin fuga de información\n\nEn un problema supervisado, separamos primero entrenamiento y prueba, y ajustamos cualquier imputador **solo con entrenamiento**. Aquí `Item_Outlet_Sales` es la variable objetivo: nunca se usa como predictor para imputar `Item_Weight`. Las variables auxiliares son un precio y un tipo de tienda simulados.\n\n::: {.cell execution_count=10}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\nfrom sklearn.compose import ColumnTransformer\nfrom sklearn.impute import SimpleImputer\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.pipeline import Pipeline\nfrom sklearn.preprocessing import OneHotEncoder\nfrom sklearn.linear_model import LinearRegression\n\nrng = np.random.default_rng(42)\nn = 300\noutlet = rng.choice(['Supermarket', 'Grocery'], size=n, p=[0.6, 0.4])\nweight = rng.normal(12, 2, n)\nprice = rng.normal(100, 15, n)\nsales = 150 + 30 * weight + 4 * price + rng.normal(0, 50, n)\nX = pd.DataFrame({'Item_Weight': weight, 'Item_MRP': price, 'Outlet_Type': outlet})\ny = pd.Series(sales, name='Item_Outlet_Sales')\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)\n\n# MAR simulado: la ausencia de peso depende del tipo de tienda observado.\nfor part in (X_train, X_test):\n    probability = np.where(part['Outlet_Type'].eq('Grocery'), 0.45, 0.10)\n    part.loc[rng.random(len(part)) < probability, 'Item_Weight'] = np.nan\n\nnumeric = Pipeline([('imputer', SimpleImputer(strategy='median', add_indicator=True))])\npreprocess = ColumnTransformer([\n    ('numeric', numeric, ['Item_Weight', 'Item_MRP']),\n    ('outlet', OneHotEncoder(handle_unknown='ignore'), ['Outlet_Type'])\n])\nmodel = Pipeline([('preprocess', preprocess), ('regression', LinearRegression())])\nmodel.fit(X_train, y_train)\nprint('R² en prueba:', round(model.score(X_test, y_test), 3))\nprint('Faltantes en train:', X_train['Item_Weight'].isna().sum())\nprint('Faltantes en test:', X_test['Item_Weight'].isna().sum())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nR² en prueba: 0.623\nFaltantes en train: 57\nFaltantes en test: 16\n```\n:::\n:::\n\n\nLa puntuación es solo una comprobación de que el flujo se ejecuta; para elegir estrategia, compara alternativas con validación cruzada dentro del conjunto de entrenamiento y deja la prueba para la evaluación final. Un indicador de ausencia puede ayudar cuando el patrón aporta señal; compruébalo empíricamente[^indicador].\n\n::: {.callout-tip title=\"Práctica profesional: documentar y vigilar\"}\nGuarda el imputador junto con el modelo, vigila la tasa de faltantes por grupo y periodo, y registra qué campos están disponibles en el momento de inferencia. Compara una línea base simple con métodos más costosos según la métrica, la latencia y el volumen **de tu sistema**. No existe un umbral universal para descartar columnas ni un método de imputación superior en todos los datos. [scikit-learn: errores comunes y fuga de datos](https://scikit-learn.org/stable/common_pitfalls.html) · [scikit-learn: imputación](https://scikit-learn.org/stable/modules/impute.html).\n:::\n\n[^nan]: `NaN` significa *Not a Number*. En pandas, también pueden aparecer otros marcadores de ausencia como `None` o `pd.NA`, según el tipo de columna.\n[^mecanismos]: MCAR significa *Missing Completely At Random*; MAR, *Missing At Random*; MNAR, *Missing Not At Random*. MAR es una independencia **condicional** respecto al valor ausente.\n[^sensibilidad]: Un análisis de sensibilidad repite el cálculo bajo varios supuestos plausibles sobre los valores no observados para ver cuánto cambia la conclusión.\n[^objetivo]: La variable objetivo es el resultado que se desea predecir. Usarla para construir un predictor crea fuga de información si ese resultado todavía no existe al hacer la predicción.\n[^knn]: Por defecto, `KNNImputer` usa la distancia `nan_euclidean` y `weights=\"uniform\"`; también admite ponderar vecinos por distancia. [Documentación de KNNImputer](https://scikit-learn.org/stable/modules/generated/sklearn.impute.KNNImputer.html).\n[^multiple]: La imputación múltiple considera incertidumbre entre tablas imputadas. `IterativeImputer` puede producir realizaciones con `sample_posterior=True`, pero el análisis y la combinación de estimaciones quedan a cargo del usuario. [Documentación de IterativeImputer](https://scikit-learn.org/stable/modules/generated/sklearn.impute.IterativeImputer.html).\n[^indicador]: Un indicador de ausencia es una columna binaria que registra si el valor original faltaba. `SimpleImputer(add_indicator=True)` la añade para las columnas con faltantes durante el ajuste. [Documentación de SimpleImputer](https://scikit-learn.org/stable/modules/generated/sklearn.impute.SimpleImputer.html).\n\n",
    "supporting": [
      "4-2-datos-faltantes_files/figure-pdf"
    ],
    "filters": []
  }
}