{
  "hash": "bab1f6f06c679eee9a79bcc120dbc4d2",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Medidas de forma\"\nauthor: \"Diego Villalba\"\ndate: today\nlang: es\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    number-sections: true\n    code-fold: true\n    code-tools: true\n    code-summary: \"Mostrar código\"\n    fig-align: center\n    theme: cosmo\n  pdf:\n    toc: true\n    toc-depth: 3\n    number-sections: true\nexecute:\n  echo: true\n  warning: false\n  message: false\n  cache: false\njupyter: python3\nbibliography: [referencias_eda.bib, ../../references.bib]\ncrossref:\n  fig-title: \"Figura\"\n  tbl-title: \"Tabla\"\n  eq-prefix: \"Ec.\"\n---\n\n## El problema: mismo centro y escala, distinta experiencia\n\nUna cafetería registró el tiempo de espera, en minutos, de sus primeros cinco\nclientes durante dos mañanas:\n\n| Mañana | Tiempos de espera ordenados |\n|:---:|:---|\n| A | $0,\\ 2,\\ 3,\\ 4,\\ 6$ |\n| B | $2,\\ 2,\\ 2,\\ 2,\\ 7$ |\n\nEn ambas mañanas, la espera media es de tres minutos:\n\n$$\n\\bar x_A=\\frac{0+2+3+4+6}{5}=3,\n\\qquad\n\\bar x_B=\\frac{2+2+2+2+7}{5}=3.\n$$\n\nTambién comparten el mismo segundo momento central,[^momento-central] que en\neste capítulo calcularemos con divisor $n$:\n\n$$\n\\begin{aligned}\nm_{2,A}\n&=\\frac{(-3)^2+(-1)^2+0^2+1^2+3^2}{5}=4,\\\\\nm_{2,B}\n&=\\frac{(-1)^2+(-1)^2+(-1)^2+(-1)^2+4^2}{5}=4.\n\\end{aligned}\n$$\n\nPor tanto, ambas tienen escala $\\sqrt{m_2}=2$ minutos. Sin embargo, no\ncuentan la misma historia:\n\n- en A, los tiempos se reparten de manera simétrica alrededor de 3;\n- en B, cuatro clientes esperan 2 minutos y uno espera 7: hay una extensión\n  hacia la derecha.\n\nLa localización y la variabilidad no determinan la geometría de una\ndistribución.[^distribucion] Para distinguir estas mañanas necesitamos estudiar\nsu **forma**: simetría, dirección de las colas, frecuencia de observaciones\nalejadas y número de agrupamientos o modos [@tukey1977eda; @nist2012handbook].\n\n::: {.callout-note appearance=\"minimal\"}\n### Una idea que servirá como brújula\n\nTrasladar todos los datos cinco minutos o convertir minutos a segundos cambia\nla localización o la escala, pero no debería cambiar la forma. En contraste,\nmover una sola observación hacia un extremo sí puede cambiarla.\n:::\n\n## Aprender a mirar la forma\n\n### Simetría y asimetría\n\nUna distribución es **simétrica alrededor de $c$** si las desviaciones a la\nizquierda y a la derecha de $c$ tienen el mismo comportamiento. En una\ndistribución continua,[^continua] esto significa que su densidad satisface\n$f(c-t)=f(c+t)$ para todo $t$ donde esté definida. En datos finitos, la idea\nse aprecia al ordenar los valores y comparar pares equidistantes del centro.\n\nEn la mañana A,\n\n$$\n(0,2,3,4,6)-3=(-3,-1,0,1,3).\n$$\n\nCada desviación negativa tiene una contraparte positiva. En la mañana B,\n\n$$\n(2,2,2,2,7)-3=(-1,-1,-1,-1,4),\n$$\n\nde modo que una desviación positiva larga compensa cuatro desviaciones\nnegativas cortas. Diremos que B tiene **asimetría a la derecha** o positiva.\nLa cola indica la dirección de la asimetría, no el lado donde se acumulan más\nobservaciones.[^cola]\n\nEs común usar la posición relativa de media y mediana como pista. En B,\n$\\bar x=3>\\operatorname{Med}(x)=2$, porque el 7 atrae a la media hacia la\nderecha. No es un teorema universal: distribuciones complejas pueden violar\nesa regla. La forma debe inspeccionarse gráficamente y no inferirse solo a\npartir de dos resúmenes.\n\n### Colas y observaciones alejadas\n\nLas **colas** describen lo que ocurre lejos de la región central. Dos\ndistribuciones simétricas pueden compartir media y varianza y, aun así, asignar\nprobabilidades muy diferentes a resultados extremos. Esto importa cuando se\nestudian tiempos de espera inusuales, pérdidas, fallas o anomalías.\n\nEn una muestra pequeña no puede observarse literalmente el comportamiento\ninfinito de una cola. Sí pueden verse señales: máximos muy separados, cuantiles\nextremos,[^cuantil] sensibilidad de los momentos altos y desviaciones en un\ngráfico Q--Q. Hablar de “colas pesadas” a partir de cinco datos debe entenderse\ncomo una hipótesis para investigar, no como una conclusión definitiva.\n\n### Modos y mezclas\n\nUn **modo** es una región de alta frecuencia o densidad.[^modo] Una distribución\ncon dos concentraciones visibles es bimodal. Esto puede ocurrir, por ejemplo,\nsi se mezclan pedidos sencillos y pedidos que requieren preparación especial.\nLa bimodalidad no equivale a asimetría: una distribución puede ser bimodal y\nsimétrica.\n\n::: {.callout-important appearance=\"minimal\"}\n### La forma tiene varias dimensiones\n\nAsimetría, colas y modalidad responden preguntas distintas. Ningún número\núnico reconstruye toda la distribución. Las medidas complementan al histograma,\nal diagrama de puntos, a la ECDF y al gráfico Q--Q; no los sustituyen.\n:::\n\n## Del dibujo al cálculo: la mañana B\n\nTrabajaremos a mano con\n\n$$\nx=(2,2,2,2,7),\\qquad n=5,\\qquad \\bar x=3.\n$$\n\nLa tabla organiza todas las operaciones. Las potencias impares conservan el\nsigno de la desviación; las pares lo eliminan.\n\n| $x_i$ | $d_i=x_i-\\bar x$ | $d_i^2$ | $d_i^3$ | $d_i^4$ |\n|---:|---:|---:|---:|---:|\n| 2 | -1 | 1 | -1 | 1 |\n| 2 | -1 | 1 | -1 | 1 |\n| 2 | -1 | 1 | -1 | 1 |\n| 2 | -1 | 1 | -1 | 1 |\n| 7 | 4 | 16 | 64 | 256 |\n| **Suma** | **0** | **20** | **60** | **260** |\n\n### Por qué el cubo detecta dirección\n\nEl tercer momento central es\n\n$$\nm_3=\\frac1n\\sum_{i=1}^{n}(x_i-\\bar x)^3\n=\\frac{60}{5}=12.\n$$\n\nLas desviaciones a la izquierda aportan números negativos y las de la derecha,\npositivos. Además, el cubo da mucho más peso a $4$ que a $1$:\n$4^3=64$. El signo positivo concuerda con la extensión hacia la derecha.\n\nEl valor 12 está en minutos cúbicos y cambiaría al convertir unidades. Para\nobtener una medida sin unidades se divide por la escala al cubo:\n\n$$\ng_1=\\frac{m_3}{m_2^{3/2}}\n=\\frac{12}{4^{3/2}}\n=\\frac{12}{8}=1.5. \\tag{1}\n$$\n\nEn la mañana A, los cubos se cancelan por pares:\n\n$$\n(-3)^3+(-1)^3+0^3+1^3+3^3=0,\n$$\n\npor lo que $g_1=0$. Así logramos distinguir dos conjuntos que tenían la\nmisma media y la misma escala.\n\n### Por qué la cuarta potencia detecta alejamiento\n\nEl cuarto momento central de B es\n\n$$\nm_4=\\frac1n\\sum_{i=1}^{n}(x_i-\\bar x)^4\n=\\frac{260}{5}=52.\n$$\n\nComo la cuarta potencia siempre es no negativa, no mide dirección. Su efecto\nes amplificar las observaciones alejadas: la desviación $4$ aporta\n$4^4=256$, mientras que cada desviación de magnitud $1$ aporta solo 1.\n\nLa **curtosis de Pearson** estandariza con la varianza al cuadrado:\n\n$$\nb_2=\\frac{m_4}{m_2^2}\n=\\frac{52}{4^2}=3.25. \\tag{2}\n$$\n\nLa distribución normal tiene curtosis poblacional 3. Por eso también se usa\nel **exceso de curtosis de Fisher**:\n\n$$\ng_2=b_2-3=3.25-3=0.25. \\tag{3}\n$$\n\nRestar 3 solo cambia el punto de referencia; no cambia la información. En\nparticular, “curtosis 3” y “exceso 0” describen la misma referencia normal.\n\n::: {.callout-warning appearance=\"minimal\"}\n### Curtosis no significa simplemente “altura del pico”\n\nLa curtosis es el promedio de la **cuarta potencia de las desviaciones\nestandarizadas**. Por ello responde con fuerza a observaciones alejadas y al\ncomportamiento de las colas. La altura central puede cambiar también, pero no\nexiste una correspondencia única entre “pico alto” y curtosis alta. Interpretar\nla curtosis solo como apuntamiento puede llevar a conclusiones equivocadas.\n:::\n\n## Formalización mediante momentos\n\nSea $X$ una variable aleatoria numérica[^variable-aleatoria] con media\n$\\mu=\\mathbb E[X]$. Cuando las esperanzas existen, se distinguen:\n\n$$\n\\text{momento respecto al origen:}\n\\qquad \\mu'_r=\\mathbb E[X^r],\n$$\n\n$$\n\\text{momento central:}\n\\qquad \\mu_r=\\mathbb E[(X-\\mu)^r]. \\tag{4}\n$$\n\nLos primeros momentos centrales ayudan a leer la construcción:\n\n- $\\mu_1=0$, porque las desviaciones respecto de la media se compensan;\n- $\\mu_2=\\sigma^2$, la varianza poblacional;\n- $\\mu_3$ conserva dirección, pero depende de la unidad al cubo;\n- $\\mu_4$ pondera intensamente el alejamiento y depende de la unidad a la\n  cuarta potencia.\n\nSi $0<\\sigma^2<\\infty$, los momentos estandarizados tercero y cuarto son\n\n$$\n\\gamma_1=\\frac{\\mu_3}{\\sigma^3},\n\\qquad\n\\beta_2=\\frac{\\mu_4}{\\sigma^4},\n\\qquad\n\\gamma_2=\\beta_2-3. \\tag{5}\n$$\n\n$\\gamma_1$ es la asimetría poblacional, $\\beta_2$ la curtosis de Pearson y\n$\\gamma_2$ el exceso de Fisher. Si la variable es constante, $\\sigma=0$ y\nestas razones no están definidas: no se debe reportar cero como si hubiese una\nforma estimable.\n\n### Propiedades que aclaran la interpretación\n\nSi $Y=a+bX$, con $b\\neq0$, entonces\n\n$$\n\\mu_r(Y)=b^r\\mu_r(X),\n\\qquad\n\\sigma_Y=|b|\\sigma_X.\n$$\n\nPor tanto,\n\n$$\n\\gamma_1(Y)=\\operatorname{sign}(b)\\gamma_1(X),\n\\qquad\n\\beta_2(Y)=\\beta_2(X). \\tag{6}\n$$\n\nSumar una constante o cambiar de minutos a segundos con un factor positivo no\naltera asimetría ni curtosis. Reflejar el eje, $b<0$, invierte el signo de la\nasimetría y conserva la curtosis.\n\nSi una distribución es simétrica y su tercer momento existe, entonces\n$\\mu_3=0$. El recíproco es falso: asimetría cero no garantiza simetría. Por\nejemplo, la muestra\n\n$$\n(0,0,0,4,5,5,7)\n$$\n\ntiene media 3 y suma de cubos centrados\n\n$$\n3(-3)^3+1^3+2(2^3)+4^3=-81+1+16+64=0,\n$$\n\npero no es simétrica alrededor de 3.\n\nLa curtosis poblacional satisface $\\beta_2\\ge1$, siempre que la varianza sea\npositiva y el cuarto momento finito. Se obtiene de\n\n$$\n\\mathbb E[(X-\\mu)^4]\n\\ge \\left(\\mathbb E[(X-\\mu)^2]\\right)^2.\n$$\n\nNo hay una cota superior universal: una probabilidad pequeña colocada muy\nlejos del centro puede hacer crecer el cuarto momento de manera drástica.\n\n### Población, muestra y convenciones de software\n\nPara una colección observada usamos los momentos descriptivos\n\n$$\nm_r=\\frac1n\\sum_{i=1}^{n}(x_i-\\bar x)^r,\n\\qquad\ng_1=\\frac{m_3}{m_2^{3/2}},\n\\qquad\ng_2=\\frac{m_4}{m_2^2}-3. \\tag{7}\n$$\n\nSi los datos se consideran una muestra de una población, existen correcciones\npara reducir el sesgo del estimador.[^estimador] Una convención frecuente es\n\n$$\nG_1=\\frac{\\sqrt{n(n-1)}}{n-2}g_1,\n\\qquad n>2, \\tag{8}\n$$\n\n$$\nG_2=\\frac{n-1}{(n-2)(n-3)}\n\\left[(n+1)g_2+6\\right],\n\\qquad n>3. \\tag{9}\n$$\n\nPara la mañana B, $g_1=1.5$ y $g_2=0.25$, mientras que las versiones\ncorregidas dan $G_1\\approx2.2361$ y $G_2=5$. La diferencia es grande porque\n$n=5$. Paquetes distintos pueden usar definiciones distintas; el resultado\ndebe acompañarse de la convención y el tamaño muestral [@joanes1998skewness].\n\n::: {.callout-note appearance=\"minimal\"}\nLas correcciones no convierten cinco observaciones en evidencia abundante.\nReducen cierto sesgo bajo un modelo de muestreo, pero las medidas de orden alto\nsiguen siendo inestables en muestras pequeñas.\n:::\n\n## Laboratorio interactivo: cambiar la forma\n\nEl laboratorio parte de la mañana B. Mueva cada observación o compare los\nescenarios preparados. Observe que “simétrica” y “asimétrica a la derecha”\ntienen la misma media y la misma desviación, mientras que “misma forma, otra\nescala” conserva $g_1$ y $g_2$ aunque duplica la desviación estándar.\n\n::: {.content-visible when-format=\"html\"}\n```{=html}\n<div id=\"shape-wait-lab\" class=\"shape-lab\" aria-labelledby=\"shape-lab-title\">\n  <style>\n    #shape-wait-lab { --ink:#172033; --muted:#64748b; --line:#cbd5e1; --blue:#2563eb; --orange:#d97706; margin:1.25rem 0 1.75rem; color:var(--ink); }\n    #shape-wait-lab .lab-shell { border:1px solid var(--line); border-radius:12px; padding:1rem; background:#fff; }\n    #shape-wait-lab .lab-title { font-weight:700; margin:0 0 .25rem; }\n    #shape-wait-lab .lab-intro { color:#475569; margin:0 0 1rem; }\n    #shape-wait-lab .lab-layout { display:grid; grid-template-columns:minmax(250px,.9fr) minmax(320px,1.2fr); gap:1.2rem; align-items:start; }\n    #shape-wait-lab .control-row { display:grid; grid-template-columns:3.8rem 1fr 2.5rem; gap:.55rem; align-items:center; margin:.45rem 0; }\n    #shape-wait-lab input[type=\"range\"] { width:100%; }\n    #shape-wait-lab .scenario-row { display:flex; flex-wrap:wrap; gap:.4rem; margin:.8rem 0; }\n    #shape-wait-lab button { border:1px solid #94a3b8; background:#fff; color:var(--ink); border-radius:6px; padding:.35rem .55rem; cursor:pointer; }\n    #shape-wait-lab button:hover, #shape-wait-lab button:focus { border-color:var(--blue); outline:none; }\n    #shape-wait-lab .metrics { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:.55rem; margin-top:.8rem; }\n    #shape-wait-lab .metric { background:#f6f8fb; border-radius:8px; padding:.55rem .65rem; }\n    #shape-wait-lab .metric span { display:block; color:var(--muted); font-size:.8rem; }\n    #shape-wait-lab .metric strong { font-size:1.08rem; font-variant-numeric:tabular-nums; }\n    #shape-wait-lab .formula-live { margin-top:.7rem; padding:.65rem .75rem; background:#f8fafc; border-left:4px solid var(--blue); font-variant-numeric:tabular-nums; }\n    #shape-wait-lab svg { width:100%; height:auto; display:block; }\n    #shape-wait-lab .legend { display:flex; gap:1rem; flex-wrap:wrap; color:#475569; font-size:.84rem; justify-content:center; }\n    #shape-wait-lab .swatch { display:inline-block; width:1.2rem; height:.18rem; margin-right:.3rem; vertical-align:.2rem; }\n    @media (max-width:760px) { #shape-wait-lab .lab-layout { grid-template-columns:1fr; } }\n  </style>\n  <div class=\"lab-shell\">\n    <p id=\"shape-lab-title\" class=\"lab-title\">Explorador de forma de cinco tiempos de espera</p>\n    <p class=\"lab-intro\">Cada control mueve una observación. La línea azul es la media y la naranja discontinua es la mediana.</p>\n    <div class=\"lab-layout\">\n      <div>\n        <div data-controls></div>\n        <div class=\"scenario-row\" aria-label=\"Escenarios preparados\">\n          <button type=\"button\" data-values=\"0,2,3,4,6\">Simétrica</button>\n          <button type=\"button\" data-values=\"2,2,2,2,7\">Cola derecha</button>\n          <button type=\"button\" data-values=\"0,5,5,5,5\">Cola izquierda</button>\n          <button type=\"button\" data-values=\"2,2,2,2,12\">Misma forma, otra escala</button>\n          <button type=\"button\" data-values=\"1,1,3,5,5\">Bimodal</button>\n        </div>\n        <div class=\"metrics\" aria-live=\"polite\">\n          <div class=\"metric\"><span>Media</span><strong data-mean></strong></div>\n          <div class=\"metric\"><span>Mediana</span><strong data-median></strong></div>\n          <div class=\"metric\"><span>Desviación √m₂</span><strong data-sd></strong></div>\n          <div class=\"metric\"><span>Asimetría g₁</span><strong data-skew></strong></div>\n          <div class=\"metric\"><span>Curtosis b₂</span><strong data-kurt></strong></div>\n          <div class=\"metric\"><span>Exceso g₂</span><strong data-excess></strong></div>\n        </div>\n        <div class=\"formula-live\" data-formula></div>\n      </div>\n      <div>\n        <svg data-plot viewBox=\"0 0 650 330\" role=\"img\" aria-label=\"Diagrama de puntos de los tiempos de espera\"></svg>\n        <div class=\"legend\"><span><i class=\"swatch\" style=\"background:#2563eb\"></i>media</span><span><i class=\"swatch\" style=\"background:#d97706;border-top:2px dashed #d97706;background:none\"></i>mediana</span></div>\n      </div>\n    </div>\n  </div>\n</div>\n<script>\n(() => {\n  const root=document.getElementById('shape-wait-lab'); if(!root)return;\n  const controls=root.querySelector('[data-controls]'), defaults=[2,2,2,2,7];\n  defaults.forEach((v,i)=>{const row=document.createElement('label');row.className='control-row';row.innerHTML=`<span>Cliente ${i+1}</span><input type=\"range\" min=\"0\" max=\"12\" step=\"1\" value=\"${v}\" data-x=\"${i}\"><output data-out=\"${i}\">${v}</output>`;controls.appendChild(row);});\n  const inputs=[...root.querySelectorAll('[data-x]')], svg=root.querySelector('[data-plot]'), NS='http://www.w3.org/2000/svg';\n  const sx=x=>55+(x/12)*550;\n  const add=(tag,attrs,text='')=>{const e=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));e.textContent=text;svg.appendChild(e);return e;};\n  const setText=(key,value)=>root.querySelector(`[data-${key}]`).textContent=value;\n  function update(){\n    const x=inputs.map((el,i)=>{const v=+el.value;root.querySelector(`[data-out=\"${i}\"]`).value=v;return v;}), n=x.length;\n    const sorted=[...x].sort((a,b)=>a-b), mean=x.reduce((a,b)=>a+b,0)/n, median=sorted[Math.floor(n/2)], d=x.map(v=>v-mean);\n    const m=r=>d.reduce((s,v)=>s+v**r,0)/n, m2=m(2), sd=Math.sqrt(m2), skew=m2>0?m(3)/m2**1.5:NaN, kurt=m2>0?m(4)/m2**2:NaN, excess=kurt-3;\n    setText('mean',mean.toFixed(2));setText('median',median.toFixed(2));setText('sd',sd.toFixed(2));setText('skew',Number.isFinite(skew)?skew.toFixed(3):'no definida');setText('kurt',Number.isFinite(kurt)?kurt.toFixed(3):'no definida');setText('excess',Number.isFinite(excess)?excess.toFixed(3):'no definido');\n    root.querySelector('[data-formula]').textContent=Number.isFinite(skew)?`g₁ = ${skew.toFixed(3)};  g₂ = ${excess.toFixed(3)}. Compare siempre estos números con el diagrama.`:'Todos los valores coinciden: m₂ = 0 y las medidas estandarizadas no están definidas.';\n    svg.replaceChildren();\n    for(let t=0;t<=12;t+=2){add('line',{x1:sx(t),x2:sx(t),y1:35,y2:275,stroke:'#e2e8f0','stroke-width':'1'});add('text',{x:sx(t),y:302,'text-anchor':'middle',fill:'#475569','font-size':'13'},t);}\n    add('line',{x1:55,x2:605,y1:275,y2:275,stroke:'#64748b','stroke-width':'2'});\n    add('line',{x1:sx(mean),x2:sx(mean),y1:38,y2:275,stroke:'#2563eb','stroke-width':'3'});\n    add('line',{x1:sx(median),x2:sx(median),y1:38,y2:275,stroke:'#d97706','stroke-width':'3','stroke-dasharray':'8 6'});\n    const used={};sorted.forEach((v,i)=>{used[v]=(used[v]||0)+1;const cy=250-(used[v]-1)*38;add('circle',{cx:sx(v),cy,r:'13',fill:'#16835f',stroke:'#fff','stroke-width':'2'});add('text',{x:sx(v),y:cy+4,'text-anchor':'middle',fill:'#fff','font-size':'10'},i+1);});\n    add('text',{x:330,y:326,'text-anchor':'middle',fill:'#475569','font-size':'13'},'Tiempo de espera (minutos)');\n  }\n  inputs.forEach(el=>el.addEventListener('input',update));\n  root.querySelectorAll('[data-values]').forEach(btn=>btn.addEventListener('click',()=>{btn.dataset.values.split(',').forEach((v,i)=>inputs[i].value=v);update();}));\n  update();\n})();\n</script>\n```\n:::\n\n::: {.content-visible unless-format=\"html\"}\nLa versión HTML incluye un laboratorio para mover cinco tiempos de espera. Los\nescenarios principales se resumen aquí:\n\n| Escenario | Datos | Media | $\\sqrt{m_2}$ | $g_1$ | $b_2$ | $g_2$ |\n|:---|:---|---:|---:|---:|---:|---:|\n| Simétrica | $0,2,3,4,6$ | 3 | 2 | 0 | 2.05 | -0.95 |\n| Cola derecha | $2,2,2,2,7$ | 3 | 2 | 1.50 | 3.25 | 0.25 |\n| Cola izquierda | $0,5,5,5,5$ | 4 | 2 | -1.50 | 3.25 | 0.25 |\n| Misma forma, otra escala | $2,2,2,2,12$ | 4 | 4 | 1.50 | 3.25 | 0.25 |\n| Bimodal | $1,1,3,5,5$ | 3 | 1.7889 | 0 | 1.25 | -1.75 |\n\nLos dos primeros escenarios tienen la misma media y escala, pero distinta\nforma. El segundo y el cuarto tienen distinta media y escala, pero los mismos\nmomentos estandarizados.\n:::\n\n## Curtosis y colas: una comparación controlada\n\nPara aislar la forma, compare tres modelos simétricos con media 0 y varianza 1:\n\n| Distribución | Exceso de curtosis | Comportamiento cualitativo de las colas |\n|:---|---:|:---|\n| Normal estándar | $0$ | decrecimiento rápido, proporcional a $e^{-x^2/2}$ en la densidad |\n| Laplace estandarizada | $3$ | decrecimiento exponencial en $\\lvert x\\rvert$ |\n| $t$ de Student con 5 grados de libertad, estandarizada | $6$ | decrecimiento polinómico |\n\nLas tres son simétricas y tienen la misma varianza. La diferencia está en\ncuánta probabilidad conservan lejos del centro. La $t_5$ genera extremos con\nmayor frecuencia que la normal; esto se refleja en una curtosis mayor. La\ncomparación funciona porque estamos examinando familias completas, no porque\nla curtosis permita reconstruir por sí sola todas sus colas.\n\n::: {.callout-warning appearance=\"minimal\"}\nDos distribuciones pueden tener la misma curtosis y formas diferentes. Además,\nsi $\\mathbb E[(X-\\mu)^4]$ no existe, la curtosis poblacional es infinita o no\nestá definida, aunque un programa siempre produzca algún número finito para\nuna muestra finita.\n:::\n\n## Gráficos que completan las medidas\n\n### Histograma, densidad y ECDF\n\nEl histograma muestra acumulaciones, huecos y posibles modos, pero cambia con\nel ancho y origen de los intervalos. Una estimación de densidad suaviza la\nforma y depende de un parámetro de suavizado. La función de distribución\nempírica (ECDF)[^ecdf] evita intervalos y conserva cada observación, aunque los\nmodos son menos visibles.\n\nConviene observar más de una representación. Una asimetría numérica elevada\npuede provenir de una cola gradual, de un solo dato erróneo o de mezclar dos\ngrupos; las acciones analíticas serían distintas.\n\n### Gráfico Q--Q\n\nUn gráfico Q--Q enfrenta los cuantiles observados con los cuantiles de una\ndistribución de referencia.[^qq] Si los datos son compatibles con una versión\ntrasladada y escalada de esa referencia, los puntos siguen aproximadamente\nuna recta. La pendiente refleja escala y el intercepto localización; curvaturas\nsistemáticas revelan diferencias de forma.\n\nEn un Q--Q normal:\n\n- separación fuerte en ambos extremos sugiere colas distintas de la normal;\n- una desviación más intensa en un solo extremo sugiere asimetría;\n- escalones o grupos pueden revelar redondeo, discreción o mezclas.\n\nLa rectitud no demuestra normalidad, sobre todo con pocas observaciones. Es una\ncomprobación visual que debe acompañarse de conocimiento del proceso y tamaño\nmuestral.\n\n## Transformar cambia la forma y la pregunta\n\nPara datos estrictamente positivos con asimetría derecha, una transformación\nlogarítmica puede comprimir valores grandes:\n\n$$\ny_i=\\log(x_i).\n$$\n\nEsto puede facilitar una visualización o estabilizar relaciones\nmultiplicativas, pero el análisis deja de estar en la escala original. Una\ndiferencia de una unidad en $\\log x$ representa una razón multiplicativa en\n$x$, no una diferencia aditiva.\n\nLas transformaciones monótonas[^monotona] preservan el orden, pero no preservan\ndistancias, media, varianza, asimetría ni curtosis. Por ello no se debe\n“normalizar” una variable automáticamente solo para reducir $g_1$. Antes hay\nque preguntar:\n\n1. ¿La nueva escala tiene sentido para el fenómeno?\n2. ¿Los ceros y valores negativos están tratados explícitamente?\n3. ¿La transformación se aprende y aplica dentro del mismo *pipeline*?\n4. ¿Las predicciones pueden regresar a la escala original sin introducir una\n   interpretación engañosa?\n\n## Implementación reproducible\n\nLa función siguiente hace explícita la convención de momentos con divisor\n$n$. También calcula las correcciones de las Ecs. 8 y 9 para mostrar por qué\ndos bibliotecas pueden entregar cifras distintas.\n\n::: {#39b5b19f .cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\n\ndef medidas_forma(valores):\n    x = np.asarray(valores, dtype=float)\n    if x.ndim != 1 or x.size == 0 or not np.isfinite(x).all():\n        raise ValueError(\"Se requiere un vector no vacío de valores finitos.\")\n\n    n = x.size\n    media = x.mean()\n    desviaciones = x - media\n    m2 = np.mean(desviaciones**2)\n    m3 = np.mean(desviaciones**3)\n    m4 = np.mean(desviaciones**4)\n\n    if m2 == 0:\n        g1 = g2 = G1 = G2 = np.nan\n    else:\n        g1 = m3 / m2**1.5\n        g2 = m4 / m2**2 - 3\n        G1 = np.sqrt(n * (n - 1)) / (n - 2) * g1 if n > 2 else np.nan\n        G2 = ((n - 1) / ((n - 2) * (n - 3))\n              * ((n + 1) * g2 + 6)) if n > 3 else np.nan\n\n    return pd.Series({\n        \"n\": n,\n        \"media\": media,\n        \"mediana\": np.median(x),\n        \"sqrt(m2)\": np.sqrt(m2),\n        \"g1_momentos\": g1,\n        \"G1_corregida\": G1,\n        \"b2_Pearson\": g2 + 3 if np.isfinite(g2) else np.nan,\n        \"g2_exceso\": g2,\n        \"G2_corregido\": G2,\n    })\n\nescenarios = {\n    \"Simétrica\": [0, 2, 3, 4, 6],\n    \"Cola derecha\": [2, 2, 2, 2, 7],\n    \"Cola izquierda\": [0, 5, 5, 5, 5],\n    \"Misma forma, otra escala\": [2, 2, 2, 2, 12],\n    \"Bimodal\": [1, 1, 3, 5, 5],\n}\n\nresumen_forma = pd.DataFrame({\n    nombre: medidas_forma(datos)\n    for nombre, datos in escenarios.items()\n}).T\n\nresumen_forma.round(4)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>n</th>\n      <th>media</th>\n      <th>mediana</th>\n      <th>sqrt(m2)</th>\n      <th>g1_momentos</th>\n      <th>G1_corregida</th>\n      <th>b2_Pearson</th>\n      <th>g2_exceso</th>\n      <th>G2_corregido</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Simétrica</th>\n      <td>5.0</td>\n      <td>3.0</td>\n      <td>3.0</td>\n      <td>2.0000</td>\n      <td>0.0</td>\n      <td>0.0000</td>\n      <td>2.05</td>\n      <td>-0.95</td>\n      <td>0.2</td>\n    </tr>\n    <tr>\n      <th>Cola derecha</th>\n      <td>5.0</td>\n      <td>3.0</td>\n      <td>2.0</td>\n      <td>2.0000</td>\n      <td>1.5</td>\n      <td>2.2361</td>\n      <td>3.25</td>\n      <td>0.25</td>\n      <td>5.0</td>\n    </tr>\n    <tr>\n      <th>Cola izquierda</th>\n      <td>5.0</td>\n      <td>4.0</td>\n      <td>5.0</td>\n      <td>2.0000</td>\n      <td>-1.5</td>\n      <td>-2.2361</td>\n      <td>3.25</td>\n      <td>0.25</td>\n      <td>5.0</td>\n    </tr>\n    <tr>\n      <th>Misma forma, otra escala</th>\n      <td>5.0</td>\n      <td>4.0</td>\n      <td>2.0</td>\n      <td>4.0000</td>\n      <td>1.5</td>\n      <td>2.2361</td>\n      <td>3.25</td>\n      <td>0.25</td>\n      <td>5.0</td>\n    </tr>\n    <tr>\n      <th>Bimodal</th>\n      <td>5.0</td>\n      <td>3.0</td>\n      <td>3.0</td>\n      <td>1.7889</td>\n      <td>0.0</td>\n      <td>0.0000</td>\n      <td>1.25</td>\n      <td>-1.75</td>\n      <td>-3.0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n### Las formas completas detrás de los momentos\n\nLas funciones de distribución empírica siguientes utilizan los mismos cinco\nescenarios de la tabla. Los escalones permiten comprobar dónde se acumulan o\nse separan sus observaciones.\n\n::: {#eb88b95b .cell execution_count=2}\n``` {.python .cell-code}\nimport plotly.express as px\nfrom IPython.display import HTML, display\n\ndef mostrar_plotly(figura):\n    \"\"\"Incrusta Plotly sin cargar una segunda versión de MathJax.\"\"\"\n    display(HTML(figura.to_html(\n        full_html=False,\n        include_plotlyjs=\"cdn\",\n        include_mathjax=False,\n    )))\n\nforma_larga = pd.DataFrame([\n    {\"Escenario\": nombre, \"Valor\": valor}\n    for nombre, valores in escenarios.items()\n    for valor in valores\n])\n\nfig = px.ecdf(\n    forma_larga,\n    x=\"Valor\",\n    facet_col=\"Escenario\",\n    facet_col_wrap=3,\n    markers=True,\n    title=\"Mismo centro o escala no implica la misma forma\",\n)\nfig.for_each_annotation(lambda a: a.update(text=a.text.split(\"=\")[-1]))\nfig.update_layout(showlegend=False)\nmostrar_plotly(fig)\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>                        <script>window.PlotlyConfig = {MathJaxConfig: 'local'};</script>\n        <script charset=\"utf-8\" src=\"https://cdn.plot.ly/plotly-3.4.0.min.js\" integrity=\"sha256-KEmPoupLpFyGMyGAiOsiNDbKDKAvxXAn/W+oQa0ZAfk=\" crossorigin=\"anonymous\"></script>                <div id=\"13deec9e-b29a-4e7d-bf98-25ad3fad847a\" class=\"plotly-graph-div\" style=\"height:100%; width:100%;\"></div>            <script>                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById(\"13deec9e-b29a-4e7d-bf98-25ad3fad847a\")) {                    Plotly.newPlot(                        \"13deec9e-b29a-4e7d-bf98-25ad3fad847a\",                        [{\"hovertemplate\":\"Escenario=Sim\\u00e9trica\\u003cbr\\u003eValor=%{x}\\u003cbr\\u003eprobability=%{y}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"legendgroup\":\"\",\"line\":{\"dash\":\"solid\",\"shape\":\"hv\"},\"marker\":{\"color\":\"#636efa\",\"symbol\":\"circle\"},\"mode\":\"lines+markers\",\"name\":\"\",\"orientation\":\"v\",\"showlegend\":false,\"x\":{\"dtype\":\"i1\",\"bdata\":\"AAIDBAY=\"},\"xaxis\":\"x4\",\"y\":{\"dtype\":\"f8\",\"bdata\":\"mpmZmZmZyT+amZmZmZnZPzMzMzMzM+M\\u002fmpmZmZmZ6T8AAAAAAADwPw==\"},\"yaxis\":\"y4\",\"type\":\"scatter\"},{\"hovertemplate\":\"Escenario=Cola derecha\\u003cbr\\u003eValor=%{x}\\u003cbr\\u003eprobability=%{y}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"legendgroup\":\"\",\"line\":{\"dash\":\"solid\",\"shape\":\"hv\"},\"marker\":{\"color\":\"#636efa\",\"symbol\":\"circle\"},\"mode\":\"lines+markers\",\"name\":\"\",\"orientation\":\"v\",\"showlegend\":false,\"x\":{\"dtype\":\"i1\",\"bdata\":\"AgICAgc=\"},\"xaxis\":\"x5\",\"y\":{\"dtype\":\"f8\",\"bdata\":\"mpmZmZmZyT+amZmZmZnZPzMzMzMzM+M\\u002fmpmZmZmZ6T8AAAAAAADwPw==\"},\"yaxis\":\"y5\",\"type\":\"scatter\"},{\"hovertemplate\":\"Escenario=Cola izquierda\\u003cbr\\u003eValor=%{x}\\u003cbr\\u003eprobability=%{y}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"legendgroup\":\"\",\"line\":{\"dash\":\"solid\",\"shape\":\"hv\"},\"marker\":{\"color\":\"#636efa\",\"symbol\":\"circle\"},\"mode\":\"lines+markers\",\"name\":\"\",\"orientation\":\"v\",\"showlegend\":false,\"x\":{\"dtype\":\"i1\",\"bdata\":\"AAUFBQU=\"},\"xaxis\":\"x6\",\"y\":{\"dtype\":\"f8\",\"bdata\":\"mpmZmZmZyT+amZmZmZnZPzMzMzMzM+M\\u002fmpmZmZmZ6T8AAAAAAADwPw==\"},\"yaxis\":\"y6\",\"type\":\"scatter\"},{\"hovertemplate\":\"Escenario=Misma forma, otra escala\\u003cbr\\u003eValor=%{x}\\u003cbr\\u003eprobability=%{y}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"legendgroup\":\"\",\"line\":{\"dash\":\"solid\",\"shape\":\"hv\"},\"marker\":{\"color\":\"#636efa\",\"symbol\":\"circle\"},\"mode\":\"lines+markers\",\"name\":\"\",\"orientation\":\"v\",\"showlegend\":false,\"x\":{\"dtype\":\"i1\",\"bdata\":\"AgICAgw=\"},\"xaxis\":\"x\",\"y\":{\"dtype\":\"f8\",\"bdata\":\"mpmZmZmZyT+amZmZmZnZPzMzMzMzM+M\\u002fmpmZmZmZ6T8AAAAAAADwPw==\"},\"yaxis\":\"y\",\"type\":\"scatter\"},{\"hovertemplate\":\"Escenario=Bimodal\\u003cbr\\u003eValor=%{x}\\u003cbr\\u003eprobability=%{y}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"legendgroup\":\"\",\"line\":{\"dash\":\"solid\",\"shape\":\"hv\"},\"marker\":{\"color\":\"#636efa\",\"symbol\":\"circle\"},\"mode\":\"lines+markers\",\"name\":\"\",\"orientation\":\"v\",\"showlegend\":false,\"x\":{\"dtype\":\"i1\",\"bdata\":\"AQEDBQU=\"},\"xaxis\":\"x2\",\"y\":{\"dtype\":\"f8\",\"bdata\":\"mpmZmZmZyT+amZmZmZnZPzMzMzMzM+M\\u002fmpmZmZmZ6T8AAAAAAADwPw==\"},\"yaxis\":\"y2\",\"type\":\"scatter\"}],                        {\"template\":{\"data\":{\"histogram2dcontour\":[{\"type\":\"histogram2dcontour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"choropleth\":[{\"type\":\"choropleth\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"histogram2d\":[{\"type\":\"histogram2d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmap\":[{\"type\":\"heatmap\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"contourcarpet\":[{\"type\":\"contourcarpet\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"contour\":[{\"type\":\"contour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"surface\":[{\"type\":\"surface\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"mesh3d\":[{\"type\":\"mesh3d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"scatter\":[{\"fillpattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2},\"type\":\"scatter\"}],\"parcoords\":[{\"type\":\"parcoords\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolargl\":[{\"type\":\"scatterpolargl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"bar\":[{\"error_x\":{\"color\":\"#2a3f5f\"},\"error_y\":{\"color\":\"#2a3f5f\"},\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"bar\"}],\"scattergeo\":[{\"type\":\"scattergeo\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolar\":[{\"type\":\"scatterpolar\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"histogram\":[{\"marker\":{\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"histogram\"}],\"scattergl\":[{\"type\":\"scattergl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatter3d\":[{\"type\":\"scatter3d\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermap\":[{\"type\":\"scattermap\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermapbox\":[{\"type\":\"scattermapbox\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterternary\":[{\"type\":\"scatterternary\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattercarpet\":[{\"type\":\"scattercarpet\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"carpet\":[{\"aaxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"baxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"type\":\"carpet\"}],\"table\":[{\"cells\":{\"fill\":{\"color\":\"#EBF0F8\"},\"line\":{\"color\":\"white\"}},\"header\":{\"fill\":{\"color\":\"#C8D4E3\"},\"line\":{\"color\":\"white\"}},\"type\":\"table\"}],\"barpolar\":[{\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"barpolar\"}],\"pie\":[{\"automargin\":true,\"type\":\"pie\"}]},\"layout\":{\"autotypenumbers\":\"strict\",\"colorway\":[\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\",\"#19d3f3\",\"#FF6692\",\"#B6E880\",\"#FF97FF\",\"#FECB52\"],\"font\":{\"color\":\"#2a3f5f\"},\"hovermode\":\"closest\",\"hoverlabel\":{\"align\":\"left\"},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#E5ECF6\",\"polar\":{\"bgcolor\":\"#E5ECF6\",\"angularaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"radialaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"ternary\":{\"bgcolor\":\"#E5ECF6\",\"aaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"baxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"caxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"coloraxis\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"colorscale\":{\"sequential\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"sequentialminus\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"diverging\":[[0,\"#8e0152\"],[0.1,\"#c51b7d\"],[0.2,\"#de77ae\"],[0.3,\"#f1b6da\"],[0.4,\"#fde0ef\"],[0.5,\"#f7f7f7\"],[0.6,\"#e6f5d0\"],[0.7,\"#b8e186\"],[0.8,\"#7fbc41\"],[0.9,\"#4d9221\"],[1,\"#276419\"]]},\"xaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"yaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"scene\":{\"xaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"yaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"zaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2}},\"shapedefaults\":{\"line\":{\"color\":\"#2a3f5f\"}},\"annotationdefaults\":{\"arrowcolor\":\"#2a3f5f\",\"arrowhead\":0,\"arrowwidth\":1},\"geo\":{\"bgcolor\":\"white\",\"landcolor\":\"#E5ECF6\",\"subunitcolor\":\"white\",\"showland\":true,\"showlakes\":true,\"lakecolor\":\"white\"},\"title\":{\"x\":0.05},\"mapbox\":{\"style\":\"light\"},\"margin\":{\"b\":0,\"l\":0,\"r\":0,\"t\":30}}},\"xaxis\":{\"anchor\":\"y\",\"domain\":[0.0,0.31999999999999995],\"title\":{\"text\":\"Valor\"}},\"yaxis\":{\"anchor\":\"x\",\"domain\":[0.0,0.46499999999999997],\"title\":{\"text\":\"probability\"},\"rangemode\":\"tozero\"},\"xaxis2\":{\"anchor\":\"y2\",\"domain\":[0.33999999999999997,0.6599999999999999],\"matches\":\"x\",\"title\":{\"text\":\"Valor\"}},\"yaxis2\":{\"anchor\":\"x2\",\"domain\":[0.0,0.46499999999999997],\"matches\":\"y\",\"showticklabels\":false,\"rangemode\":\"tozero\"},\"xaxis3\":{\"anchor\":\"y3\",\"domain\":[0.6799999999999999,0.9999999999999999],\"matches\":\"x\",\"title\":{\"text\":\"Valor\"}},\"yaxis3\":{\"anchor\":\"x3\",\"domain\":[0.0,0.46499999999999997],\"matches\":\"y\",\"showticklabels\":false,\"rangemode\":\"tozero\"},\"xaxis4\":{\"anchor\":\"y4\",\"domain\":[0.0,0.31999999999999995],\"matches\":\"x\",\"showticklabels\":false},\"yaxis4\":{\"anchor\":\"x4\",\"domain\":[0.5349999999999999,0.9999999999999999],\"matches\":\"y\",\"title\":{\"text\":\"probability\"},\"rangemode\":\"tozero\"},\"xaxis5\":{\"anchor\":\"y5\",\"domain\":[0.33999999999999997,0.6599999999999999],\"matches\":\"x\",\"showticklabels\":false},\"yaxis5\":{\"anchor\":\"x5\",\"domain\":[0.5349999999999999,0.9999999999999999],\"matches\":\"y\",\"showticklabels\":false,\"rangemode\":\"tozero\"},\"xaxis6\":{\"anchor\":\"y6\",\"domain\":[0.6799999999999999,0.9999999999999999],\"matches\":\"x\",\"showticklabels\":false},\"yaxis6\":{\"anchor\":\"x6\",\"domain\":[0.5349999999999999,0.9999999999999999],\"matches\":\"y\",\"showticklabels\":false,\"rangemode\":\"tozero\"},\"annotations\":[{\"font\":{},\"showarrow\":false,\"text\":\"Misma forma, otra escala\",\"x\":0.15999999999999998,\"xanchor\":\"center\",\"xref\":\"paper\",\"y\":0.46499999999999997,\"yanchor\":\"bottom\",\"yref\":\"paper\"},{\"font\":{},\"showarrow\":false,\"text\":\"Bimodal\",\"x\":0.49999999999999994,\"xanchor\":\"center\",\"xref\":\"paper\",\"y\":0.46499999999999997,\"yanchor\":\"bottom\",\"yref\":\"paper\"},{\"font\":{},\"showarrow\":false,\"text\":\"Sim\\u00e9trica\",\"x\":0.15999999999999998,\"xanchor\":\"center\",\"xref\":\"paper\",\"y\":0.9999999999999999,\"yanchor\":\"bottom\",\"yref\":\"paper\"},{\"font\":{},\"showarrow\":false,\"text\":\"Cola derecha\",\"x\":0.49999999999999994,\"xanchor\":\"center\",\"xref\":\"paper\",\"y\":0.9999999999999999,\"yanchor\":\"bottom\",\"yref\":\"paper\"},{\"font\":{},\"showarrow\":false,\"text\":\"Cola izquierda\",\"x\":0.8399999999999999,\"xanchor\":\"center\",\"xref\":\"paper\",\"y\":0.9999999999999999,\"yanchor\":\"bottom\",\"yref\":\"paper\"}],\"legend\":{\"tracegroupgap\":0},\"title\":{\"text\":\"Mismo centro o escala no implica la misma forma\"},\"showlegend\":false},                        {\"responsive\": true}                    )                };            </script>        </div>\n```\n:::\n:::\n\n\n::: {.callout-important appearance=\"minimal\"}\n### Del cálculo al programa\n\nEl algoritmo necesita primero la media y después las potencias de las\ndesviaciones. La estandarización divide $m_3$ por $m_2^{3/2}$ y $m_4$ por\n$m_2^2$. En datos reales se debe definir antes cómo tratar valores faltantes,\nponderaciones y grupos; eliminarlos silenciosamente cambia la distribución\nanalizada.\n:::\n\n## Qué implica la forma en minería de datos\n\n| Situación | Por qué importa la forma | Acción razonable |\n|:---|:---|:---|\n| Imputación | La media se desplaza hacia colas largas. | Comparar media, mediana y distribución por grupos antes de imputar. |\n| Detección de anomalías | Una regla basada en desviaciones estándar confunde colas pesadas con errores. | Usar cuantiles o métodos robustos y validar con el contexto. |\n| Modelos lineales | La normalidad suele concernir a errores o residuos, no a cada predictor. | Revisar residuos y especificación del modelo; no transformar por rutina. |\n| $k$-means y distancias | Extremos y escalas dominan distancias euclidianas. | Estandarizar y considerar escalamiento robusto; la estandarización no elimina asimetría. |\n| Árboles | Las divisiones por umbrales toleran transformaciones monótonas del predictor. | Aun así, revisar colas, soporte escaso y posibles errores de medición. |\n| Mezclas | Dos modos pueden representar subpoblaciones con mecanismos distintos. | Estratificar, añadir variables explicativas o modelar la mezcla. |\n\nEstandarizar mediante $z_i=(x_i-\\bar x)/s$ centra y cambia la escala, pero,\npor la Ec. 6, no vuelve simétrica una variable. **Estandarizar** y\n**normalizar en el sentido de hacer normal una distribución** no son la misma\noperación.\n\n## Guía de lectura\n\n| Pregunta | Herramienta principal | Precaución |\n|:---|:---|:---|\n| ¿Hacia qué lado se extiende la distribución? | Histograma/ECDF y $g_1$ | $g_1=0$ no demuestra simetría. |\n| ¿Hay más observaciones extremas que en una referencia? | Q--Q, cuantiles extremos y curtosis | La curtosis no describe por sí sola toda la cola ni el pico. |\n| ¿Hay uno o varios grupos? | Histograma, densidad y comparación por grupos | Asimetría y curtosis no determinan modalidad. |\n| ¿Conviene transformar? | Gráficos antes/después y sentido sustantivo de la escala | La transformación cambia la pregunta y debe formar parte del *pipeline*. |\n| ¿Puedo comparar software? | Definición, $n$, tratamiento de faltantes | Distinguir Pearson/Fisher y momento/corrección muestral. |\n\n## Puente al caso BigMart\n\nEl capítulo práctico [Medidas de forma en Big Mart Sales](2-5-forma_bigmart.qmd)\ntraslada esta secuencia a variables comerciales:\n\n1. observar primero la distribución y sus posibles subgrupos;\n2. comparar centro y escala sin confundirlos con forma;\n3. calcular asimetría y curtosis documentando la convención;\n4. inspeccionar colas con gráficos y cuantiles;\n5. evaluar transformaciones por su significado, no solo por reducir una cifra.\n\nLos datos cambian, pero la pregunta permanece: **¿qué estructura oculta una\nmedia y una desviación estándar?**\n\n## Ejercicios formativos\n\n1. **Cálculo completo.** Para $x=(1,1,1,3,4)$, calcule $\\bar x$, $m_2$,\n   $m_3$, $m_4$, $g_1$, $b_2$ y $g_2$. Interprete los signos antes de\n   usar software y luego verifique con `medidas_forma`.\n2. **Reflexión.** Construya la variable $y=10-x$ a partir del ejercicio\n   anterior. Prediga qué ocurrirá con media, desviación, $g_1$ y $g_2$, y\n   compruébelo mediante la Ec. 6.\n3. **Cero no significa simetría.** Verifique que\n   $(0,0,0,4,5,5,7)$ tiene $g_1=0$. Dibuje sus puntos y explique por qué no\n   es simétrica.\n4. **Mismo centro y escala.** Compruebe manualmente que las mañanas A y B\n   comparten media y $m_2$. Proponga una tercera muestra de cinco valores con\n   media 3 y $m_2=4$, pero con otra forma.\n5. **Curtosis no es pico.** Simule 10,000 observaciones de una normal, una\n   Laplace con escala $1/\\sqrt2$ y una $t_5$ multiplicada por\n   $\\sqrt{3/5}$. Compare varianza, exceso de curtosis, histogramas y Q--Q.\n6. **Modalidad.** Construya una muestra simétrica y bimodal. Muestre que su\n   asimetría puede ser cero y explique qué información no captura $g_1$.\n7. **Decisión de transformación.** Elija una variable positiva con asimetría\n   derecha. Compare la escala original y $\\log(x)$. Describa qué cambia en\n   la interpretación de una diferencia de una unidad y justifique cuál escala\n   usaría en un modelo.\n\n## Referencias {.unnumbered}\n\n::: {#refs}\n:::\n\n[^momento-central]: Un **momento central de orden $r$** es el promedio de las desviaciones respecto de la media elevadas a la potencia $r$. El orden 2 mide dispersión; los órdenes 3 y 4 participan en medidas de forma.\n[^distribucion]: Una **distribución** describe qué valores puede tomar una variable y con qué frecuencia o probabilidad aparecen. En una muestra se observa una versión finita de esa estructura.\n[^continua]: Una variable **continua** puede tomar valores en intervalos. Su densidad representa concentración de probabilidad por unidad; la probabilidad de un intervalo es el área bajo esa curva.\n[^cola]: Una **cola** es la región alejada del centro hacia valores pequeños o grandes. “Cola derecha larga” no significa que la mayoría de los datos estén a la derecha, sino que la extensión o probabilidad extrema es mayor en esa dirección.\n[^cuantil]: El cuantil de nivel $p$ es un valor que deja aproximadamente una proporción $p$ de observaciones por debajo. La mediana es el cuantil $0.5$.\n[^modo]: En datos discretos, un modo es un valor de frecuencia máxima. En una distribución continua se habla de máximos locales de la densidad; su estimación depende del suavizado y del tamaño muestral.\n[^variable-aleatoria]: Una **variable aleatoria** asigna un número a cada resultado posible de un fenómeno incierto. Su esperanza $\\mathbb E[X]$ es un promedio teórico ponderado por probabilidades.\n[^estimador]: Un **estimador** es una regla que usa una muestra para aproximar una cantidad poblacional. Su sesgo es la diferencia entre el valor que produciría en promedio bajo muestreo repetido y el parámetro que intenta estimar.\n[^ecdf]: La **función de distribución empírica** en $t$ es la proporción de observaciones menores o iguales que $t$. Es una función escalonada que no requiere elegir intervalos ni parámetros de suavizado.\n[^qq]: Un **cuantil--cuantil (Q--Q)** empareja cuantiles ordenados de los datos con cuantiles de una distribución de referencia. No compara frecuencias de barras, sino posiciones equivalentes dentro de ambas distribuciones.\n[^monotona]: Una transformación es **monótona creciente** si conserva el orden: $x_i<x_j\\Rightarrow f(x_i)<f(x_j)$. El logaritmo es creciente para valores positivos.\n\n",
    "supporting": [
      "2-5-forma_files/figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}