{
  "hash": "156caeacc34e23012984ae893be73bd4",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Medidas de forma en Big Mart Sales\"\nauthor: \"Diego Villalba\"\ndate: today\nlang: es\nnumber-sections: true\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: true\n    code-tools: true\n    code-summary: \"Mostrar código\"\n    page-layout: full\n  pdf:\n    toc: true\njupyter: python3\nbibliography: referencias_eda.bib\n---\n\n::: {.callout-tip appearance=\"minimal\"}\nEste caso aplica los conceptos presentados en [Medidas de forma](2-5-forma.qmd). Allí se distinguen asimetría, curtosis, multimodalidad y gráficos Q–Q.\n:::\n## Introducción\n\nEn una etapa inicial del análisis exploratorio de datos se estudian las **medidas de localización** y las **medidas de variabilidad** con el fin de identificar, respectivamente, el comportamiento central de una variable y el grado en que sus observaciones se dispersan alrededor de un valor representativo. Sin embargo, una descripción estadística rigurosa no se agota en estas dos dimensiones. Dos distribuciones pueden compartir una media y una desviación estándar semejantes, y aun así diferir de manera importante en su estructura global. Por ello es necesario incorporar el estudio de la **forma** de la distribución.\n\nLas medidas de forma permiten caracterizar aspectos tales como la **asimetría** y el grado de **concentración de masa alrededor del centro o en las colas**, usualmente descrito mediante la **curtosis**. En términos aplicados, estas medidas ayudan a responder preguntas como las siguientes: ¿la mayor parte de los productos tiene ventas moderadas con unos cuantos casos excepcionalmente altos?, ¿las observaciones se reparten de forma aproximadamente simétrica?, ¿aparecen colas pesadas o valores extremos frecuentes?, ¿una transformación puede facilitar la interpretación visual y estadística del fenómeno? Además, estas medidas orientan decisiones posteriores del EDA, como la revisión de valores atípicos, la conveniencia de usar medidas robustas o la necesidad de transformar variables para facilitar su análisis.\n\nEn este capítulo se estudian las **medidas de forma** en el dataset de BigMart, utilizando como variable principal `Item_Outlet_Sales`. No obstante, varias de las herramientas presentadas pueden aplicarse también a otras variables numéricas del conjunto de datos, como `Item_MRP`, `Item_Visibility` y `Item_Weight`.\n\n::: {.callout-note appearance=\"minimal\"}\n**Definición operativa.** La forma describe asimetría, colas y estructura modal después de considerar el centro y la escala de la distribución [@joanes1998skewness].\n:::\n\n## Preparación del entorno\n\nTrabajaremos con el siguiente [dataset BigMart](../../data/bigmart_sales.csv), usando Python, pandas, NumPy, SciPy y Plotly.\n\n::: {.cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport plotly.express as px\nimport plotly.graph_objects as go\nfrom scipy import stats\n\nDATA_PATH = \"../../data/bigmart_sales.csv\"\n\ndf = pd.read_csv(DATA_PATH)\ndf.head()\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Item_Identifier</th>\n      <th>Item_Weight</th>\n      <th>Item_Fat_Content</th>\n      <th>Item_Visibility</th>\n      <th>Item_Type</th>\n      <th>Item_MRP</th>\n      <th>Outlet_Identifier</th>\n      <th>Outlet_Establishment_Year</th>\n      <th>Outlet_Size</th>\n      <th>Outlet_Location_Type</th>\n      <th>Outlet_Type</th>\n      <th>Item_Outlet_Sales</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>FDA15</td>\n      <td>9.30</td>\n      <td>Low Fat</td>\n      <td>0.016047</td>\n      <td>Dairy</td>\n      <td>249.8092</td>\n      <td>OUT049</td>\n      <td>1999</td>\n      <td>Medium</td>\n      <td>Tier 1</td>\n      <td>Supermarket Type1</td>\n      <td>3735.1380</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>DRC01</td>\n      <td>5.92</td>\n      <td>Regular</td>\n      <td>0.019278</td>\n      <td>Soft Drinks</td>\n      <td>48.2692</td>\n      <td>OUT018</td>\n      <td>2009</td>\n      <td>Medium</td>\n      <td>Tier 3</td>\n      <td>Supermarket Type2</td>\n      <td>443.4228</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>FDN15</td>\n      <td>17.50</td>\n      <td>Low Fat</td>\n      <td>0.016760</td>\n      <td>Meat</td>\n      <td>141.6180</td>\n      <td>OUT049</td>\n      <td>1999</td>\n      <td>Medium</td>\n      <td>Tier 1</td>\n      <td>Supermarket Type1</td>\n      <td>2097.2700</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>FDX07</td>\n      <td>19.20</td>\n      <td>Regular</td>\n      <td>0.000000</td>\n      <td>Fruits and Vegetables</td>\n      <td>182.0950</td>\n      <td>OUT010</td>\n      <td>1998</td>\n      <td>NaN</td>\n      <td>Tier 3</td>\n      <td>Grocery Store</td>\n      <td>732.3800</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>NCD19</td>\n      <td>8.93</td>\n      <td>Low Fat</td>\n      <td>0.000000</td>\n      <td>Household</td>\n      <td>53.8614</td>\n      <td>OUT013</td>\n      <td>1987</td>\n      <td>High</td>\n      <td>Tier 3</td>\n      <td>Supermarket Type1</td>\n      <td>994.7052</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nAntes de proceder conviene verificar el tipo de las variables y concentrarnos en aquellas que sean cuantitativas.\n\n::: {.cell execution_count=2}\n``` {.python .cell-code}\ndf.info()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 8523 entries, 0 to 8522\nData columns (total 12 columns):\n #   Column                     Non-Null Count  Dtype  \n---  ------                     --------------  -----  \n 0   Item_Identifier            8523 non-null   object \n 1   Item_Weight                7060 non-null   float64\n 2   Item_Fat_Content           8523 non-null   object \n 3   Item_Visibility            8523 non-null   float64\n 4   Item_Type                  8523 non-null   object \n 5   Item_MRP                   8523 non-null   float64\n 6   Outlet_Identifier          8523 non-null   object \n 7   Outlet_Establishment_Year  8523 non-null   int64  \n 8   Outlet_Size                6113 non-null   object \n 9   Outlet_Location_Type       8523 non-null   object \n 10  Outlet_Type                8523 non-null   object \n 11  Item_Outlet_Sales          8523 non-null   float64\ndtypes: float64(4), int64(1), object(7)\nmemory usage: 799.2+ KB\n```\n:::\n:::\n\n\n::: {.cell execution_count=3}\n``` {.python .cell-code}\nnum_cols = df.select_dtypes(include=np.number).columns.tolist()\nnum_cols\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```\n['Item_Weight',\n 'Item_Visibility',\n 'Item_MRP',\n 'Outlet_Establishment_Year',\n 'Item_Outlet_Sales']\n```\n:::\n:::\n\n\n## Fundamentos teóricos\n\n### Asimetría\n\nLa asimetría describe el grado en que una distribución se desvía de la simetría respecto de su centro. Intuitivamente:\n\n- una distribución **simétrica** presenta masas comparables a la izquierda y derecha del centro;\n- una distribución con **asimetría positiva** presenta una cola más larga hacia valores altos;\n- una distribución con **asimetría negativa** presenta una cola más larga hacia valores bajos.\n\nUna medida común de asimetría es el coeficiente:\n\n$$\ng_1 = \\frac{\\frac{1}{n}\\sum_{i=1}^{n}(x_i-\\bar{x})^3}{\\left(\\frac{1}{n}\\sum_{i=1}^{n}(x_i-\\bar{x})^2\\right)^{3/2}}.\n$$\n\nCuando $g_1 > 0$, la cola derecha tiende a ser más extensa; cuando $g_1 < 0$, domina la cola izquierda; y cuando $g_1 \\approx 0$, la distribución puede considerarse aproximadamente simétrica, aunque esta interpretación siempre debe acompañarse de una inspección gráfica.\n\n### Curtosis\n\nLa curtosis resume el peso relativo de las colas y la concentración de observaciones alrededor del centro. Una expresión frecuente es:\n\n$$\ng_2 = \\frac{\\frac{1}{n}\\sum_{i=1}^{n}(x_i-\\bar{x})^4}{\\left(\\frac{1}{n}\\sum_{i=1}^{n}(x_i-\\bar{x})^2\\right)^2} - 3.\n$$\n\nLa resta de 3 permite comparar la distribución con la normal estándar:\n\n- si $g_2 \\approx 0$, la curtosis es similar a la de una normal;\n- si $g_2 > 0$, la distribución exhibe colas relativamente pesadas y mayor propensión a valores extremos;\n- si $g_2 < 0$, las colas son relativamente ligeras y la distribución resulta más plana.\n\nLa curtosis no debe leerse únicamente como “pico” central: en la práctica, suele ser más útil interpretarla en términos de **presencia de colas pesadas y extremos**.\n\n## Exploración gráfica inicial de la variable de ventas\n\nComenzamos con la variable de mayor interés económico: $\\texttt{Item\\_Outlet\\_Sales}$.\n\n::: {.cell execution_count=4}\n``` {.python .cell-code}\nsales = df[\"Item_Outlet_Sales\"].dropna()\n\nsales.describe()\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```\ncount     8523.000000\nmean      2181.288914\nstd       1706.499616\nmin         33.290000\n25%        834.247400\n50%       1794.331000\n75%       3101.296400\nmax      13086.964800\nName: Item_Outlet_Sales, dtype: float64\n```\n:::\n:::\n\n\n::: {.cell execution_count=5}\n``` {.python .cell-code}\nfig = px.histogram(\n    df,\n    x=\"Item_Outlet_Sales\",\n    nbins=50,\n    marginal=\"box\",\n    title=\"Distribución de Item_Outlet_Sales\"\n)\nfig.update_layout(bargap=0.05)\nfig.show()\n```\n\n::: {.cell-output .cell-output-display}\n```\nUnable to display output for mime type(s): text/html\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```\nUnable to display output for mime type(s): text/html\n```\n:::\n:::\n\n\nA partir del histograma y el boxplot, se pueden responder varias preguntas sobre la forma de la distribución.\n\nEn primer lugar, **no se observa simetría visual**. La distribución presenta una clara **asimetría positiva (sesgo a la derecha)**: la mayor parte de las observaciones se concentra en valores relativamente bajos, mientras que una cola se extiende hacia valores de ventas más altos.\n\nEn segundo lugar, **sí aparecen colas largas**, especialmente hacia la derecha. Esto indica que, aunque la mayoría de los productos presenta niveles de ventas moderados, existen algunos casos con ventas considerablemente mayores que el resto.\n\nEn tercer lugar, **se observan posibles valores extremos**, lo cual también se confirma en el boxplot superior, donde varios puntos aparecen fuera de los bigotes. Estos puntos corresponden a observaciones con ventas muy superiores al comportamiento típico.\n\nFinalmente, la gráfica muestra que **la masa principal de los datos se concentra en una región relativamente acotada**, aproximadamente en el rango bajo y medio de la distribución, mientras que un número reducido de observaciones alcanza valores de ventas mucho más altos. Esto sugiere que el comportamiento típico de las ventas está dominado por valores moderados, pero con algunos productos o combinaciones producto–tienda que generan ventas excepcionalmente elevadas.\n\nPara reforzar la interpretación puede añadirse una curva de densidad aproximada.\n\n::: {.cell execution_count=6}\n``` {.python .cell-code}\nimport numpy as np\nimport plotly.graph_objects as go\nfrom scipy import stats\n\nxs = np.linspace(sales.min(), sales.max(), 400)\nkde = stats.gaussian_kde(sales)\n\nfig = go.Figure()\n\n# Histograma en densidad\nfig.add_trace(\n    go.Histogram(\n        x=sales,\n        nbinsx=40,\n        histnorm=\"probability density\",\n        opacity=0.6,\n        name=\"Histograma\"\n    )\n)\n\n# Curva KDE\nfig.add_trace(\n    go.Scatter(\n        x=xs,\n        y=kde(xs),\n        mode=\"lines\",\n        name=\"Densidad estimada\",\n        line=dict(width=2)\n    )\n)\n\nfig.update_layout(\n    title=\"Histograma y densidad estimada de Item_Outlet_Sales\",\n    xaxis_title=\"Item_Outlet_Sales\",\n    yaxis_title=\"Densidad\",\n    bargap=0.02,\n    height=500,\n    width=900\n)\n\nfig.show()\n```\n\n::: {.cell-output .cell-output-display}\n```\nUnable to display output for mime type(s): text/html\n```\n:::\n:::\n\n\nLa superposición del histograma con la curva de densidad permite observar con mayor claridad la forma general de la distribución. Mientras el histograma muestra la frecuencia relativa por intervalos, la curva KDE suaviza esa información y ayuda a identificar la concentración principal de los datos, la presencia de asimetría y la posible existencia de colas largas.\n\n## Cálculo de asimetría y curtosis\n\n::: {.cell execution_count=7}\n``` {.python .cell-code}\nskew_sales = sales.skew()\nkurt_sales = sales.kurt()\n\npd.DataFrame({\n    \"medida\": [\"asimetría\", \"curtosis_exceso\"],\n    \"valor\": [skew_sales, kurt_sales]\n})\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>medida</th>\n      <th>valor</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>asimetría</td>\n      <td>1.177531</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>curtosis_exceso</td>\n      <td>1.615877</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nUna interpretación orientativa puede apoyarse en criterios simples:\n\n- $|\\text{asimetría}| < 0.5$: asimetría baja;\n- $0.5 \\le |\\text{asimetría}| < 1$: asimetría moderada;\n- $|\\text{asimetría}| \\ge 1$: asimetría marcada.\n\nEstos umbrales no son absolutos, pero ayudan a construir una primera lectura del fenómeno. En datasets comerciales es frecuente observar asimetría positiva: muchos productos exhiben ventas moderadas, mientras un grupo reducido alcanza ventas muy elevadas.\n\n## Comparación de forma en varias variables numéricas\n\nLa forma no tiene por qué ser igual en todas las variables del conjunto de datos. Conviene comparar la asimetría y curtosis de todas las columnas numéricas disponibles.\n\n::: {.cell execution_count=8}\n``` {.python .cell-code}\nshape_table = pd.DataFrame({\n    \"variable\": num_cols,\n    \"asimetria\": [df[c].dropna().skew() for c in num_cols],\n    \"curtosis_exceso\": [df[c].dropna().kurt() for c in num_cols]\n}).sort_values(\"asimetria\", key=np.abs, ascending=False)\n\nshape_table\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>variable</th>\n      <th>asimetria</th>\n      <th>curtosis_exceso</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>4</th>\n      <td>Item_Outlet_Sales</td>\n      <td>1.177531</td>\n      <td>1.615877</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Item_Visibility</td>\n      <td>1.167091</td>\n      <td>1.679445</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Outlet_Establishment_Year</td>\n      <td>-0.396641</td>\n      <td>-1.205694</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Item_MRP</td>\n      <td>0.127202</td>\n      <td>-0.889769</td>\n    </tr>\n    <tr>\n      <th>0</th>\n      <td>Item_Weight</td>\n      <td>0.082426</td>\n      <td>-1.227766</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {.cell execution_count=9}\n``` {.python .cell-code}\nfig = px.bar(\n    shape_table,\n    x=\"variable\",\n    y=\"asimetria\",\n    title=\"Asimetría por variable numérica\",\n    text_auto=True\n)\nfig.show()\n```\n\n::: {.cell-output .cell-output-display}\n```\nUnable to display output for mime type(s): text/html\n```\n:::\n:::\n\n\n::: {.cell execution_count=10}\n``` {.python .cell-code}\nfig = px.bar(\n    shape_table,\n    x=\"variable\",\n    y=\"curtosis_exceso\",\n    title=\"Curtosis (exceso) por variable numérica\",\n    text_auto=True\n)\nfig.show()\n```\n\n::: {.cell-output .cell-output-display}\n```\nUnable to display output for mime type(s): text/html\n```\n:::\n:::\n\n\nLa comparación de **asimetría** y **curtosis en exceso** muestra que no todas las variables numéricas presentan la misma estructura de forma. En particular, `Item_Outlet_Sales` exhibe una asimetría positiva de **1.177531** y una curtosis en exceso de **1.615877**, mientras que `Item_Visibility` presenta una asimetría de **1.167091** y una curtosis en exceso de **1.679445**. Estos valores sugieren distribuciones con **colas derechas largas** y una posible presencia de **valores extremos**, por lo que en ambas variables conviene reforzar el análisis con medidas robustas, boxplots y, si resulta útil, transformaciones como la logarítmica.\n\nEn cambio, `Item_MRP` muestra una asimetría mucho más baja (**0.127202**) y una curtosis en exceso negativa (**-0.889769**), mientras que `Item_Weight` presenta una asimetría de **0.082426** y una curtosis en exceso de **-1.227766**. Esto sugiere que ambas variables tienen una forma más cercana a la simetría y una distribución relativamente menos influida por colas pesadas.\n\nPor su parte, `Outlet_Establishment_Year` registra una asimetría negativa de **-0.396641** y una curtosis en exceso de **-1.205694**. Aunque su forma no parece especialmente extrema, esta variable requiere una interpretación adicional debido a su naturaleza temporal, ya que su análisis no debe basarse únicamente en criterios de distribución continua.\n\nEn conjunto, estos resultados indican que el EDA debe adaptarse a la forma específica de cada variable y no aplicar una misma lectura descriptiva a todas por igual.\n\n## Transformaciones y su efecto sobre la forma\n\nCuando una variable presenta fuerte asimetría positiva, una transformación logarítmica puede facilitar tanto la visualización como el modelado posterior. En el caso de las ventas, una opción práctica es usar:\n\n$$\ny^{\\ast} = \\log(1+y),\n$$\n\nque evita problemas cuando existen observaciones cercanas a cero.\n\n::: {.cell execution_count=11}\n``` {.python .cell-code}\ndf[\"log_Item_Outlet_Sales\"] = np.log1p(df[\"Item_Outlet_Sales\"])\nlog_sales = df[\"log_Item_Outlet_Sales\"].dropna()\n\npd.DataFrame({\n    \"variable\": [\"Item_Outlet_Sales\", \"log_Item_Outlet_Sales\"],\n    \"asimetria\": [sales.skew(), log_sales.skew()],\n    \"curtosis_exceso\": [sales.kurt(), log_sales.kurt()]\n})\n```\n\n::: {.cell-output .cell-output-display execution_count=11}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>variable</th>\n      <th>asimetria</th>\n      <th>curtosis_exceso</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Item_Outlet_Sales</td>\n      <td>1.177531</td>\n      <td>1.615877</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>log_Item_Outlet_Sales</td>\n      <td>-0.882266</td>\n      <td>0.532920</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {.cell execution_count=12}\n``` {.python .cell-code}\nfig = px.histogram(\n    df,\n    x=\"log_Item_Outlet_Sales\",\n    nbins=50,\n    marginal=\"box\",\n    title=\"Distribución de log(1 + Item_Outlet_Sales)\"\n)\nfig.show()\n```\n\n::: {.cell-output .cell-output-display}\n```\nUnable to display output for mime type(s): text/html\n```\n:::\n:::\n\n\n::: {.cell execution_count=13}\n``` {.python .cell-code}\nxs_log = np.linspace(log_sales.min(), log_sales.max(), 400)\nkde_log = stats.gaussian_kde(log_sales)\nfig = go.Figure()\nfig.add_trace(go.Histogram(\n    x=log_sales, nbinsx=40, histnorm=\"probability density\",\n    opacity=0.55, name=\"Histograma\"\n))\nfig.add_trace(go.Scatter(\n    x=xs_log, y=kde_log(xs_log), mode=\"lines\",\n    line=dict(width=3), name=\"Densidad KDE\"\n))\nfig.update_layout(\n    title=\"Histograma y densidad de log(1 + Item_Outlet_Sales)\",\n    xaxis_title=\"log(1 + Item_Outlet_Sales)\", yaxis_title=\"Densidad\",\n    barmode=\"overlay\"\n)\nfig.show()\n```\n\n::: {.cell-output .cell-output-display}\n```\nUnable to display output for mime type(s): text/html\n```\n:::\n:::\n\n\nLa comparación entre la variable original y su versión transformada permite mostrar un punto importante del EDA: las medidas de forma no son meramente descriptivas, también orientan decisiones analíticas posteriores. Si la asimetría disminuye sustancialmente bajo la transformación, esto sugiere una representación más equilibrada del fenómeno.\n\nEn particular, una **transformación logarítmica** puede ser útil cuando la distribución presenta una **asimetría positiva marcada**, es decir, cuando existen valores muy altos que alargan la cola derecha de la distribución. Al aplicar el logaritmo, los valores grandes se comprimen relativamente más que los valores pequeños, lo que tiende a reducir la asimetría y a concentrar mejor los datos alrededor del centro.\n\nDesde el punto de vista del EDA, esta transformación ayuda a:\n\n- **visualizar mejor la estructura de la distribución**, evitando que unos pocos valores muy grandes dominen el gráfico;\n- **comparar observaciones en términos relativos**, ya que las diferencias en escala logarítmica representan cambios proporcionales;\n- **reducir la influencia de valores extremos**, facilitando una lectura más clara del comportamiento típico de los datos.\n\nAdemás, esta transformación puede ser útil para **análisis posteriores**, especialmente cuando se emplean métodos estadísticos o modelos que funcionan mejor con distribuciones más simétricas o con variabilidad más estable. En contextos de modelado, por ejemplo, trabajar con una variable transformada puede mejorar la interpretación de los resultados, estabilizar la varianza y facilitar el ajuste de modelos lineales o regresiones.\n\nEn síntesis, el uso del logaritmo en el EDA no solo mejora la interpretación visual de distribuciones muy asimétricas, sino que también prepara los datos para etapas posteriores del análisis, donde una representación más equilibrada de la variable puede resultar analíticamente más conveniente.\n\n## Gráfico cuantil-cuantil como apoyo visual\n\nOtra herramienta útil para estudiar la forma es el gráfico Q-Q frente a la distribución normal. No debe interpretarse como una prueba definitiva, pero sí como un recurso visual para detectar desviaciones sistemáticas respecto a simetría y colas gaussianas.\n\n::: {.cell execution_count=14}\n``` {.python .cell-code}\ndef qq_plotly(x, titulo):\n    (teoricos, observados), (pendiente, intercepto, _) = stats.probplot(x, dist=\"norm\")\n    linea_x = np.array([teoricos.min(), teoricos.max()])\n    fig = go.Figure()\n    fig.add_trace(go.Scatter(x=teoricos, y=observados, mode=\"markers\", name=\"Cuantiles\"))\n    fig.add_trace(go.Scatter(\n        x=linea_x, y=intercepto + pendiente * linea_x,\n        mode=\"lines\", name=\"Referencia normal\", line=dict(dash=\"dash\")\n    ))\n    fig.update_layout(title=titulo, xaxis_title=\"Cuantiles teóricos\",\n                      yaxis_title=\"Cuantiles observados\")\n    return fig\n\nqq_plotly(sales, \"Gráfico Q-Q de Item_Outlet_Sales\").show()\n```\n\n::: {.cell-output .cell-output-display}\n```\nUnable to display output for mime type(s): text/html\n```\n:::\n:::\n\n\n::: {.cell execution_count=15}\n``` {.python .cell-code}\nqq_plotly(log_sales, \"Gráfico Q-Q de log(1 + Item_Outlet_Sales)\").show()\n```\n\n::: {.cell-output .cell-output-display}\n```\nUnable to display output for mime type(s): text/html\n```\n:::\n:::\n\n\nSi la versión transformada se alinea mejor con la recta de referencia que la variable original, ello aporta evidencia visual de una mejora en la regularidad de la forma, aunque no implica normalidad perfecta.\n\n## Mini-dashboard de forma\n\nLa siguiente sección integra un dashboard simple para resumir la forma de la variable de ventas y su transformación.\n\n::: {.cell execution_count=16}\n``` {.python .cell-code}\nfrom plotly.subplots import make_subplots\n\nfig = make_subplots(\n    rows=2,\n    cols=2,\n    subplot_titles=(\n        \"Ventas originales\",\n        \"Ventas transformadas con log(1+y)\",\n        \"Asimetría comparada\",\n        \"Curtosis comparada\"\n    )\n)\n\nfig.add_trace(\n    go.Histogram(x=sales, nbinsx=40, name=\"Ventas originales\"),\n    row=1, col=1\n)\nfig.add_trace(\n    go.Histogram(x=log_sales, nbinsx=40, name=\"Ventas log\"),\n    row=1, col=2\n)\nfig.add_trace(\n    go.Bar(\n        x=[\"Original\", \"Log\"],\n        y=[sales.skew(), log_sales.skew()],\n        name=\"Asimetría\"\n    ),\n    row=2, col=1\n)\nfig.add_trace(\n    go.Bar(\n        x=[\"Original\", \"Log\"],\n        y=[sales.kurt(), log_sales.kurt()],\n        name=\"Curtosis\"\n    ),\n    row=2, col=2\n)\n\nfig.update_layout(\n    title=\"Dashboard básico de medidas de forma\",\n    height=700,\n    showlegend=False\n)\nfig.show()\n```\n\n::: {.cell-output .cell-output-display}\n```\nUnable to display output for mime type(s): text/html\n```\n:::\n:::\n\n\n",
    "supporting": [
      "2-5-forma_bigmart_files/figure-pdf"
    ],
    "filters": []
  }
}