{
  "hash": "9dbc9dda05c68a945fe0407a70a5a7e3",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Conversión de Datos, Codificación y Escalado\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    toc-title: \"Contenido\"\n    code-fold: true\n    code-tools: true\n    theme: cosmo\n    highlight-style: github\nexecute:\n  echo: true\n  warning: false\n  message: false\njupyter: python3\n---\n\n<!--\nKit compartido de los laboratorios interactivos de la unidad de preprocesamiento.\nCada capítulo lo incluye con el shortcode include de Quarto, al inicio.\nDefine estilos (modo claro/oscuro de Quarto) y window.LabKit: utilidades\nnuméricas y un pequeño graficador SVG sin dependencias externas.\n-->\n::: {.content-visible when-format=\"html\"}\n```{=html}\n<style>\n.plab {\n  --lab-bg: #ffffff; --lab-surface: #f6f8fa; --lab-border: #d0d7de;\n  --lab-text: #1f2328; --lab-muted: #59636e; --lab-grid: #e6e9ed; --lab-axis: #8c959f;\n  --lab-accent: #0969da; --lab-accent-soft: #ddf4ff;\n  --lab-s1: #2563eb; --lab-s2: #ea580c; --lab-s3: #16a34a; --lab-s4: #7c3aed; --lab-s5: #dc2626;\n  --lab-good: #1a7f37; --lab-good-soft: #dafbe1; --lab-warn: #9a6700; --lab-warn-soft: #fff8c5;\n  --lab-bad: #cf222e; --lab-bad-soft: #ffebe9;\n  border: 1px solid var(--lab-border); border-radius: 10px; background: var(--lab-bg);\n  color: var(--lab-text); padding: 1.1rem 1.2rem 1.2rem; margin: 1.5rem 0;\n  font-family: system-ui, -apple-system, \"Segoe UI\", Roboto, sans-serif; font-size: 0.92rem; line-height: 1.45;\n}\nbody.quarto-dark .plab {\n  --lab-bg: #1b1f24; --lab-surface: #22272e; --lab-border: #3d444d;\n  --lab-text: #e6edf3; --lab-muted: #9ea7b3; --lab-grid: #2d333b; --lab-axis: #768390;\n  --lab-accent: #58a6ff; --lab-accent-soft: #1c2d41;\n  --lab-s1: #60a5fa; --lab-s2: #fb923c; --lab-s3: #4ade80; --lab-s4: #a78bfa; --lab-s5: #f87171;\n  --lab-good: #3fb950; --lab-good-soft: #1b2f23; --lab-warn: #d29922; --lab-warn-soft: #2e2716;\n  --lab-bad: #f85149; --lab-bad-soft: #3a1d1f;\n}\n.plab * { box-sizing: border-box; }\n.plab-eyebrow { font-size: 0.72rem; letter-spacing: .08em; text-transform: uppercase; color: var(--lab-accent); font-weight: 700; margin: 0; }\n.plab h3.plab-title, .plab .plab-title { font-size: 1.12rem; margin: .15rem 0 .35rem; border: 0; padding: 0; color: var(--lab-text); }\n.plab-sub { color: var(--lab-muted); margin: 0 0 .9rem; }\n.plab-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(260px, 1fr)); gap: 1rem; align-items: start; }\n.plab-grid.wide-left { grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); }\n.plab-panel { background: var(--lab-surface); border: 1px solid var(--lab-border); border-radius: 8px; padding: .8rem .9rem; min-width: 0; }\n.plab-panel h4 { font-size: .95rem; margin: 0 0 .5rem; color: var(--lab-text); }\n.plab-controls { display: flex; flex-wrap: wrap; gap: .7rem 1.2rem; align-items: flex-end; margin-bottom: .8rem; }\n.plab-controls > label, .plab-field { display: flex; flex-direction: column; gap: .2rem; font-size: .82rem; color: var(--lab-muted); min-width: 150px; flex: 1 1 150px; }\n.plab-controls b, .plab-field b { color: var(--lab-text); font-variant-numeric: tabular-nums; }\n.plab input[type=range] { width: 100%; accent-color: var(--lab-accent); }\n.plab select, .plab input[type=number] {\n  background: var(--lab-bg); color: var(--lab-text); border: 1px solid var(--lab-border);\n  border-radius: 6px; padding: .3rem .4rem; font-size: .85rem;\n}\n.plab input[type=number] { width: 4.6rem; text-align: center; }\n.plab-seg { display: inline-flex; flex-wrap: wrap; border: 1px solid var(--lab-border); border-radius: 7px; overflow: hidden; }\n.plab-seg button, .plab-btn {\n  background: var(--lab-bg); color: var(--lab-text); border: 0; border-right: 1px solid var(--lab-border);\n  padding: .35rem .7rem; font-size: .82rem; cursor: pointer; font-family: inherit;\n}\n.plab-seg button:last-child { border-right: 0; }\n.plab-seg button[aria-pressed=true] { background: var(--lab-accent); color: #fff; }\nbody.quarto-dark .plab-seg button[aria-pressed=true] { color: #0d1117; }\n.plab-btn { border: 1px solid var(--lab-border); border-radius: 7px; }\n.plab-btn:hover, .plab-seg button:hover { filter: brightness(0.96); }\n.plab-btn.primary { background: var(--lab-accent); color: #fff; border-color: var(--lab-accent); }\nbody.quarto-dark .plab-btn.primary { color: #0d1117; }\n.plab button:focus-visible, .plab input:focus-visible, .plab select:focus-visible { outline: 2px solid var(--lab-accent); outline-offset: 2px; }\n.plab-stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(120px, 1fr)); gap: .5rem; margin: .7rem 0; }\n.plab-stat { background: var(--lab-bg); border: 1px solid var(--lab-border); border-radius: 7px; padding: .45rem .6rem; }\n.plab-stat span { display: block; font-size: .72rem; color: var(--lab-muted); }\n.plab-stat strong { font-size: 1.08rem; font-variant-numeric: tabular-nums; color: var(--lab-text); }\n.plab-note { border-left: 3px solid var(--lab-accent); background: var(--lab-accent-soft); padding: .5rem .7rem; border-radius: 0 6px 6px 0; margin: .7rem 0 0; font-size: .85rem; }\n.plab-note.good { border-color: var(--lab-good); background: var(--lab-good-soft); }\n.plab-note.warn { border-color: var(--lab-warn); background: var(--lab-warn-soft); }\n.plab-note.bad { border-color: var(--lab-bad); background: var(--lab-bad-soft); }\n.plab-table { width: 100%; border-collapse: collapse; font-size: .82rem; font-variant-numeric: tabular-nums; margin: 0; }\n.plab-table th, .plab-table td { border-bottom: 1px solid var(--lab-border); padding: .3rem .45rem; text-align: right; color: var(--lab-text); background: transparent; }\n.plab-table th { color: var(--lab-muted); font-weight: 600; }\n.plab-table th:first-child, .plab-table td:first-child { text-align: left; }\n.plab-table .hl { background: var(--lab-accent-soft); font-weight: 700; }\n.plab-scroll { overflow-x: auto; }\n.plab-steps { display: flex; flex-wrap: wrap; gap: .35rem; margin-bottom: .7rem; }\n.plab-steps button { border: 1px solid var(--lab-border); background: var(--lab-bg); color: var(--lab-text); border-radius: 999px; padding: .25rem .7rem; font-size: .8rem; cursor: pointer; font-family: inherit; }\n.plab-steps button[aria-pressed=true] { background: var(--lab-accent); border-color: var(--lab-accent); color: #fff; }\nbody.quarto-dark .plab-steps button[aria-pressed=true] { color: #0d1117; }\n.plab-math { font-family: \"Fira Mono\", ui-monospace, monospace; font-size: .85rem; background: var(--lab-bg); border: 1px solid var(--lab-border); border-radius: 6px; padding: .5rem .7rem; overflow-x: auto; white-space: pre; margin: .5rem 0 0; }\n.plab-legend { display: flex; flex-wrap: wrap; gap: .3rem 1rem; font-size: .78rem; color: var(--lab-muted); margin-top: .35rem; }\n.plab-legend i { display: inline-block; width: 14px; height: 4px; border-radius: 2px; vertical-align: middle; margin-right: .3rem; }\n.plab-legend i.dot { width: 9px; height: 9px; border-radius: 50%; }\n.plab-task { margin: .9rem 0 0; padding-left: 1.2rem; color: var(--lab-text); font-size: .86rem; }\n.plab-task li { margin-bottom: .25rem; }\n@media (max-width: 480px) {\n  .plab { padding: .8rem .7rem 1rem; }\n  .plab-panel { padding: .6rem .55rem; }\n  .plab-controls > label, .plab-field { min-width: 120px; }\n}\n/* Gráficas SVG */\n.plab svg.plab-chart { width: 100%; max-width: 460px; height: auto; display: block; margin: 0 auto; overflow: visible; touch-action: none; }\n.plab svg.plab-chart.wide { max-width: 640px; }\n.plab svg text { pointer-events: none; fill: var(--lab-muted); font-size: 11px; font-family: system-ui, sans-serif; }\n.plab svg text.strong { fill: var(--lab-text); font-weight: 600; }\n.plab svg .grid { stroke: var(--lab-grid); stroke-width: 1; }\n.plab svg .axis { stroke: var(--lab-axis); stroke-width: 1; }\n.plab svg .zero { stroke: var(--lab-axis); stroke-width: 1.2; stroke-dasharray: 3 3; }\n.plab svg .s1 { stroke: var(--lab-s1); fill: var(--lab-s1); }\n.plab svg .s2 { stroke: var(--lab-s2); fill: var(--lab-s2); }\n.plab svg .s3 { stroke: var(--lab-s3); fill: var(--lab-s3); }\n.plab svg .s4 { stroke: var(--lab-s4); fill: var(--lab-s4); }\n.plab svg .s5 { stroke: var(--lab-s5); fill: var(--lab-s5); }\n.plab svg .muted { stroke: var(--lab-axis); fill: var(--lab-axis); }\n.plab svg .line { fill: none !important; stroke-width: 2.2; stroke-linecap: round; stroke-linejoin: round; }\n.plab svg .dash { stroke-dasharray: 5 4; }\n.plab svg .thin { stroke-width: 1.2; }\n.plab svg .soft { fill-opacity: .18; }\n.plab svg .ghost { fill-opacity: .35; stroke-opacity: .35; }\n.plab svg .dot { stroke: var(--lab-bg); stroke-width: 1.5; }\n.plab svg .drag { cursor: grab; }\n.plab svg .drag:active { cursor: grabbing; }\n.plab svg text.s1 { fill: var(--lab-s1); stroke: none; }\n.plab svg text.s2 { fill: var(--lab-s2); stroke: none; }\n.plab svg text.s3 { fill: var(--lab-s3); stroke: none; }\n.plab svg text.s5 { fill: var(--lab-s5); stroke: none; }\n</style>\n<script>\nwindow.LabKit = window.LabKit || (() => {\n  const NS = 'http://www.w3.org/2000/svg';\n  const sum = a => a.reduce((s, v) => s + v, 0);\n  const mean = a => sum(a) / a.length;\n  const variance = (a, ddof = 0) => { const m = mean(a); return sum(a.map(v => (v - m) ** 2)) / (a.length - ddof); };\n  const sd = (a, ddof = 0) => Math.sqrt(variance(a, ddof));\n  // Percentil con interpolación lineal (convención de numpy.percentile por defecto).\n  const quantile = (a, q) => {\n    const s = [...a].sort((x, y) => x - y), pos = (s.length - 1) * q, lo = Math.floor(pos), hi = Math.ceil(pos);\n    return s[lo] + (s[hi] - s[lo]) * (pos - lo);\n  };\n  const median = a => quantile(a, 0.5);\n  const clamp = (v, lo, hi) => Math.min(hi, Math.max(lo, v));\n  const fmt = (v, d = 2) => (v === null || v === undefined || Number.isNaN(v)) ? '—'\n    : Number(v).toLocaleString('es-MX', { minimumFractionDigits: d, maximumFractionDigits: d });\n  // Generador pseudoaleatorio reproducible (mulberry32) y normal estándar (Box-Muller).\n  const rng = seed => {\n    let t = seed >>> 0;\n    const u = () => { t += 0x6D2B79F5; let r = Math.imul(t ^ (t >>> 15), 1 | t); r ^= r + Math.imul(r ^ (r >>> 7), 61 | r); return ((r ^ (r >>> 14)) >>> 0) / 4294967296; };\n    u.normal = () => { let a = 0, b = 0; while (a === 0) a = u(); while (b === 0) b = u(); return Math.sqrt(-2 * Math.log(a)) * Math.cos(2 * Math.PI * b); };\n    return u;\n  };\n  const niceTicks = (lo, hi, n = 5) => {\n    if (hi === lo) { hi = lo + 1; }\n    const raw = (hi - lo) / n, mag = 10 ** Math.floor(Math.log10(raw)), f = raw / mag;\n    const step = (f >= 5 ? 10 : f >= 2 ? 5 : f >= 1 ? 2 : 1) * mag;\n    const out = [];\n    for (let v = Math.ceil(lo / step - 1e-9) * step; v <= hi + 1e-9; v += step) out.push(Math.abs(v) < step * 1e-9 ? 0 : v);\n    return out;\n  };\n  const el = (tag, attrs = {}, parent) => {\n    const node = document.createElementNS(NS, tag);\n    for (const [k, v] of Object.entries(attrs)) if (v !== undefined && v !== null) node.setAttribute(k, v);\n    if (parent) parent.appendChild(node);\n    return node;\n  };\n  // Graficador mínimo: escala lineal, ejes, rejilla y primitivas.\n  function chart(svg, opts) {\n    const W = opts.width || 480, H = opts.height || 300;\n    const m = Object.assign({ top: 14, right: 14, bottom: 38, left: 48 }, opts.margin || {});\n    svg.setAttribute('viewBox', `0 0 ${W} ${H}`);\n    svg.classList.add('plab-chart');\n    svg.replaceChildren();\n    const [x0, x1] = opts.x, [y0, y1] = opts.y;\n    const iw = W - m.left - m.right, ih = H - m.top - m.bottom;\n    const X = v => m.left + (v - x0) / (x1 - x0) * iw;\n    const Y = v => m.top + ih - (v - y0) / (y1 - y0) * ih;\n    const c = {\n      svg, X, Y, W, H, m, iw, ih,\n      invX: px => x0 + (px - m.left) / iw * (x1 - x0),\n      invY: py => y0 + (m.top + ih - py) / ih * (y1 - y0),\n      g: el('g', {}, svg),\n      axes({ xTicks = 5, yTicks = 5, xLabel = '', yLabel = '', xFmt = v => fmt(v, Math.abs(v) < 10 && v % 1 ? 1 : 0), yFmt, grid = true, xCats } = {}) {\n        const ax = el('g', {}, svg); svg.insertBefore(ax, c.g);\n        const yf = yFmt || xFmt;\n        if (yTicks) niceTicks(y0, y1, yTicks).forEach(t => {\n          if (grid) el('line', { x1: m.left, x2: m.left + iw, y1: Y(t), y2: Y(t), class: 'grid' }, ax);\n          el('text', { x: m.left - 6, y: Y(t) + 3.5, 'text-anchor': 'end' }, ax).textContent = yf(t);\n        });\n        if (xCats) xCats.forEach(([v, lab]) => { el('text', { x: X(v), y: m.top + ih + 16, 'text-anchor': 'middle' }, ax).textContent = lab; });\n        else if (xTicks) niceTicks(x0, x1, xTicks).forEach(t => {\n          if (grid) el('line', { x1: X(t), x2: X(t), y1: m.top, y2: m.top + ih, class: 'grid' }, ax);\n          el('text', { x: X(t), y: m.top + ih + 16, 'text-anchor': 'middle' }, ax).textContent = xFmt(t);\n        });\n        el('line', { x1: m.left, x2: m.left + iw, y1: m.top + ih, y2: m.top + ih, class: 'axis' }, ax);\n        el('line', { x1: m.left, x2: m.left, y1: m.top, y2: m.top + ih, class: 'axis' }, ax);\n        if (xLabel) el('text', { x: m.left + iw / 2, y: H - 4, 'text-anchor': 'middle', class: 'strong' }, ax).textContent = xLabel;\n        if (yLabel) el('text', { x: 12, y: m.top + ih / 2, 'text-anchor': 'middle', transform: `rotate(-90 12 ${m.top + ih / 2})`, class: 'strong' }, ax).textContent = yLabel;\n        return c;\n      },\n      zeroLines() {\n        if (x0 < 0 && x1 > 0) el('line', { x1: X(0), x2: X(0), y1: m.top, y2: m.top + ih, class: 'zero' }, c.g);\n        if (y0 < 0 && y1 > 0) el('line', { x1: m.left, x2: m.left + iw, y1: Y(0), y2: Y(0), class: 'zero' }, c.g);\n        return c;\n      },\n      path(points, cls = 's1 line') {\n        const d = points.filter(p => p && Number.isFinite(p[1])).map((p, i) => `${i ? 'L' : 'M'}${X(p[0]).toFixed(1)},${Y(p[1]).toFixed(1)}`).join('');\n        return el('path', { d, class: cls }, c.g);\n      },\n      line(xa, ya, xb, yb, cls = 's1 line') { return el('line', { x1: X(xa), y1: Y(ya), x2: X(xb), y2: Y(yb), class: cls }, c.g); },\n      dot(x, y, r = 5, cls = 's1 dot') { return el('circle', { cx: X(x), cy: Y(y), r, class: cls }, c.g); },\n      rect(xa, ya, xb, yb, cls = 's1 soft') {\n        return el('rect', { x: Math.min(X(xa), X(xb)), y: Math.min(Y(ya), Y(yb)), width: Math.abs(X(xb) - X(xa)), height: Math.abs(Y(yb) - Y(ya)), class: cls }, c.g);\n      },\n      text(x, y, s, attrs = {}) { const t = el('text', Object.assign({ x: X(x), y: Y(y) }, attrs), c.g); t.textContent = s; return t; },\n      arrow(xa, ya, xb, yb, cls = 's1') {\n        const ax = X(xa), ay = Y(ya), bx = X(xb), by = Y(yb), ang = Math.atan2(by - ay, bx - ax), h = 8;\n        el('line', { x1: ax, y1: ay, x2: bx, y2: by, class: cls + ' line' }, c.g);\n        el('path', { d: `M${bx},${by}L${bx - h * Math.cos(ang - 0.4)},${by - h * Math.sin(ang - 0.4)}L${bx - h * Math.cos(ang + 0.4)},${by - h * Math.sin(ang + 0.4)}Z`, class: cls }, c.g);\n      },\n      // Convierte un evento de puntero a coordenadas de datos.\n      pointer(evt) {\n        const pt = svg.createSVGPoint(); pt.x = evt.clientX; pt.y = evt.clientY;\n        const p = pt.matrixTransform(svg.getScreenCTM().inverse());\n        return [c.invX(p.x), c.invY(p.y)];\n      }\n    };\n    svg.__chart = c;\n    return c;\n  }\n  // Botones segmentados: devuelve un getter del valor activo.\n  function segmented(container, onChange) {\n    const buttons = [...container.querySelectorAll('button')];\n    let value = (buttons.find(b => b.getAttribute('aria-pressed') === 'true') || buttons[0]).dataset.value;\n    const set = v => { value = v; buttons.forEach(b => b.setAttribute('aria-pressed', String(b.dataset.value === v))); };\n    set(value);\n    buttons.forEach(b => b.addEventListener('click', () => { set(b.dataset.value); onChange && onChange(value); }));\n    return { get: () => value, set: v => { set(v); onChange && onChange(value); } };\n  }\n  return { sum, mean, variance, sd, quantile, median, clamp, fmt, rng, niceTicks, el, chart, segmented };\n})();\n</script>\n```\n:::\n\n\nMuchos modelos, entre ellos KNN, regresión logística y redes neuronales, necesitan una representación numérica de las variables. Una etiqueta como \"Grocery Store\" requiere codificación; el número asignado debe respetar el significado de la categoría.\n\nPero el hecho de que todo deba ser numérico presenta un desafío profundo: **la escala y la naturaleza de los números importan enormemente**.\n\n## El problema de la escala\nImagina que estamos construyendo un modelo predictivo de ventas para **BigMart Sales** mediante k-Vecinos Más Cercanos (KNN)[^5]. Nuestro dataset tiene dos variables numéricas principales:\n- **Item_MRP** (Precio Máximo al Por Menor): Varía de \\$30 a \\$250.\n- **Item_Visibility** (Visibilidad del producto en anaquel): Varía de 0.00 a 0.30.\n\nEl algoritmo KNN calcula la distancia euclidiana entre dos productos $A$ y $B$:\n$$d(A, B) = \\sqrt{(MRP_A - MRP_B)^2 + (Visibilidad_A - Visibilidad_B)^2}$$\n\nSi el producto A tiene un Item_MRP de \\$50 y una visibilidad de 0.02, y el producto B tiene un Item_MRP de \\$51 y una visibilidad de 0.28:\n$$d(A, B) = \\sqrt{(50 - 51)^2 + (0.02 - 0.28)^2} = \\sqrt{(-1)^2 + (-0.26)^2} = \\sqrt{1 + 0.0676} \\approx 1.03$$\n\nComo vemos, **la variable \"Item_MRP\" domina casi por completo el cálculo de la distancia**. Para el algoritmo, una diferencia inmensa en visibilidad (del 2% al 28%) es matemáticamente irrelevante comparada con una modesta diferencia de \\$1 en el precio. Sin un escalado adecuado, nuestro modelo de machine learning se vuelve ciego a las variables numéricamente pequeñas, sin importar su poder predictivo real.\n\n### Laboratorio: el espacio que ve KNN\n\nEl ejemplo anterior tenía dos productos. Aquí tenemos nueve productos de entrenamiento y uno nuevo (★) cuyo vecindario queremos encontrar. La gráfica dibuja los datos **con la misma escala en ambos ejes**, porque así es como la distancia euclidiana «ve» el espacio: si una variable tiene un rango mil veces menor, su eje queda aplastado.\n\n::: {.content-visible when-format=\"html\"}\n```{=html}\n<div class=\"plab\" id=\"conv-knn-lab\">\n  <p class=\"plab-eyebrow\">Laboratorio · Escala y distancias</p>\n  <h3 class=\"plab-title\">¿Quiénes son los 3 vecinos más cercanos de ★?</h3>\n  <p class=\"plab-sub\">Los parámetros de cada escalador se aprenden con los nueve productos de entrenamiento y se aplican también a ★.</p>\n  <div class=\"plab-controls\">\n    <div class=\"plab-field\" style=\"flex:3 1 300px\">Transformación antes de medir distancias\n      <div class=\"plab-seg\" id=\"knn-scaler\">\n        <button type=\"button\" data-value=\"none\" aria-pressed=\"true\">Sin escalar</button>\n        <button type=\"button\" data-value=\"minmax\">Min-Max</button>\n        <button type=\"button\" data-value=\"standard\">StandardScaler</button>\n        <button type=\"button\" data-value=\"robust\">RobustScaler</button>\n      </div>\n    </div>\n  </div>\n  <div class=\"plab-grid\">\n    <div class=\"plab-panel\"><h4>Espacio de distancias (ejes con igual escala)</h4>\n      <svg id=\"knn-chart\" role=\"img\" aria-label=\"Productos en el espacio transformado con los vecinos resaltados\"></svg>\n      <div class=\"plab-legend\"><span><i class=\"dot\" style=\"background:var(--lab-s2)\"></i>producto nuevo ★</span><span><i class=\"dot\" style=\"background:var(--lab-s1)\"></i>vecino</span><span><i class=\"dot\" style=\"background:var(--lab-axis)\"></i>otros</span></div>\n    </div>\n    <div class=\"plab-panel\"><h4>Distancias a ★ y peso de cada variable</h4>\n      <div class=\"plab-scroll\"><div id=\"knn-table\"></div></div>\n    </div>\n  </div>\n  <p class=\"plab-note\" id=\"knn-note\" aria-live=\"polite\"></p>\n</div>\n<script>\n(() => {\n  const K = window.LabKit, root = document.getElementById('conv-knn-lab');\n  const $ = s => root.querySelector(s);\n  const train = [\n    ['P1', 51, 0.28], ['P2', 58, 0.03], ['P3', 45, 0.25], ['P4', 120, 0.02], ['P5', 95, 0.05],\n    ['P6', 60, 0.15], ['P7', 180, 0.10], ['P8', 240, 0.22], ['P9', 70, 0.04]\n  ];\n  const query = ['★', 50, 0.02];\n  function fitScaler(kind, col) {\n    if (kind === 'minmax') { const lo = Math.min(...col), hi = Math.max(...col); return v => (v - lo) / (hi - lo); }\n    if (kind === 'standard') { const m = K.mean(col), s = K.sd(col); return v => (v - m) / s; }\n    if (kind === 'robust') { const med = K.median(col), iqr = K.quantile(col, .75) - K.quantile(col, .25); return v => (v - med) / iqr; }\n    return v => v;\n  }\n  const scaler = K.segmented($('#knn-scaler'), () => render());\n  function render() {\n    const kind = scaler.get();\n    const f = [1, 2].map(j => fitScaler(kind, train.map(r => r[j])));\n    const T = train.map(r => [r[0], f[0](r[1]), f[1](r[2]), r]);\n    const q = [f[0](query[1]), f[1](query[2])];\n    const d = T.map(t => { const dx = (t[1] - q[0]) ** 2, dy = (t[2] - q[1]) ** 2; return { name: t[0], raw: t[3], dist: Math.sqrt(dx + dy), share: dx / (dx + dy || 1), p: [t[1], t[2]] }; })\n      .sort((a, b) => a.dist - b.dist);\n    const nn = new Set(d.slice(0, 3).map(x => x.name));\n    // Ventana con igual escala en ambos ejes: el rango mayor fija el tamaño del cuadrado.\n    const xs = [...T.map(t => t[1]), q[0]], ys = [...T.map(t => t[2]), q[1]];\n    const cx = (Math.min(...xs) + Math.max(...xs)) / 2, cy = (Math.min(...ys) + Math.max(...ys)) / 2;\n    const half = Math.max(Math.max(...xs) - Math.min(...xs), Math.max(...ys) - Math.min(...ys)) * .58;\n    const c = K.chart($('#knn-chart'), { width: 400, height: 394, x: [cx - half, cx + half], y: [cy - half, cy + half], margin: { left: 46, right: 14, top: 14, bottom: 40 } });\n    const lab = kind === 'none' ? ['Item_MRP ($)', 'Item_Visibility'] : ['Item_MRP transformado', 'Item_Visibility transformada'];\n    c.axes({ xTicks: 5, yTicks: 5, xLabel: lab[0], yLabel: lab[1], xFmt: v => K.fmt(v, Math.abs(half) > 20 ? 0 : 1) });\n    d.slice(0, 3).forEach(x => c.line(q[0], q[1], x.p[0], x.p[1], 's1 line thin dash'));\n    d.forEach(x => { c.dot(x.p[0], x.p[1], 6, (nn.has(x.name) ? 's1' : 'muted') + ' dot'); c.text(x.p[0], x.p[1], x.name, { dx: 8, dy: -6, class: nn.has(x.name) ? 'strong' : '' }); });\n    c.dot(q[0], q[1], 8, 's2 dot'); c.text(q[0], q[1], '★ nuevo', { dx: 9, dy: 14, class: 's2' });\n    $('#knn-table').innerHTML = '<table class=\"plab-table\"><thead><tr><th>Producto</th><th>MRP</th><th>Visib.</th><th>Distancia</th><th>% por MRP</th></tr></thead><tbody>' +\n      d.map((x, i) => `<tr${i < 3 ? ' class=\"hl\"' : ''}><td>${i < 3 ? (i + 1) + '.º ' : ''}${x.name}</td><td>${x.raw[1]}</td><td>${K.fmt(x.raw[2], 2)}</td><td>${K.fmt(x.dist, kind === 'none' ? 2 : 3)}</td><td>${K.fmt(100 * x.share, 1)} %</td></tr>`).join('') + '</tbody></table>';\n    const avgShare = K.mean(d.map(x => x.share)), names = d.slice(0, 3).map(x => x.name).join(', '), note = $('#knn-note');\n    if (kind === 'none') { note.className = 'plab-note bad'; note.textContent = `Sin escalar, el precio explica en promedio el ${K.fmt(100 * avgShare, 1)} % de cada distancia al cuadrado. Los vecinos (${names}) se eligen casi solo por precio: P1 tiene visibilidad 0.28 frente a 0.02 de ★ y aun así resulta el más cercano.`; }\n    else { note.className = 'plab-note good'; note.textContent = `Con ${kind === 'minmax' ? 'Min-Max' : kind === 'standard' ? 'StandardScaler' : 'RobustScaler'} ambas variables compiten: el precio aporta en promedio el ${K.fmt(100 * avgShare, 1)} % de cada distancia al cuadrado. Vecinos: ${names}. Que cambien no dice cuál escala es «correcta»; eso se decide validando el modelo.`; }\n  }\n  render();\n})();\n</script>\n```\n:::\n\n::: {.content-visible when-format=\"pdf\"}\nEn la versión web, este laboratorio muestra nueve productos en el espacio que usa la distancia euclidiana. Sin escalar, los tres vecinos del producto nuevo $(50, 0.02)$ son P1, P3 y P2, elegidos casi solo por precio; con cualquiera de los tres escaladores, P1 y P3 (visibilidad alta) salen del vecindario.\n:::\n\n**Guía del laboratorio.** Anota los tres vecinos sin escalar y con cada escalador. ¿Qué productos salen del vecindario en cuanto escalas y por qué? Observa la columna «% por MRP»: sin escalar, supera el 99 % en casi todas las filas. Con Min-Max y StandardScaler los vecinos son P2, P9 y P5; con RobustScaler el tercero pasa a ser P6. Explica esa diferencia a partir de los parámetros que usa cada escalador.\n\n## El peligro de la falsa ordinalidad\nAhora consideremos las variables categóricas. Supongamos que tenemos la variable categórica \"Outlet_Type\" (Tipo de tienda) del dataset BigMart con valores: `Grocery Store`, `Supermarket Type1`, `Supermarket Type3`. \nUna solución ingenua sería asignarles números arbitrarios:\n- `Grocery Store` = 1\n- `Supermarket Type1` = 2\n- `Supermarket Type3` = 3\n\nSi introducimos estos números a un modelo lineal (por ejemplo, regresión lineal), el algoritmo tratará sus diferencias como distancias numéricas que no justifican las categorías:\n1. **Orden falso**: Asumirá que `Supermarket Type1` > `Grocery Store` y `Supermarket Type3` > `Supermarket Type1`.\n2. **Distancia falsa**: Asumirá que la distancia entre `Grocery Store` y `Supermarket Type1` ($2-1=1$) es igual a la distancia entre `Supermarket Type1` y `Supermarket Type3` ($3-2=1$).\n3. **Efecto lineal impuesto**: Un incremento de 1 en el código tendrá el mismo efecto estimado entre las categorías 1 y 2 que entre 2 y 3.\n\nCodificar variables nominales con números enteros arbitrarios destruye los supuestos de la mayoría de los modelos introduciendo patrones falsos que el modelo intentará aprender. Necesitamos técnicas que conviertan categorías a números sin inyectar relaciones espurias.\n\n---\n\n## Desarrollo manual paso a paso\n\nPara comprender verdaderamente lo que hacen las librerías bajo el capó, realicemos las transformaciones más importantes a mano sobre un mini-dataset simulado de 4 productos de **BigMart Sales**:\n\n| ID | Item_MRP | Outlet_Size | Outlet_Type | Target (Item_Outlet_Sales) |\n|----|----------|-------------|-------------|----------------------------|\n| 1  | 45.0     | Small       | Grocery Store | 500                      |\n| 2  | 120.0    | Medium      | Supermarket Type1 | 2500                 |\n| 3  | 180.0    | High        | Supermarket Type3 | 4200                 |\n| 4  | 500.0    | Small       | Grocery Store | 800                      |\n\n*Nota:* El `Item_MRP` del ID 4 (\\$500.0) es un valor atípico (*outlier*) relativo a los otros tres.\n\n### Min-Max scaling (normalización)\nQueremos escalar \"Item_MRP\" a un rango $[0, 1]$.\nLa fórmula es: $x' = \\frac{x - x_{\\min}}{x_{\\max} - x_{\\min}}$\n\n1. $x_{\\min} = 45.0$\n2. $x_{\\max} = 500.0$\n3. Rango = $500.0 - 45.0 = 455.0$\n\nCálculos:\n- $x'_1 = \\frac{45.0 - 45.0}{455.0} = 0.0$\n- $x'_2 = \\frac{120.0 - 45.0}{455.0} = \\frac{75.0}{455.0} \\approx 0.165$\n- $x'_3 = \\frac{180.0 - 45.0}{455.0} = \\frac{135.0}{455.0} \\approx 0.297$\n- $x'_4 = \\frac{500.0 - 45.0}{455.0} = 1.0$\n\n*Observación clave:* El outlier (500.0) comprime a los demás productos en el tercio inferior del rango ($0.0$ a $0.297$), reduciendo su separabilidad.\n\n### StandardScaler ($z$-score)\nEscalamos \"Item_MRP\" para que tenga media 0 y varianza 1.\n\n1. Media ($\\mu$): $\\frac{45 + 120 + 180 + 500}{4} = \\frac{845}{4} = 211.25$\n2. Varianza poblacional[^varpob] ($\\sigma^2$):\n   - $(45 - 211.25)^2 = (-166.25)^2 = 27,639.06$\n   - $(120 - 211.25)^2 = (-91.25)^2 = 8,326.56$\n   - $(180 - 211.25)^2 = (-31.25)^2 = 976.56$\n   - $(500 - 211.25)^2 = (288.75)^2 = 83,376.56$\n   - Suma = $120,318.75$\n   - $\\sigma^2 = \\frac{120,318.75}{4} = 30,079.69 \\implies \\sigma = \\sqrt{30,079.69} \\approx 173.44$\n\nCálculos de $z_i = \\frac{x_i - \\mu}{\\sigma}$:\n- $z_1 = \\frac{45 - 211.25}{173.44} \\approx -0.959$\n- $z_2 = \\frac{120 - 211.25}{173.44} \\approx -0.526$\n- $z_3 = \\frac{180 - 211.25}{173.44} \\approx -0.180$\n- $z_4 = \\frac{500 - 211.25}{173.44} \\approx 1.665$\n\n### RobustScaler (mediana y rango intercuartílico)\nEscalamos usando estadísticas robustas a outliers: $x_{\\text{rob}} = \\frac{x - \\text{mediana}}{\\text{IQR}}$.\n\n1. Datos ordenados: $[45.0, 120.0, 180.0, 500.0]$\n2. Mediana = $\\frac{120.0 + 180.0}{2} = 150.0$\n3. Con el percentil interpolado que usa `RobustScaler` de scikit-learn por defecto: $Q_1 = 101.25$ y $Q_3 = 260.0$[^6].\n4. $\\text{IQR} = Q_3 - Q_1 = 260.0 - 101.25 = 158.75$.\n\nCálculos:\n- $x_{\\text{rob}, 1} = \\frac{45 - 150}{158.75} \\approx -0.661$\n- $x_{\\text{rob}, 2} = \\frac{120 - 150}{158.75} \\approx -0.189$\n- $x_{\\text{rob}, 3} = \\frac{180 - 150}{158.75} \\approx 0.189$\n- $x_{\\text{rob}, 4} = \\frac{500 - 150}{158.75} \\approx 2.205$\n\n**Lectura del resultado:** la mediana cambia menos que la media ante un extremo, pero con solo cuatro datos el cuartil superior también depende del valor 500. \"Robusto\" no significa inmune.\n\n### One-Hot Encoding y la trampa de la variable ficticia\nCodificamos `Outlet_Type`: `{Grocery Store, Supermarket Type1, Supermarket Type3}`. Sin embargo, si tuviéramos cientos de categorías, One-Hot Encoding induciría la *Maldición de la Dimensionalidad*[^1] y requeriría el uso de *matrices dispersas*[^2] para optimizar la memoria.\n\n| ID | Outlet_Type_Grocery | Outlet_Type_Supermarket1 | Outlet_Type_Supermarket3 |\n|----|:-------------------:|:------------------------:|:------------------------:|\n| 1  | 1                   | 0                        | 0                        |\n| 2  | 0                   | 1                        | 0                        |\n| 3  | 0                   | 0                        | 1                        |\n| 4  | 1                   | 0                        | 0                        |\n\n*La trampa de la variable ficticia:* Observe que la suma de las tres columnas es siempre igual a 1:\n$$\\text{Grocery} + \\text{Supermarket1} + \\text{Supermarket3} = 1$$\nSi un modelo lineal sin regularización incluye un intercepto $\\beta_0$, existe colinealidad perfecta[^4]. Una opción es descartar una columna de referencia (`drop='first'`); no es una regla universal para árboles ni para todo modelo regularizado.\n\n### Target encoding (mean encoding) suavizado\nEl *Target Encoding* reemplaza cada categoría por el promedio del target (`Item_Outlet_Sales`) en esa categoría:\n- Media global del target ($\\bar{y}_{\\text{global}}$) = $\\frac{500 + 2500 + 4200 + 800}{4} = 2000.0$\n- **Grocery Store**: 2 ocurrencias. Ventas = $[500, 800]$. Media local $\\bar{y}_c = 650.0$.\n- **Supermarket Type1**: 1 ocurrencia. Ventas = $[2500]$. Media local $\\bar{y}_c = 2500.0$.\n- **Supermarket Type3**: 1 ocurrencia. Ventas = $[4200]$. Media local $\\bar{y}_c = 4200.0$.\n\nPara evitar sobreajuste en categorías poco frecuentes, aplicamos **suavizado bayesiano**[^bayes] (*m-estimate*):\n$$ \\hat{S}_i = \\frac{n_c \\cdot \\bar{y}_c + m \\cdot \\bar{y}_{\\text{global}}}{n_c + m} $$\nCon factor de suavizado $m = 2$ (cálculo ilustrativo que **no** debe aplicarse directamente a las mismas filas de entrenamiento):\n- **Grocery Store**: $\\frac{(2 \\times 650) + (2 \\times 2000)}{2 + 2} = \\frac{1300 + 4000}{4} = 1325.0$\n- **Supermarket Type1**: $\\frac{(1 \\times 2500) + (2 \\times 2000)}{1 + 2} = \\frac{2500 + 4000}{3} \\approx 2166.67$\n- **Supermarket Type3**: $\\frac{(1 \\times 4200) + (2 \\times 2000)}{1 + 2} = \\frac{4200 + 4000}{3} \\approx 2733.33$\n\n---\n\n## Formalización teórica y matemática\n\n### Escaladores numéricos\n1. **Min-Max Scaler**: Mapea una variable continua al intervalo $[a, b]$ (típicamente $[0, 1]$):\n   $$ x' = a + \\frac{x - x_{\\min}}{x_{\\max} - x_{\\min}} (b - a) $$\n   Es altamente sensible a outliers, ya que un único valor extremo dilata el denominador $x_{\\max} - x_{\\min}$.\n\n2. **StandardScaler ($z$-score)**: Transforma la variable para que tenga media $\\mu = 0$ y desviación estándar $\\sigma = 1$:\n   $$ z = \\frac{x - \\mu}{\\sigma}, \\quad \\mathbb{E}[Z] = 0, \\quad \\operatorname{Var}(Z) = 1 $$\n   Ambas igualdades salen de la linealidad de la esperanza[^linealidad]: $\\mathbb{E}[(X-\\mu)/\\sigma]=(\\mathbb{E}[X]-\\mu)/\\sigma=0$ y $\\operatorname{Var}(aX+b)=a^2\\operatorname{Var}(X)$, con $a=1/\\sigma$. Min-Max y StandardScaler son transformaciones afines: conservan el orden y las proporciones entre diferencias, así que **no cambian la forma** de la distribución ni reducen la influencia relativa de un valor extremo.\n\n3. **RobustScaler**: Utiliza estadísticas de posición no paramétricas resistentes a valores extremos:\n   $$ x_{\\text{rob}} = \\frac{x - \\operatorname{mediana}(X)}{\\text{IQR}(X)}, \\quad \\text{IQR}(X) = Q_3(X) - Q_1(X) $$\n\n4. **Transformaciones de Potencia**: Diseñadas para estabilizar la varianza y aproximar normalidad en distribuciones asimétricas (sesgadas):\n   - **Box-Cox**[^boxcox] (solo para $y > 0$):\n     $$ y^{(\\lambda)} = \\begin{cases} \\frac{y^\\lambda - 1}{\\lambda} & \\text{si } \\lambda \\neq 0 \\\\ \\ln(y) & \\text{si } \\lambda = 0 \\end{cases} $$\n   - **Yeo-Johnson** (soporta valores positivos, cero y negativos).\n\n### Codificación categórica\n1. **One-Hot Encoding**:\n   Definimos un conjunto finito de categorías $\\mathcal{C} = \\{c_1, c_2, \\dots, c_K\\}$.\n   La función de codificación es $h: \\mathcal{C} \\to \\{0, 1\\}^K$ tal que $h(c_j)$ es un vector donde la componente $j$ es 1 y el resto son 0.\n   Si se incluye la matriz de diseño $X$ con las $K$ columnas junto a una columna de unos $\\mathbf{1}$ para el intercepto:\n   $$ \\sum_{k=1}^K X_{i,k} = 1 \\quad \\forall i $$\n   Esto genera una dependencia lineal exacta, haciendo que la matriz $X^T X$ sea singular e imposible de invertir mediante mínimos cuadrados ordinarios.\n\n2. **Target encoding con suavizado**:\n   Sea $y_i$ el objetivo continuo asociado a la observación $i$ con categoría $c$. Combinamos la media local con la global mediante la siguiente fórmula ilustrativa de suavizado:\n   $$ \\hat{S}_c = \\lambda(n_c) \\bar{y}_c + (1 - \\lambda(n_c)) \\bar{y}_{\\text{global}} $$\n   Donde $\\lambda(n_c) = \\frac{n_c}{n_c + m}$ es el factor de contracción (*shrinkage*). Cuando $n_c \\to \\infty$, $\\lambda(n_c) \\to 1$ (confianza en la media local). Cuando $n_c \\to 0$, $\\lambda(n_c) \\to 0$ (confianza en la media global).\n\n---\n\n## Laboratorio interactivo: banco de pruebas de escalado y codificación (BigMart)\n\n::: {.content-visible when-format=\"html\"}\n```{=html}\n<div class=\"plab\" id=\"conv-bench-lab\">\n  <p class=\"plab-eyebrow\">Laboratorio · Escaladores y codificadores</p>\n  <h3 class=\"plab-title\">Un precio extremo y una categoría rara</h3>\n  <p class=\"plab-sub\">Usa los cuatro productos del desarrollo manual. Mueve el precio del producto 4 y compara los tres escaladores a la vez; después cambia la codificación de <code>Outlet_Type</code>.</p>\n  <div class=\"plab-panel\">\n    <div class=\"plab-controls\">\n      <label>Precio del producto 4 (atípico): <b id=\"bench-out-v\"></b><input type=\"range\" id=\"bench-out\" min=\"200\" max=\"1000\" step=\"25\" value=\"500\"></label>\n    </div>\n    <svg id=\"bench-strips\" class=\"wide\" role=\"img\" aria-label=\"Valores escalados por los tres escaladores\"></svg>\n    <div class=\"plab-legend\"><span><i class=\"dot\" style=\"background:var(--lab-s1)\"></i>productos 1–3</span><span><i class=\"dot\" style=\"background:var(--lab-s5)\"></i>producto 4 (atípico)</span><span><i style=\"background:var(--lab-s3)\"></i>separación entre los productos 1 y 3</span></div>\n    <div class=\"plab-scroll\" style=\"margin-top:.6rem\"><div id=\"bench-table\"></div></div>\n  </div>\n  <div class=\"plab-panel\" style=\"margin-top:1rem\">\n    <div class=\"plab-controls\">\n      <div class=\"plab-field\" style=\"flex:2 1 260px\">Codificación de <code>Outlet_Type</code>\n        <div class=\"plab-seg\" id=\"bench-enc\">\n          <button type=\"button\" data-value=\"onehot\" aria-pressed=\"true\">One-Hot</button>\n          <button type=\"button\" data-value=\"drop\">One-Hot con drop='first'</button>\n          <button type=\"button\" data-value=\"target\">Target encoding</button>\n        </div>\n      </div>\n      <label id=\"bench-m-wrap\">Suavizado m: <b id=\"bench-m-v\"></b><input type=\"range\" id=\"bench-m\" min=\"0\" max=\"10\" step=\"0.5\" value=\"2\"></label>\n    </div>\n    <svg id=\"bench-target\" class=\"wide\" role=\"img\" aria-label=\"Medias locales, global y codificadas por categoría\"></svg>\n    <div class=\"plab-scroll\"><div id=\"bench-enc-table\"></div></div>\n    <p class=\"plab-note\" id=\"bench-enc-note\" aria-live=\"polite\"></p>\n  </div>\n</div>\n<script>\n(() => {\n  const K = window.LabKit, root = document.getElementById('conv-bench-lab');\n  const $ = s => root.querySelector(s);\n  const base = [45, 120, 180];\n  const outlets = ['Grocery Store', 'Supermarket Type1', 'Supermarket Type3', 'Grocery Store'];\n  const targets = [500, 2500, 4200, 800];\n  const cats = ['Grocery Store', 'Supermarket Type1', 'Supermarket Type3'];\n  function scalers(x) {\n    const lo = Math.min(...x), hi = Math.max(...x), m = K.mean(x), s = K.sd(x);\n    const med = K.median(x), q1 = K.quantile(x, .25), q3 = K.quantile(x, .75);\n    return [\n      { name: 'Min-Max', f: v => (v - lo) / (hi - lo), par: `mín ${K.fmt(lo, 0)}, máx ${K.fmt(hi, 0)}` },\n      { name: 'StandardScaler', f: v => (v - m) / s, par: `μ ${K.fmt(m, 1)}, σ ${K.fmt(s, 1)}` },\n      { name: 'RobustScaler', f: v => (v - med) / (q3 - q1), par: `mediana ${K.fmt(med, 1)}, IQR ${K.fmt(q3 - q1, 1)}` }\n    ];\n  }\n  function renderScale() {\n    const out = +$('#bench-out').value; $('#bench-out-v').textContent = '$' + out;\n    const x = [...base, out], S = scalers(x);\n    const c = K.chart($('#bench-strips'), { width: 640, height: 230, x: [-1.5, 6], y: [0, 3], margin: { left: 110, right: 16, top: 10, bottom: 34 } });\n    c.axes({ xTicks: 8, yTicks: 0, xLabel: 'valor escalado', xFmt: v => K.fmt(v, 0) });\n    S.forEach((sc, i) => {\n      const y = 2.5 - i, v = x.map(sc.f);\n      c.line(-1.5, y, 6, y, 'muted line thin').style.opacity = .35;\n      c.text(-1.5, y, sc.name, { 'text-anchor': 'end', dx: -8, dy: 4, class: 'strong' });\n      const band = c.rect(v[0], y - .16, v[2], y + .16, 's3'); band.style.fillOpacity = .22; band.style.strokeWidth = 0;\n      c.text((v[0] + v[2]) / 2, y, 'separación ' + K.fmt(v[2] - v[0], 2), { 'text-anchor': 'middle', dy: -14, class: 's3' });\n      v.forEach((z, k) => c.dot(Math.min(z, 5.9), y, 6, (k === 3 ? 's5' : 's1') + ' dot'));\n      if (v[3] > 5.9) c.text(5.9, y, `→ ${K.fmt(v[3], 2)}`, { dx: 8, dy: 4, class: 's5' });\n    });\n    $('#bench-table').innerHTML = '<table class=\"plab-table\"><thead><tr><th>Escalador</th><th>Parámetros aprendidos</th><th>ID 1</th><th>ID 2</th><th>ID 3</th><th>ID 4</th></tr></thead><tbody>' +\n      S.map(sc => `<tr><td>${sc.name}</td><td>${sc.par}</td>${x.map((v, k) => `<td${k === 3 ? ' style=\"color:var(--lab-s5)\"' : ''}>${K.fmt(sc.f(v), 3)}</td>`).join('')}</tr>`).join('') + '</tbody></table>';\n  }\n  const enc = K.segmented($('#bench-enc'), () => renderEnc());\n  function renderEnc() {\n    const mode = enc.get(), m = +$('#bench-m').value, note = $('#bench-enc-note');\n    $('#bench-m-v').textContent = K.fmt(m, 1);\n    $('#bench-m-wrap').style.visibility = mode === 'target' ? 'visible' : 'hidden';\n    const svg = $('#bench-target');\n    if (mode !== 'target') {\n      svg.style.display = 'none';\n      const cols = mode === 'drop' ? cats.slice(1) : cats;\n      $('#bench-enc-table').innerHTML = '<table class=\"plab-table\"><thead><tr><th>ID</th><th>Outlet_Type</th>' + cols.map(c => `<th>${c.replace('Supermarket ', 'SM_').replace('Grocery Store', 'Grocery')}</th>`).join('') + '<th>suma</th></tr></thead><tbody>' +\n        outlets.map((o, i) => { const v = cols.map(c => +(o === c)); return `<tr><td>${i + 1}</td><td>${o}</td>${v.map(b => `<td${b ? ' class=\"hl\"' : ''}>${b}</td>`).join('')}<td>${K.sum(v)}</td></tr>`; }).join('') + '</tbody></table>';\n      note.className = mode === 'drop' ? 'plab-note' : 'plab-note warn';\n      note.textContent = mode === 'drop'\n        ? 'Sin la columna Grocery, dos ceros significan «Grocery Store». Desaparece la dependencia lineal con el intercepto, pero una categoría nueva con handle_unknown=\"ignore\" también produciría dos ceros.'\n        : 'Cada fila suma 1 (columna «suma»): junto con el intercepto de una regresión, las tres columnas son linealmente dependientes y XᵀX no se puede invertir.';\n      return;\n    }\n    svg.style.display = '';\n    const g = K.mean(targets);\n    const st = cats.map(cat => { const y = targets.filter((_, i) => outlets[i] === cat); const loc = K.mean(y); return { cat, y, n: y.length, loc, enc: (y.length * loc + m * g) / (y.length + m) }; });\n    const c = K.chart(svg, { width: 640, height: 220, x: [0, 4600], y: [0, 3], margin: { left: 130, right: 16, top: 10, bottom: 36 } });\n    c.axes({ xTicks: 5, yTicks: 0, xLabel: 'Item_Outlet_Sales', xFmt: v => K.fmt(v, 0) });\n    c.line(g, 0, g, 3, 'muted line dash');\n    c.text(g, 3, `media global ${K.fmt(g, 0)}`, { 'text-anchor': 'middle', dy: 10 });\n    st.forEach((s, i) => {\n      const y = 2.35 - i * .85;\n      c.text(0, y, `${s.cat} (n=${s.n})`, { 'text-anchor': 'end', dx: -8, dy: 4, class: 'strong' });\n      s.y.forEach(v => c.dot(v, y, 4, 'muted'));\n      if (Math.abs(s.enc - s.loc) > 30) c.arrow(s.loc, y, s.enc + (s.enc > s.loc ? -60 : 60), y, 's2');\n      c.dot(s.loc, y, 6.5, 's1 dot'); c.dot(s.enc, y, 6.5, 's2 dot');\n      c.text(s.enc, y, K.fmt(s.enc, 0), { 'text-anchor': 'middle', dy: -11, class: 's2' });\n    });\n    $('#bench-enc-table').innerHTML = '<table class=\"plab-table\"><thead><tr><th>Categoría</th><th>n</th><th>media local</th><th>peso local n/(n+m)</th><th>codificado</th></tr></thead><tbody>' +\n      st.map(s => `<tr><td>${s.cat}</td><td>${s.n}</td><td>${K.fmt(s.loc, 1)}</td><td>${K.fmt(s.n / (s.n + m), 2)}</td><td class=\"hl\">${K.fmt(s.enc, 1)}</td></tr>`).join('') + '</tbody></table>';\n    note.className = 'plab-note';\n    note.textContent = `Puntos azules: media local; naranjas: valor codificado. Con m = ${K.fmt(m, 1)}, una categoría con una sola fila conserva solo el ${K.fmt(100 / (1 + m), 0)} % de su media local y toma el resto de la global (${K.fmt(g, 0)}). El suavizado no evita que una fila use su propio objetivo: eso lo resuelve la codificación fuera de pliegue.`;\n  }\n  $('#bench-out').addEventListener('input', renderScale);\n  $('#bench-m').addEventListener('input', renderEnc);\n  renderScale(); renderEnc();\n})();\n</script>\n```\n:::\n::: {.content-visible when-format=\"pdf\"}\n*(En la versión web del libro, un laboratorio interactivo compara los tres escaladores al mover el precio atípico y muestra cómo el suavizado $m$ acerca cada categoría a la media global).*\n:::\n\n### Guía del laboratorio\n\n**Objetivo.** Distinguir entre el efecto de un valor extremo sobre tres escaladores y el efecto de la frecuencia de una categoría sobre su codificación.\n\n1. Fija el precio atípico en 500 y anota el valor escalado del producto 2 con Min-Max, StandardScaler y RobustScaler. Contrasta RobustScaler con el cálculo manual anterior.\n2. Mueve el precio a 1000 sin cambiar los otros tres. Registra qué estadísticas cambian y si alguno de los tres escaladores es completamente inmune.\n3. En codificación, activa y desactiva `drop='first'`; identifica la categoría representada por dos ceros. Después cambia a *target encoding* y compara `m=0` con `m=10` para una categoría con una sola fila.\n\n**Comprobación.** Para 500, Min-Max asigna al producto 2 aproximadamente 0.165 y RobustScaler aproximadamente −0.189. Si no coinciden, revisa el percentil usado para los cuartiles. En *target encoding*, al aumentar $m$ las categorías con una observación se acercan más a la media global.\n\n**Interpretación y entrega.** Escribe dos frases: cuál escalador elegirías para un modelo de distancias con precios extremos y qué información adicional necesitas antes de decidirlo; explica por qué las medias de ventas mostradas en este panel no deben calcularse con el objetivo de la propia fila al entrenar.\n\n::: {.callout-warning title=\"El panel enseña la fórmula, no un pipeline de entrenamiento\"}\nEl panel usa las cuatro ventas para calcular la media de cada categoría. En un modelo real, ajusta el codificador solo con el conjunto de entrenamiento y utiliza codificación fuera de pliegue para las filas de entrenamiento; transforma validación y prueba con el codificador ya ajustado. Así evitas que una fila reciba información de su propio objetivo[^3].\n:::\n\n---\n\n## Implementación computacional (Python y pandas)\n\nA continuación, mostramos cómo implementar estas transformaciones de manera profesional sobre el caso **BigMart Sales**.\n\n::: {.callout-tip title=\"Mejores prácticas en la industria\"}\n- **Conserva el esquema de categorías:** `pandas.get_dummies()` sirve para explorar, pero exige alinear columnas entre entrenamiento e inferencia. Un `OneHotEncoder` ajustado en entrenamiento conserva ese esquema y facilita integrarlo en un `Pipeline`[^7].\n- **Escala según el modelo:** los árboles de decisión que hacen cortes por umbral suelen ser invariantes a transformaciones monótonas de una variable; los modelos de distancias y los penalizados suelen ser sensibles a la escala[^5].\n:::\n\n::: {#548ff168 .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nimport numpy as np\nfrom sklearn.preprocessing import (\n    StandardScaler, MinMaxScaler, RobustScaler, \n    OneHotEncoder, TargetEncoder\n)\n\n# 1. Dataset Sintético representativo de BigMart Sales\nnp.random.seed(42)\nn_samples = 100\ndata = pd.DataFrame({\n    'Item_MRP': np.random.normal(140, 45, n_samples),\n    'Item_Weight': np.random.normal(12.8, 4.2, n_samples),\n    'Outlet_Type': np.random.choice(['Grocery Store', 'Supermarket Type1', 'Supermarket Type2', 'Supermarket Type3'], n_samples, p=[0.2, 0.5, 0.15, 0.15]),\n    'Item_Fat_Content': np.random.choice(['Low Fat', 'Regular'], n_samples),\n    'Outlet_Establishment_Year': np.random.choice([1985, 1997, 1999, 2004, 2009], n_samples),\n    'Item_Outlet_Sales': np.random.exponential(2000, n_samples)\n})\n\n# Inyectar un Outlier masivo en Item_MRP para probar el RobustScaler\ndata.loc[99, 'Item_MRP'] = 750.0 \n\ndata.head()\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Item_MRP</th>\n      <th>Item_Weight</th>\n      <th>Outlet_Type</th>\n      <th>Item_Fat_Content</th>\n      <th>Outlet_Establishment_Year</th>\n      <th>Item_Outlet_Sales</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>162.352137</td>\n      <td>6.855443</td>\n      <td>Supermarket Type3</td>\n      <td>Low Fat</td>\n      <td>2009</td>\n      <td>6373.902143</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>133.778106</td>\n      <td>11.033290</td>\n      <td>Supermarket Type2</td>\n      <td>Regular</td>\n      <td>2009</td>\n      <td>119.211065</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>169.145984</td>\n      <td>11.360599</td>\n      <td>Supermarket Type1</td>\n      <td>Low Fat</td>\n      <td>1999</td>\n      <td>1003.473435</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>208.536344</td>\n      <td>9.430435</td>\n      <td>Supermarket Type2</td>\n      <td>Low Fat</td>\n      <td>2004</td>\n      <td>225.791146</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>129.463098</td>\n      <td>12.122600</td>\n      <td>Supermarket Type1</td>\n      <td>Low Fat</td>\n      <td>1985</td>\n      <td>817.922620</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n### Escalado numérico comparativo\n\n::: {#1e1542c4 .cell execution_count=2}\n``` {.python .cell-code}\n# Instanciamos los escaladores\nstd_scaler = StandardScaler()\nminmax_scaler = MinMaxScaler()\nrobust_scaler = RobustScaler()\n\n# Aplicamos y concatenamos para comparar\nscaled_df = pd.DataFrame({\n    'MRP_Original': data['Item_MRP'],\n    'MRP_Standard': std_scaler.fit_transform(data[['Item_MRP']]).flatten(),\n    'MRP_MinMax': minmax_scaler.fit_transform(data[['Item_MRP']]).flatten(),\n    'MRP_Robust': robust_scaler.fit_transform(data[['Item_MRP']]).flatten(),\n})\n\n# Mostrar las últimas filas donde está el Outlier\nscaled_df.tail()\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>MRP_Original</th>\n      <th>MRP_Standard</th>\n      <th>MRP_MinMax</th>\n      <th>MRP_Robust</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>95</th>\n      <td>74.141827</td>\n      <td>-0.917680</td>\n      <td>0.071481</td>\n      <td>-1.243182</td>\n    </tr>\n    <tr>\n      <th>96</th>\n      <td>153.325412</td>\n      <td>0.160588</td>\n      <td>0.180267</td>\n      <td>0.353934</td>\n    </tr>\n    <tr>\n      <th>97</th>\n      <td>151.747487</td>\n      <td>0.139101</td>\n      <td>0.178099</td>\n      <td>0.322107</td>\n    </tr>\n    <tr>\n      <th>98</th>\n      <td>140.230106</td>\n      <td>-0.017735</td>\n      <td>0.162276</td>\n      <td>0.089804</td>\n    </tr>\n    <tr>\n      <th>99</th>\n      <td>750.000000</td>\n      <td>8.285695</td>\n      <td>1.000000</td>\n      <td>12.388731</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n### Codificación categórica\n\n::: {.callout-important title=\"Regla de oro en producción\"}\nPara categorías nuevas, decide explícitamente una política: `handle_unknown='ignore'` en `OneHotEncoder` produce ceros para una categoría desconocida. Comprueba si esa representación puede confundirse con la categoría de referencia cuando usas `drop='first'`; otra opción es agrupar categorías infrecuentes.\n:::\n\n::: {#f539f22a .cell execution_count=3}\n``` {.python .cell-code}\n# 1. One-Hot Encoding (Variables Nominales de Baja Cardinalidad)\nohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')\noutlet_encoded = ohe.fit_transform(data[['Outlet_Type']])\noutlet_columns = ohe.get_feature_names_out(['Outlet_Type'])\n\ndf_ohe = pd.DataFrame(outlet_encoded, columns=outlet_columns)\ndf_ohe.head(3)\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Outlet_Type_Grocery Store</th>\n      <th>Outlet_Type_Supermarket Type1</th>\n      <th>Outlet_Type_Supermarket Type2</th>\n      <th>Outlet_Type_Supermarket Type3</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>0.0</td>\n      <td>0.0</td>\n      <td>0.0</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>0.0</td>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>0.0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#62f2b3ad .cell execution_count=4}\n``` {.python .cell-code}\n# 2. Target Encoding con regularización automática en scikit-learn\ntarget_enc = TargetEncoder(smooth=\"auto\") \ndata['Outlet_Type_TargetEncoded'] = target_enc.fit_transform(data[['Outlet_Type']], data['Item_Outlet_Sales'])\n\n# Inspección de las medias codificadas por tipo de tienda\ndata[['Outlet_Type', 'Outlet_Type_TargetEncoded', 'Item_Outlet_Sales']].drop_duplicates('Outlet_Type')\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Outlet_Type</th>\n      <th>Outlet_Type_TargetEncoded</th>\n      <th>Item_Outlet_Sales</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Supermarket Type3</td>\n      <td>1463.958066</td>\n      <td>6373.902143</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Supermarket Type2</td>\n      <td>1193.408030</td>\n      <td>119.211065</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Supermarket Type1</td>\n      <td>2304.724830</td>\n      <td>1003.473435</td>\n    </tr>\n    <tr>\n      <th>19</th>\n      <td>Grocery Store</td>\n      <td>1737.340917</td>\n      <td>158.520184</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {.callout-warning title=\"Target Leakage\"}\nEl *target encoding* usa la variable $Y$ (`Item_Outlet_Sales`) para transformar las $X$. `TargetEncoder.fit_transform` utiliza particiones internas para codificar las filas de entrenamiento fuera del pliegue[^3]. Esta protección no sustituye la separación externa de entrenamiento, validación y prueba: ajusta todo el preprocesamiento dentro de cada pliegue externo.\n:::\n\n### Ingeniería de fechas y ciclos\n\n::: {#01d32e4a .cell execution_count=5}\n``` {.python .cell-code}\n# Transformar año de establecimiento en Antigüedad de la tienda\ncurrent_year = 2013 # Año de corte del dataset BigMart\ndata['Outlet_Age'] = current_year - data['Outlet_Establishment_Year']\ndata[['Outlet_Establishment_Year', 'Outlet_Age']].head(3)\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Outlet_Establishment_Year</th>\n      <th>Outlet_Age</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>2009</td>\n      <td>4</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>2009</td>\n      <td>4</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>1999</td>\n      <td>14</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n---\n\n## Referencias y definiciones\n\n[^1]: **Maldición de la Dimensionalidad**: A medida que aumenta el número de características (dimensiones), el volumen del espacio de características crece exponencialmente. Los datos se vuelven dispersos, y las medidas de distancia (como la Euclidiana) pierden significado, degradando severamente modelos espaciales como KNN. Ocurre rápido si aplicamos One-Hot a campos como `Item_Identifier` (más de 1,500 códigos únicos).\n\n[^2]: **Matrices Dispersas (CSR - Compressed Sparse Row)**: Estructura de datos en memoria que no guarda los ceros. Una matriz One-Hot de alta cardinalidad tiene más del 99% de ceros. Una matriz CSR solo guarda las coordenadas y valores de las celdas no nulas, ahorrando gigabytes de memoria RAM.\n\n[^3]: **Target Leakage (Fuga de la Variable Objetivo)**: Ocurre cuando información del target se filtra en las variables predictoras durante el preprocesamiento. En Target Encoding ingenuo, promediar el target incluyendo el registro actual permite al modelo memorizar el dataset en lugar de generalizar.\n\n[^4]: **Trampa de la variable ficticia (Dummy Variable Trap)**: Dependencia lineal exacta entre intercepto y todas las columnas binarias de una categoría exhaustiva. En mínimos cuadrados ordinarios puede eliminarse una columna o el intercepto; otros estimadores requieren una evaluación distinta.\n\n[^5]: **Escala y modelos**: KNN usa distancias entre observaciones. Un árbol que separa con umbrales sobre una sola variable conserva, en general, el orden de los valores bajo una transformación monótona; detalles numéricos e implementaciones pueden producir diferencias. Escalar redes neuronales y modelos penalizados suele facilitar la optimización o comparación de coeficientes, pero debe comprobarse en validación.\n\n[^6]: **Percentil interpolado**: Para cuatro datos ordenados, el percentil 25 queda a 0.75 del tramo entre el primero y el segundo; el 75 queda a 0.25 del tramo entre el tercero y el cuarto. Hay otras convenciones de cuartiles, por lo que conviene declarar la usada.\n\n[^7]: **Pipeline**: Secuencia que ajusta transformaciones y estimador juntos. En validación cruzada, cada ajuste aprende estadísticas solo de la parte de entrenamiento del pliegue.\n\n[^varpob]: **Varianza poblacional frente a muestral:** aquí dividimos entre $n=4$ porque `StandardScaler` usa esa convención (equivale a `numpy.std` con `ddof=0`). La varianza muestral divide entre $n-1$ y es la que usan `pandas.Series.std` y la mayoría de pruebas estadísticas. Con pocos datos la diferencia es visible: $\\sqrt{120{,}318.75/3}\\approx200.3$ frente a $173.4$.\n\n[^bayes]: **Suavizado bayesiano:** el valor codificado es la media *a posteriori* de la categoría si, antes de ver sus datos, suponemos que su media se parece a la global con una confianza equivalente a $m$ observaciones «imaginarias». Con pocas filas reales domina esa creencia previa; con muchas, dominan los datos.\n\n[^boxcox]: **Box-Cox:** el parámetro $\\lambda$ no se elige a mano: `PowerTransformer` lo estima por máxima verosimilitud, buscando el valor con el que los datos transformados se parecen más a una distribución normal. Como todo parámetro aprendido, debe ajustarse solo con entrenamiento.\n\n[^linealidad]: **Linealidad de la esperanza:** para constantes $a$ y $b$, $\\mathbb{E}[aX+b]=a\\,\\mathbb{E}[X]+b$. La varianza, en cambio, ignora los desplazamientos y escala con el cuadrado: $\\operatorname{Var}(aX+b)=a^2\\operatorname{Var}(X)$.\n\n",
    "supporting": [
      "4-3-conversion_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}